<script> import "$lib/vihtml/ayu_dark_python.css" </script>

<section class="ayu_dark_python boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr">  1 </span><span class="ayu_dark_python Include">from</span> <span class="ayu_dark_python -variable"><span class="ayu_dark_python -module">functools</span></span> <span class="ayu_dark_python Include">import</span> <span class="ayu_dark_python -variable">reduce</span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr">  2 </span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr">  3 </span><span class="ayu_dark_python Include">from</span> <span class="ayu_dark_python -variable"><span class="ayu_dark_python -module">werkzeug</span></span><span class="ayu_dark_python -punctuation-delimiter">.</span><span class="ayu_dark_python -variable"><span class="ayu_dark_python -module">exceptions</span></span> <span class="ayu_dark_python Include">import</span> <span class="ayu_dark_python -variable"><span class="ayu_dark_python Type">NotFound</span></span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr">  4 </span><span class="ayu_dark_python Include">from</span> <span class="ayu_dark_python -variable"><span class="ayu_dark_python -module">werkzeug</span></span><span class="ayu_dark_python -punctuation-delimiter">.</span><span class="ayu_dark_python -variable"><span class="ayu_dark_python -module">utils</span></span> <span class="ayu_dark_python Include">import</span> <span class="ayu_dark_python -variable">redirect</span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr">  5 </span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr">  6 </span><span class="ayu_dark_python Include">from</span> <span class="ayu_dark_python -punctuation-delimiter">.</span><span class="ayu_dark_python -variable"><span class="ayu_dark_python -module">application</span></span> <span class="ayu_dark_python Include">import</span> <span class="ayu_dark_python -variable"><span class="ayu_dark_python Type">Page</span></span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr">  7 </span><span class="ayu_dark_python Include">from</span> <span class="ayu_dark_python -punctuation-delimiter">.</span><span class="ayu_dark_python -variable"><span class="ayu_dark_python -module">utils</span></span> <span class="ayu_dark_python Include">import</span> <span class="ayu_dark_python -variable">unicodecmp</span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr">  8 </span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr">  9 </span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr"> 10 </span><span class="ayu_dark_python -keyword">class</span> <span class="ayu_dark_python -variable"><span class="ayu_dark_python Type"><span class="ayu_dark_python Type">ServerList</span></span></span><span class="ayu_dark_python -punctuation-bracket">(</span><span class="ayu_dark_python -variable"><span class="ayu_dark_python Type"><span class="ayu_dark_python Type">Page</span></span></span><span class="ayu_dark_python -punctuation-bracket">)</span><span class="ayu_dark_python -punctuation-delimiter">:</span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr"> 11 </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python -variable"><span class="ayu_dark_python -variable-member">url_rule</span></span> <span class="ayu_dark_python -operator">=</span> <span class="ayu_dark_python -string">&quot;/&quot;</span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr"> 12 </span><span class="ayu_dark_python NonText">│</span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr"> 13 </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python -keyword-function">def</span> <span class="ayu_dark_python -variable"><span class="ayu_dark_python -function"><span class="ayu_dark_python -function-method">order_link</span></span></span><span class="ayu_dark_python -punctuation-bracket">(</span><span class="ayu_dark_python -variable"><span class="ayu_dark_python -variable-parameter"><span class="ayu_dark_python -variable-builtin">self</span></span></span><span class="ayu_dark_python -punctuation-delimiter">,</span> <span class="ayu_dark_python -variable"><span class="ayu_dark_python -variable-parameter">name</span></span><span class="ayu_dark_python -punctuation-delimiter">,</span> <span class="ayu_dark_python -variable"><span class="ayu_dark_python -variable-parameter">title</span></span><span class="ayu_dark_python -punctuation-bracket">)</span><span class="ayu_dark_python -punctuation-delimiter">:</span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr"> 14 </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python -variable"><span class="ayu_dark_python -variable-builtin">cls</span></span> <span class="ayu_dark_python -operator">=</span> <span class="ayu_dark_python -string">&quot;&quot;</span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr"> 15 </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python -variable">link</span> <span class="ayu_dark_python -operator">=</span> <span class="ayu_dark_python -string">f&quot;?order_by=<span class="ayu_dark_python -none"><span class="ayu_dark_python -punctuation-bracket"><span class="ayu_dark_python Special">&#123;</span></span><span class="ayu_dark_python -variable">name</span><span class="ayu_dark_python -punctuation-bracket"><span class="ayu_dark_python Special">&#125;</span></span></span>&quot;</span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr"> 16 </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python -variable">desc</span> <span class="ayu_dark_python -operator">=</span> <span class="ayu_dark_python Boolean">False</span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr"> 17 </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python -keyword-conditional">if</span> <span class="ayu_dark_python -variable">name</span> <span class="ayu_dark_python -operator">==</span> <span class="ayu_dark_python -variable"><span class="ayu_dark_python -variable-builtin">self</span></span><span class="ayu_dark_python -punctuation-delimiter">.</span><span class="ayu_dark_python -variable"><span class="ayu_dark_python -variable-member">order_by</span></span><span class="ayu_dark_python -punctuation-delimiter">:</span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr"> 18 </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python -variable">desc</span> <span class="ayu_dark_python -operator">=</span> <span class="ayu_dark_python -keyword-operator">not</span> <span class="ayu_dark_python -variable"><span class="ayu_dark_python -variable-builtin">self</span></span><span class="ayu_dark_python -punctuation-delimiter">.</span><span class="ayu_dark_python -variable"><span class="ayu_dark_python -variable-member">order_desc</span></span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr"> 19 </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python -variable"><span class="ayu_dark_python -variable-builtin">cls</span></span> <span class="ayu_dark_python -operator">=</span> <span class="ayu_dark_python -string">f' class=&quot;<span class="ayu_dark_python -none"><span class="ayu_dark_python -punctuation-bracket"><span class="ayu_dark_python Special">&#123;</span></span><span class="ayu_dark_python -string">&quot;down&quot;</span> <span class="ayu_dark_python -keyword-conditional">if</span> <span class="ayu_dark_python -variable">desc</span> <span class="ayu_dark_python -keyword-conditional">else</span> <span class="ayu_dark_python -string">&quot;up&quot;</span><span class="ayu_dark_python -punctuation-bracket"><span class="ayu_dark_python Special">&#125;</span></span></span>&quot;'</span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr"> 20 </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python -keyword-conditional">if</span> <span class="ayu_dark_python -variable">desc</span><span class="ayu_dark_python -punctuation-delimiter">:</span>
<span class="ayu_dark_python SignColumn">  </span><span class="ayu_dark_python LineNr"> 21 </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText">│</span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python NonText"> </span><span class="ayu_dark_python -variable">link</span> <span class="ayu_dark_python -operator">+=</span> <span class="ayu_dark_python -string">&quot;&amp;amp;dir=desc&quot;</span>

</pre>
</section>