<script> import "$lib/vihtml/bamboo-vulgaris_c.css" </script>

<section class="bamboo-vulgaris_c boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr">  1 </span><span class="bamboo-vulgaris_c PreProc">#include</span> <span class="bamboo-vulgaris_c String">&lt;stdio.h&gt;</span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr">  2 </span><span class="bamboo-vulgaris_c PreProc">#include</span> <span class="bamboo-vulgaris_c String">&lt;stdlib.h&gt;</span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr">  3 </span><span class="bamboo-vulgaris_c PreProc">#include</span> <span class="bamboo-vulgaris_c String">&lt;stdbool.h&gt;</span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr">  4 </span><span class="bamboo-vulgaris_c PreProc">#include</span> <span class="bamboo-vulgaris_c String">&lt;math.h&gt;</span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr">  5 </span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr">  6 </span><span class="bamboo-vulgaris_c -keyword-directive-define">#define</span> <span class="bamboo-vulgaris_c -variable"><span class="bamboo-vulgaris_c Constant"><span class="bamboo-vulgaris_c Macro">PI</span></span></span> <span class="bamboo-vulgaris_c -variable"><span class="bamboo-vulgaris_c Constant">3.14159</span></span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr">  7 </span><span class="bamboo-vulgaris_c -keyword-directive-define">#define</span> <span class="bamboo-vulgaris_c -variable"><span class="bamboo-vulgaris_c Constant"><span class="bamboo-vulgaris_c -function-macro">SQUARE</span></span></span><span class="bamboo-vulgaris_c Delimiter">(</span><span class="bamboo-vulgaris_c -variable"><span class="bamboo-vulgaris_c -variable-parameter">x</span></span><span class="bamboo-vulgaris_c Delimiter">)</span> <span class="bamboo-vulgaris_c Delimiter">(</span><span class="bamboo-vulgaris_c Delimiter">(</span><span class="bamboo-vulgaris_c -variable">x</span><span class="bamboo-vulgaris_c Delimiter">)</span> <span class="bamboo-vulgaris_c Operator">*</span> <span class="bamboo-vulgaris_c Delimiter">(</span><span class="bamboo-vulgaris_c -variable">x</span><span class="bamboo-vulgaris_c Delimiter">)</span><span class="bamboo-vulgaris_c Delimiter">)</span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr">  8 </span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr">  9 </span><span class="bamboo-vulgaris_c Keyword">typedef</span> <span class="bamboo-vulgaris_c Keyword">struct</span> <span class="bamboo-vulgaris_c Delimiter">&#123;</span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr"> 10 </span><span class="bamboo-vulgaris_c -ibl-indent-char-1">│</span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c Type">double</span> <span class="bamboo-vulgaris_c -variable-member">x</span><span class="bamboo-vulgaris_c Delimiter">,</span> <span class="bamboo-vulgaris_c -variable-member">y</span><span class="bamboo-vulgaris_c Delimiter">;</span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr"> 11 </span><span class="bamboo-vulgaris_c -ibl-indent-char-1">│</span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c Type">double</span> <span class="bamboo-vulgaris_c -variable-member">radius</span><span class="bamboo-vulgaris_c Delimiter">;</span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr"> 12 </span><span class="bamboo-vulgaris_c Delimiter">&#125;</span> <span class="bamboo-vulgaris_c Type"><span class="bamboo-vulgaris_c Type">Circle</span></span><span class="bamboo-vulgaris_c Delimiter">;</span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr"> 13 </span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr"> 14 </span><span class="bamboo-vulgaris_c Type">double</span> <span class="bamboo-vulgaris_c -variable"><span class="bamboo-vulgaris_c Function">calculate_area</span></span><span class="bamboo-vulgaris_c Delimiter">(</span><span class="bamboo-vulgaris_c -keyword-modifier">const</span> <span class="bamboo-vulgaris_c Type">Circle</span> <span class="bamboo-vulgaris_c -variable-parameter"><span class="bamboo-vulgaris_c Operator">*</span><span class="bamboo-vulgaris_c -variable">c</span></span><span class="bamboo-vulgaris_c Delimiter">)</span> <span class="bamboo-vulgaris_c Delimiter">&#123;</span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr"> 15 </span><span class="bamboo-vulgaris_c -ibl-indent-char-1">│</span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c Keyword">return</span> <span class="bamboo-vulgaris_c -variable"><span class="bamboo-vulgaris_c Constant">PI</span></span> <span class="bamboo-vulgaris_c Operator">*</span> <span class="bamboo-vulgaris_c -variable"><span class="bamboo-vulgaris_c Constant"><span class="bamboo-vulgaris_c Function">SQUARE</span></span></span><span class="bamboo-vulgaris_c Delimiter">(</span><span class="bamboo-vulgaris_c -_parent"><span class="bamboo-vulgaris_c -variable">c</span><span class="bamboo-vulgaris_c Operator">-&gt;</span><span class="bamboo-vulgaris_c -variable-member">radius</span></span><span class="bamboo-vulgaris_c Delimiter">)</span><span class="bamboo-vulgaris_c Delimiter">;</span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr"> 16 </span><span class="bamboo-vulgaris_c Delimiter">&#125;</span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr"> 17 </span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr"> 18 </span><span class="bamboo-vulgaris_c Type">void</span> <span class="bamboo-vulgaris_c -variable"><span class="bamboo-vulgaris_c Function">print_array</span></span><span class="bamboo-vulgaris_c Delimiter">(</span><span class="bamboo-vulgaris_c -keyword-modifier">const</span> <span class="bamboo-vulgaris_c Type">char</span> <span class="bamboo-vulgaris_c -variable-parameter"><span class="bamboo-vulgaris_c Operator">*</span><span class="bamboo-vulgaris_c -variable">msg</span></span><span class="bamboo-vulgaris_c Delimiter">,</span> <span class="bamboo-vulgaris_c Type">int</span> <span class="bamboo-vulgaris_c -variable-parameter"><span class="bamboo-vulgaris_c Operator">*</span><span class="bamboo-vulgaris_c -variable">arr</span></span><span class="bamboo-vulgaris_c Delimiter">,</span> <span class="bamboo-vulgaris_c Type">size_t</span> <span class="bamboo-vulgaris_c -variable"><span class="bamboo-vulgaris_c -variable-parameter">size</span></span><span class="bamboo-vulgaris_c Delimiter">)</span> <span class="bamboo-vulgaris_c Delimiter">&#123;</span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr"> 19 </span><span class="bamboo-vulgaris_c -ibl-indent-char-1">│</span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c -variable"><span class="bamboo-vulgaris_c Function">printf</span></span><span class="bamboo-vulgaris_c Delimiter">(</span><span class="bamboo-vulgaris_c String">&quot;%s: &quot;</span><span class="bamboo-vulgaris_c Delimiter">,</span> <span class="bamboo-vulgaris_c -variable">msg</span><span class="bamboo-vulgaris_c Delimiter">)</span><span class="bamboo-vulgaris_c Delimiter">;</span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr"> 20 </span><span class="bamboo-vulgaris_c -ibl-indent-char-1">│</span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c Keyword">for</span> <span class="bamboo-vulgaris_c Delimiter">(</span><span class="bamboo-vulgaris_c Type">size_t</span> <span class="bamboo-vulgaris_c -variable">i</span> <span class="bamboo-vulgaris_c Operator">=</span> <span class="bamboo-vulgaris_c Constant">0</span><span class="bamboo-vulgaris_c Delimiter">;</span> <span class="bamboo-vulgaris_c -variable">i</span> <span class="bamboo-vulgaris_c Operator">&lt;</span> <span class="bamboo-vulgaris_c -variable">size</span><span class="bamboo-vulgaris_c Delimiter">;</span> <span class="bamboo-vulgaris_c -variable">i</span><span class="bamboo-vulgaris_c Operator">++</span><span class="bamboo-vulgaris_c Delimiter">)</span> <span class="bamboo-vulgaris_c -variable"><span class="bamboo-vulgaris_c Function">printf</span></span><span class="bamboo-vulgaris_c Delimiter">(</span><span class="bamboo-vulgaris_c String">&quot;%d &quot;</span><span class="bamboo-vulgaris_c Delimiter">,</span> <span class="bamboo-vulgaris_c -variable">arr</span><span class="bamboo-vulgaris_c Delimiter">[</span><span class="bamboo-vulgaris_c -variable">i</span><span class="bamboo-vulgaris_c Delimiter">]</span><span class="bamboo-vulgaris_c Delimiter">)</span><span class="bamboo-vulgaris_c Delimiter">;</span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr"> 21 </span><span class="bamboo-vulgaris_c -ibl-indent-char-1">│</span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c -ibl-whitespace-char-1"> </span><span class="bamboo-vulgaris_c -variable"><span class="bamboo-vulgaris_c Function">printf</span></span><span class="bamboo-vulgaris_c Delimiter">(</span><span class="bamboo-vulgaris_c String">&quot;<span class="bamboo-vulgaris_c -string-escape">\n</span>&quot;</span><span class="bamboo-vulgaris_c Delimiter">)</span><span class="bamboo-vulgaris_c Delimiter">;</span>
<span class="bamboo-vulgaris_c SignColumn">  </span><span class="bamboo-vulgaris_c LineNr"> 22 </span><span class="bamboo-vulgaris_c Delimiter">&#125;</span>

</pre>
</section>