<script> import "$lib/vicss/carbonfox.css" </script>

<section class="carbonfox boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  1 </span><span class="carbonfox Keyword">local</span> <span class="carbonfox -variable">utils</span> <span class="carbonfox Operator">=</span> <span class="carbonfox -variable"><span class="carbonfox Function"><span class="carbonfox -function-builtin">require</span></span></span> <span class="carbonfox String">&quot;vihtml.utils&quot;</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  2 </span><span class="carbonfox Keyword">local</span> <span class="carbonfox -variable"><span class="carbonfox Constant">M</span></span> <span class="carbonfox Operator">=</span> <span class="carbonfox -punctuation-bracket"><span class="carbonfox -constructor-lua">&#123;</span></span><span class="carbonfox -punctuation-bracket"><span class="carbonfox -constructor-lua">&#125;</span></span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  3 </span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  4 </span><span class="carbonfox -variable"><span class="carbonfox Constant">M</span></span><span class="carbonfox -punctuation-delimiter">.</span><span class="carbonfox -variable"><span class="carbonfox -variable-member"><span class="carbonfox Function">write_file</span></span></span> <span class="carbonfox Operator">=</span> <span class="carbonfox -keyword-function">function</span><span class="carbonfox -punctuation-bracket">(</span><span class="carbonfox -variable"><span class="carbonfox -variable-parameter">path</span></span><span class="carbonfox -punctuation-delimiter">,</span> <span class="carbonfox -variable"><span class="carbonfox -variable-parameter">str</span></span><span class="carbonfox -punctuation-bracket">)</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  5 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox Keyword">local</span> <span class="carbonfox -variable">file</span> <span class="carbonfox Operator">=</span> <span class="carbonfox -variable"><span class="carbonfox Special">io</span></span><span class="carbonfox -punctuation-delimiter">.</span><span class="carbonfox -variable"><span class="carbonfox -variable-member"><span class="carbonfox Function">open</span></span></span><span class="carbonfox -punctuation-bracket">(</span><span class="carbonfox -variable">path</span><span class="carbonfox -punctuation-delimiter">,</span> <span class="carbonfox String">&quot;wb&quot;</span><span class="carbonfox -punctuation-bracket">)</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  6 </span><span class="carbonfox -ibl-indent-char-1">│</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  7 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox Conditional">if</span> <span class="carbonfox -variable">file</span> <span class="carbonfox Conditional">then</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  8 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox -variable">file</span><span class="carbonfox -punctuation-delimiter">:</span><span class="carbonfox -variable"><span class="carbonfox Function">write</span></span><span class="carbonfox -punctuation-bracket">(</span><span class="carbonfox -variable">str</span><span class="carbonfox -punctuation-bracket">)</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  9 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox -variable">file</span><span class="carbonfox -punctuation-delimiter">:</span><span class="carbonfox -variable"><span class="carbonfox Function">close</span></span><span class="carbonfox -punctuation-bracket">(</span><span class="carbonfox -punctuation-bracket">)</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 10 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox Conditional">end</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 11 </span><span class="carbonfox -keyword-function">end</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 12 </span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 13 </span><span class="carbonfox -variable"><span class="carbonfox Constant">M</span></span><span class="carbonfox -punctuation-delimiter">.</span><span class="carbonfox -variable"><span class="carbonfox -variable-member"><span class="carbonfox Function">get_theme_list</span></span></span> <span class="carbonfox Operator">=</span> <span class="carbonfox -keyword-function">function</span><span class="carbonfox -punctuation-bracket">(</span><span class="carbonfox -punctuation-bracket">)</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 14 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox Keyword">local</span> <span class="carbonfox -variable">list</span> <span class="carbonfox Operator">=</span> <span class="carbonfox -punctuation-bracket"><span class="carbonfox -constructor-lua">&#123;</span></span><span class="carbonfox -punctuation-bracket"><span class="carbonfox -constructor-lua">&#125;</span></span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 15 </span><span class="carbonfox -ibl-indent-char-1">│</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 16 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox Conditional">for</span> <span class="carbonfox -variable">_</span><span class="carbonfox -punctuation-delimiter">,</span> <span class="carbonfox -variable">v</span> <span class="carbonfox Keyword">in</span> <span class="carbonfox -variable"><span class="carbonfox Function"><span class="carbonfox -function-builtin">ipairs</span></span></span><span class="carbonfox -punctuation-bracket">(</span><span class="carbonfox -variable"><span class="carbonfox Function"><span class="carbonfox -function-builtin">require</span></span></span> <span class="carbonfox String">&quot;themelist&quot;</span><span class="carbonfox -punctuation-bracket">)</span> <span class="carbonfox Conditional">do</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 17 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox -variable">list</span> <span class="carbonfox Operator">=</span> <span class="carbonfox -variable">vim</span><span class="carbonfox -punctuation-delimiter">.</span><span class="carbonfox -variable"><span class="carbonfox -variable-member"><span class="carbonfox Function">list_extend</span></span></span><span class="carbonfox -punctuation-bracket">(</span><span class="carbonfox -variable">list</span><span class="carbonfox -punctuation-delimiter">,</span> <span class="carbonfox -variable">v</span><span class="carbonfox -punctuation-delimiter">.</span><span class="carbonfox -variable"><span class="carbonfox -variable-member">variants</span></span><span class="carbonfox -punctuation-bracket">)</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 18 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox Conditional">end</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 19 </span><span class="carbonfox -ibl-indent-char-1">│</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 20 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox -keyword-return">return</span> <span class="carbonfox -variable">list</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 21 </span><span class="carbonfox -keyword-function">end</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 22 </span>

</pre>
</section>