<script> import "$lib/vihtml/carbonfox_rust.css" </script>

<section class="carbonfox_rust boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr">  1 </span><span class="carbonfox_rust Keyword">use</span> <span class="carbonfox_rust PreProc">std</span><span class="carbonfox_rust Special">::</span><span class="carbonfox_rust PreProc">collections</span><span class="carbonfox_rust Special">::</span>HashMap;
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr">  2 </span><span class="carbonfox_rust Keyword">use</span> <span class="carbonfox_rust PreProc">std</span><span class="carbonfox_rust Special">::</span><span class="carbonfox_rust PreProc">fs</span><span class="carbonfox_rust Special">::</span>File;
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr">  3 </span><span class="carbonfox_rust Keyword">use</span> <span class="carbonfox_rust PreProc">std</span><span class="carbonfox_rust Special">::</span><span class="carbonfox_rust PreProc">io</span><span class="carbonfox_rust Special">::</span>&#123;<span class="carbonfox_rust Constant">self</span>, Write&#125;;
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr">  4 </span>
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr">  5 </span><span class="carbonfox_rust Comment">// Enum to represent different shapes</span>
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr">  6 </span><span class="carbonfox_rust Keyword">enum</span> <span class="carbonfox_rust Identifier">Shape</span> &#123;
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr">  7 </span><span class="carbonfox_rust -ibl-indent-char-1">│</span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span>Rectangle &#123; width: <span class="carbonfox_rust Type">u32</span>, height: <span class="carbonfox_rust Type">u32</span> &#125;,
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr">  8 </span><span class="carbonfox_rust -ibl-indent-char-1">│</span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span>Triangle &#123; base: <span class="carbonfox_rust Type">u32</span>, height: <span class="carbonfox_rust Type">u32</span> &#125;,
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr">  9 </span><span class="carbonfox_rust -ibl-indent-char-1">│</span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust Function">Circle</span>(<span class="carbonfox_rust Type">f64</span>),
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr"> 10 </span>&#125;
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr"> 11 </span>
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr"> 12 </span><span class="carbonfox_rust Comment">// Function to calculate the area of a shape</span>
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr"> 13 </span><span class="carbonfox_rust Keyword">fn</span> <span class="carbonfox_rust Function">calculate_area</span>(shape: <span class="carbonfox_rust Type">&amp;</span>Shape) <span class="carbonfox_rust Operator">-&gt;</span> <span class="carbonfox_rust Type">f64</span> &#123;
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr"> 14 </span><span class="carbonfox_rust -ibl-indent-char-1">│</span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust Conditional">match</span> shape &#123;
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr"> 15 </span><span class="carbonfox_rust -ibl-indent-char-1">│</span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-indent-char-1">│</span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust PreProc">Shape</span><span class="carbonfox_rust Special">::</span>Rectangle &#123; width, height &#125; <span class="carbonfox_rust Operator">=&gt;</span> (<span class="carbonfox_rust Type">*</span>width <span class="carbonfox_rust Operator">as</span> <span class="carbonfox_rust Type">f64</span>) <span class="carbonfox_rust Operator">*</span> (<span class="carbonfox_rust Type">*</span>height <span class="carbonfox_rust Operator">as</span> <span class="carbonfox_rust Type">f64</span>),
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr"> 16 </span><span class="carbonfox_rust -ibl-indent-char-1">│</span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-indent-char-1">│</span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust PreProc">Shape</span><span class="carbonfox_rust Special">::</span>Triangle &#123; base, height &#125; <span class="carbonfox_rust Operator">=&gt;</span> <span class="carbonfox_rust Number">0.5</span> <span class="carbonfox_rust Operator">*</span> (<span class="carbonfox_rust Type">*</span>base <span class="carbonfox_rust Operator">as</span> <span class="carbonfox_rust Type">f64</span>) <span class="carbonfox_rust Operator">*</span> (<span class="carbonfox_rust Type">*</span>height <span class="carbonfox_rust Operator">as</span> <span class="carbonfox_rust Type">f64</span>),
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr"> 17 </span><span class="carbonfox_rust -ibl-indent-char-1">│</span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-indent-char-1">│</span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust PreProc">Shape</span><span class="carbonfox_rust Special">::</span><span class="carbonfox_rust Function">Circle</span>(radius) <span class="carbonfox_rust Operator">=&gt;</span> <span class="carbonfox_rust PreProc">std</span><span class="carbonfox_rust Special">::</span><span class="carbonfox_rust Type">f64</span><span class="carbonfox_rust Special">::</span><span class="carbonfox_rust PreProc">consts</span><span class="carbonfox_rust Special">::</span>PI <span class="carbonfox_rust Operator">*</span> radius.<span class="carbonfox_rust Function">powi</span>(<span class="carbonfox_rust Number">2</span>),
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr"> 18 </span><span class="carbonfox_rust -ibl-indent-char-1">│</span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span><span class="carbonfox_rust -ibl-whitespace-char-1"> </span>&#125;
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr"> 19 </span>&#125;
<span class="carbonfox_rust SignColumn">  </span><span class="carbonfox_rust LineNr"> 20 </span>

</pre>
</section>