<script> import "$lib/vicss/carbonfox.css" </script>

<section class="carbonfox boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  1 </span><span class="carbonfox -variable"><span class="carbonfox Function"><span class="carbonfox -function-builtin">require</span></span></span> <span class="carbonfox String">&quot;options&quot;</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  2 </span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  3 </span><span class="carbonfox Comment"><span class="carbonfox -spell">-- bootstrap plugins &amp; lazy.nvim</span></span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  4 </span><span class="carbonfox Keyword">local</span> <span class="carbonfox -variable">lazypath</span> <span class="carbonfox Operator">=</span> <span class="carbonfox -variable">vim</span><span class="carbonfox -punctuation-delimiter">.</span><span class="carbonfox -variable"><span class="carbonfox -variable-member">fn</span></span><span class="carbonfox -punctuation-delimiter">.</span><span class="carbonfox -variable"><span class="carbonfox -variable-member"><span class="carbonfox Function">stdpath</span></span></span> <span class="carbonfox String">&quot;data&quot;</span> <span class="carbonfox Operator">..</span> <span class="carbonfox String">&quot;/lazy/lazy.nvim&quot;</span> <span class="carbonfox Comment"><span class="carbonfox -spell">-- path where its going to be installed</span></span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  5 </span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  6 </span><span class="carbonfox Conditional">if</span> <span class="carbonfox -keyword-operator">not</span> <span class="carbonfox -variable">vim</span><span class="carbonfox -punctuation-delimiter">.</span><span class="carbonfox -variable"><span class="carbonfox -variable-member">loop</span></span><span class="carbonfox -punctuation-delimiter">.</span><span class="carbonfox -variable"><span class="carbonfox -variable-member"><span class="carbonfox Function">fs_stat</span></span></span><span class="carbonfox -punctuation-bracket">(</span><span class="carbonfox -variable">lazypath</span><span class="carbonfox -punctuation-bracket">)</span> <span class="carbonfox Conditional">then</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  7 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox -variable">vim</span><span class="carbonfox -punctuation-delimiter">.</span><span class="carbonfox -variable"><span class="carbonfox -variable-member">fn</span></span><span class="carbonfox -punctuation-delimiter">.</span><span class="carbonfox -variable"><span class="carbonfox -variable-member"><span class="carbonfox Function">system</span></span></span> <span class="carbonfox -punctuation-bracket"><span class="carbonfox -constructor-lua">&#123;</span></span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  8 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox String">&quot;git&quot;</span><span class="carbonfox -punctuation-delimiter">,</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr">  9 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox String">&quot;clone&quot;</span><span class="carbonfox -punctuation-delimiter">,</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 10 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox String">&quot;--filter=blob:none&quot;</span><span class="carbonfox -punctuation-delimiter">,</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 11 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox String">&quot;https://github.com/folke/lazy.nvim.git&quot;</span><span class="carbonfox -punctuation-delimiter">,</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 12 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox String">&quot;--branch=stable&quot;</span><span class="carbonfox -punctuation-delimiter">,</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 13 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox -variable">lazypath</span><span class="carbonfox -punctuation-delimiter">,</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 14 </span><span class="carbonfox -ibl-indent-char-1">│</span><span class="carbonfox -ibl-whitespace-char-1"> </span><span class="carbonfox -punctuation-bracket"><span class="carbonfox -constructor-lua">&#125;</span></span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 15 </span><span class="carbonfox Conditional">end</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 16 </span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 17 </span><span class="carbonfox -variable">vim</span><span class="carbonfox -punctuation-delimiter">.</span><span class="carbonfox -variable"><span class="carbonfox -variable-member">opt</span></span><span class="carbonfox -punctuation-delimiter">.</span><span class="carbonfox -variable"><span class="carbonfox -variable-member">rtp</span></span><span class="carbonfox -punctuation-delimiter">:</span><span class="carbonfox -variable"><span class="carbonfox Function">prepend</span></span><span class="carbonfox -punctuation-bracket">(</span><span class="carbonfox -variable">lazypath</span><span class="carbonfox -punctuation-bracket">)</span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 18 </span>
<span class="carbonfox SignColumn">  </span><span class="carbonfox LineNr"> 19 </span><span class="carbonfox -variable"><span class="carbonfox Function"><span class="carbonfox -function-builtin">require</span></span></span><span class="carbonfox -punctuation-bracket">(</span><span class="carbonfox String">&quot;lazy&quot;</span><span class="carbonfox -punctuation-bracket">)</span><span class="carbonfox -punctuation-delimiter">.</span><span class="carbonfox -variable"><span class="carbonfox -variable-member"><span class="carbonfox Function">setup</span></span></span><span class="carbonfox -punctuation-bracket">(</span><span class="carbonfox -variable"><span class="carbonfox Function"><span class="carbonfox -function-builtin">require</span></span></span> <span class="carbonfox String">&quot;plugins&quot;</span><span class="carbonfox -punctuation-bracket">)</span>

</pre>
</section>