<script> import "$lib/vicss/dawnfox.css" </script>

<section class="dawnfox boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  1 </span><span class="dawnfox -variable"><span class="dawnfox Function"><span class="dawnfox -function-builtin">require</span></span></span> <span class="dawnfox String">&quot;options&quot;</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  2 </span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  3 </span><span class="dawnfox Keyword">local</span> <span class="dawnfox -variable">lazypath</span> <span class="dawnfox Operator">=</span> <span class="dawnfox -variable">vim</span><span class="dawnfox -punctuation-delimiter">.</span><span class="dawnfox -variable"><span class="dawnfox -variable-member">fn</span></span><span class="dawnfox -punctuation-delimiter">.</span><span class="dawnfox -variable"><span class="dawnfox -variable-member"><span class="dawnfox Function">stdpath</span></span></span> <span class="dawnfox String">&quot;data&quot;</span> <span class="dawnfox Operator">..</span> <span class="dawnfox String">&quot;/lazy/lazy.nvim&quot;</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  4 </span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  5 </span><span class="dawnfox Conditional">if</span> <span class="dawnfox -keyword-operator">not</span> <span class="dawnfox -variable">vim</span><span class="dawnfox -punctuation-delimiter">.</span><span class="dawnfox -variable"><span class="dawnfox -variable-member">loop</span></span><span class="dawnfox -punctuation-delimiter">.</span><span class="dawnfox -variable"><span class="dawnfox -variable-member"><span class="dawnfox Function">fs_stat</span></span></span><span class="dawnfox -punctuation-bracket">(</span><span class="dawnfox -variable">lazypath</span><span class="dawnfox -punctuation-bracket">)</span> <span class="dawnfox Conditional">then</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  6 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox -variable">vim</span><span class="dawnfox -punctuation-delimiter">.</span><span class="dawnfox -variable"><span class="dawnfox -variable-member">fn</span></span><span class="dawnfox -punctuation-delimiter">.</span><span class="dawnfox -variable"><span class="dawnfox -variable-member"><span class="dawnfox Function">system</span></span></span> <span class="dawnfox -punctuation-bracket"><span class="dawnfox -constructor-lua">&#123;</span></span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  7 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox String">&quot;git&quot;</span><span class="dawnfox -punctuation-delimiter">,</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  8 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox String">&quot;clone&quot;</span><span class="dawnfox -punctuation-delimiter">,</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  9 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox String">&quot;--filter=blob:none&quot;</span><span class="dawnfox -punctuation-delimiter">,</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 10 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox String">&quot;https://github.com/folke/lazy.nvim.git&quot;</span><span class="dawnfox -punctuation-delimiter">,</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 11 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox String">&quot;--branch=stable&quot;</span><span class="dawnfox -punctuation-delimiter">,</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 12 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox -variable">lazypath</span><span class="dawnfox -punctuation-delimiter">,</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 13 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox -punctuation-bracket"><span class="dawnfox -constructor-lua">&#125;</span></span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 14 </span><span class="dawnfox Conditional">end</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 15 </span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 16 </span><span class="dawnfox -variable">vim</span><span class="dawnfox -punctuation-delimiter">.</span><span class="dawnfox -variable"><span class="dawnfox -variable-member">opt</span></span><span class="dawnfox -punctuation-delimiter">.</span><span class="dawnfox -variable"><span class="dawnfox -variable-member">rtp</span></span><span class="dawnfox -punctuation-delimiter">:</span><span class="dawnfox -variable"><span class="dawnfox Function">prepend</span></span><span class="dawnfox -punctuation-bracket">(</span><span class="dawnfox -variable">lazypath</span><span class="dawnfox -punctuation-bracket">)</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 17 </span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 18 </span><span class="dawnfox -variable"><span class="dawnfox Function"><span class="dawnfox -function-builtin">require</span></span></span><span class="dawnfox -punctuation-bracket">(</span><span class="dawnfox String">&quot;lazy&quot;</span><span class="dawnfox -punctuation-bracket">)</span><span class="dawnfox -punctuation-delimiter">.</span><span class="dawnfox -variable"><span class="dawnfox -variable-member"><span class="dawnfox Function">setup</span></span></span><span class="dawnfox -punctuation-bracket">(</span><span class="dawnfox -variable"><span class="dawnfox Function"><span class="dawnfox -function-builtin">require</span></span></span> <span class="dawnfox String">&quot;plugins&quot;</span><span class="dawnfox -punctuation-bracket">)</span>

</pre>
</section>