<script> import "$lib/vicss/dawnfox.css" </script>

<section class="dawnfox boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  1 </span><span class="dawnfox Keyword">local</span> <span class="dawnfox -variable">utils</span> <span class="dawnfox Operator">=</span> <span class="dawnfox -variable"><span class="dawnfox Function"><span class="dawnfox -function-builtin">require</span></span></span> <span class="dawnfox String">&quot;vihtml.utils&quot;</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  2 </span><span class="dawnfox Keyword">local</span> <span class="dawnfox -variable"><span class="dawnfox Constant">M</span></span> <span class="dawnfox Operator">=</span> <span class="dawnfox -punctuation-bracket"><span class="dawnfox -constructor-lua">&#123;</span></span><span class="dawnfox -punctuation-bracket"><span class="dawnfox -constructor-lua">&#125;</span></span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  3 </span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  4 </span><span class="dawnfox -variable"><span class="dawnfox Constant">M</span></span><span class="dawnfox -punctuation-delimiter">.</span><span class="dawnfox -variable"><span class="dawnfox -variable-member"><span class="dawnfox Function">write_file</span></span></span> <span class="dawnfox Operator">=</span> <span class="dawnfox -keyword-function">function</span><span class="dawnfox -punctuation-bracket">(</span><span class="dawnfox -variable"><span class="dawnfox -variable-parameter">path</span></span><span class="dawnfox -punctuation-delimiter">,</span> <span class="dawnfox -variable"><span class="dawnfox -variable-parameter">str</span></span><span class="dawnfox -punctuation-bracket">)</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  5 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox Keyword">local</span> <span class="dawnfox -variable">file</span> <span class="dawnfox Operator">=</span> <span class="dawnfox -variable"><span class="dawnfox Special">io</span></span><span class="dawnfox -punctuation-delimiter">.</span><span class="dawnfox -variable"><span class="dawnfox -variable-member"><span class="dawnfox Function">open</span></span></span><span class="dawnfox -punctuation-bracket">(</span><span class="dawnfox -variable">path</span><span class="dawnfox -punctuation-delimiter">,</span> <span class="dawnfox String">&quot;wb&quot;</span><span class="dawnfox -punctuation-bracket">)</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  6 </span><span class="dawnfox -ibl-indent-char-1">│</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  7 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox Conditional">if</span> <span class="dawnfox -variable">file</span> <span class="dawnfox Conditional">then</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  8 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox -variable">file</span><span class="dawnfox -punctuation-delimiter">:</span><span class="dawnfox -variable"><span class="dawnfox Function">write</span></span><span class="dawnfox -punctuation-bracket">(</span><span class="dawnfox -variable">str</span><span class="dawnfox -punctuation-bracket">)</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr">  9 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox -variable">file</span><span class="dawnfox -punctuation-delimiter">:</span><span class="dawnfox -variable"><span class="dawnfox Function">close</span></span><span class="dawnfox -punctuation-bracket">(</span><span class="dawnfox -punctuation-bracket">)</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 10 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox Conditional">end</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 11 </span><span class="dawnfox -keyword-function">end</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 12 </span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 13 </span><span class="dawnfox -variable"><span class="dawnfox Constant">M</span></span><span class="dawnfox -punctuation-delimiter">.</span><span class="dawnfox -variable"><span class="dawnfox -variable-member"><span class="dawnfox Function">get_theme_list</span></span></span> <span class="dawnfox Operator">=</span> <span class="dawnfox -keyword-function">function</span><span class="dawnfox -punctuation-bracket">(</span><span class="dawnfox -punctuation-bracket">)</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 14 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox Keyword">local</span> <span class="dawnfox -variable">list</span> <span class="dawnfox Operator">=</span> <span class="dawnfox -punctuation-bracket"><span class="dawnfox -constructor-lua">&#123;</span></span><span class="dawnfox -punctuation-bracket"><span class="dawnfox -constructor-lua">&#125;</span></span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 15 </span><span class="dawnfox -ibl-indent-char-1">│</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 16 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox Conditional">for</span> <span class="dawnfox -variable">_</span><span class="dawnfox -punctuation-delimiter">,</span> <span class="dawnfox -variable">v</span> <span class="dawnfox Keyword">in</span> <span class="dawnfox -variable"><span class="dawnfox Function"><span class="dawnfox -function-builtin">ipairs</span></span></span><span class="dawnfox -punctuation-bracket">(</span><span class="dawnfox -variable"><span class="dawnfox Function"><span class="dawnfox -function-builtin">require</span></span></span> <span class="dawnfox String">&quot;themelist&quot;</span><span class="dawnfox -punctuation-bracket">)</span> <span class="dawnfox Conditional">do</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 17 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox -variable">list</span> <span class="dawnfox Operator">=</span> <span class="dawnfox -variable">vim</span><span class="dawnfox -punctuation-delimiter">.</span><span class="dawnfox -variable"><span class="dawnfox -variable-member"><span class="dawnfox Function">list_extend</span></span></span><span class="dawnfox -punctuation-bracket">(</span><span class="dawnfox -variable">list</span><span class="dawnfox -punctuation-delimiter">,</span> <span class="dawnfox -variable">v</span><span class="dawnfox -punctuation-delimiter">.</span><span class="dawnfox -variable"><span class="dawnfox -variable-member">variants</span></span><span class="dawnfox -punctuation-bracket">)</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 18 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox Conditional">end</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 19 </span><span class="dawnfox -ibl-indent-char-1">│</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 20 </span><span class="dawnfox -ibl-indent-char-1">│</span><span class="dawnfox -ibl-whitespace-char-1"> </span><span class="dawnfox -keyword-return">return</span> <span class="dawnfox -variable">list</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 21 </span><span class="dawnfox -keyword-function">end</span>
<span class="dawnfox SignColumn">  </span><span class="dawnfox LineNr"> 22 </span>

</pre>
</section>