<script> import "$lib/vihtml/dawnfox_haskell.css" </script>

<section class="dawnfox_haskell boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr">  1 </span><span class="dawnfox_haskell Keyword">&#123;-# LANGUAGE DeriveFunctor, DeriveFoldable, DeriveTraversable #-&#125;</span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr">  2 </span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr">  3 </span><span class="dawnfox_haskell PreProc">import</span> <span class="dawnfox_haskell -module">Data</span><span class="dawnfox_haskell Operator">.</span><span class="dawnfox_haskell -module">Map</span> <span class="dawnfox_haskell -punctuation-bracket">(</span><span class="dawnfox_haskell Type">Map</span><span class="dawnfox_haskell -punctuation-delimiter">,</span> <span class="dawnfox_haskell -variable">fromList</span><span class="dawnfox_haskell -punctuation-delimiter">,</span> <span class="dawnfox_haskell -variable">toList</span><span class="dawnfox_haskell -punctuation-bracket">)</span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr">  4 </span><span class="dawnfox_haskell PreProc">import</span> <span class="dawnfox_haskell -module">Data</span><span class="dawnfox_haskell Operator">.</span><span class="dawnfox_haskell -module">List</span> <span class="dawnfox_haskell -punctuation-bracket">(</span><span class="dawnfox_haskell -variable">foldl'</span><span class="dawnfox_haskell -punctuation-bracket">)</span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr">  5 </span><span class="dawnfox_haskell PreProc">import</span> <span class="dawnfox_haskell -module">Text</span><span class="dawnfox_haskell Operator">.</span><span class="dawnfox_haskell -module">Printf</span> <span class="dawnfox_haskell -punctuation-bracket">(</span><span class="dawnfox_haskell -variable">printf</span><span class="dawnfox_haskell -punctuation-bracket">)</span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr">  6 </span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr">  7 </span><span class="dawnfox_haskell Comment"><span class="dawnfox_haskell -spell">-- Define a data type to hold complex data</span></span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr">  8 </span><span class="dawnfox_haskell Keyword">data</span> <span class="dawnfox_haskell Type">ComplexData</span> <span class="dawnfox_haskell Operator">=</span> <span class="dawnfox_haskell -constructor">ComplexData</span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr">  9 </span><span class="dawnfox_haskell -ibl-indent-char-1">│</span><span class="dawnfox_haskell -ibl-whitespace-char-1"> </span><span class="dawnfox_haskell -punctuation-bracket">&#123;</span> <span class="dawnfox_haskell -variable"><span class="dawnfox_haskell -variable-member">id</span></span> <span class="dawnfox_haskell Operator">::</span> <span class="dawnfox_haskell Type">Int</span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr"> 10 </span><span class="dawnfox_haskell -ibl-indent-char-1">│</span><span class="dawnfox_haskell -ibl-whitespace-char-1"> </span><span class="dawnfox_haskell -punctuation-delimiter">,</span> <span class="dawnfox_haskell -variable"><span class="dawnfox_haskell -variable-member">name</span></span> <span class="dawnfox_haskell Operator">::</span> <span class="dawnfox_haskell Type">String</span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr"> 11 </span><span class="dawnfox_haskell -ibl-indent-char-1">│</span><span class="dawnfox_haskell -ibl-whitespace-char-1"> </span><span class="dawnfox_haskell -punctuation-delimiter">,</span> <span class="dawnfox_haskell -variable"><span class="dawnfox_haskell -variable-member">values</span></span> <span class="dawnfox_haskell Operator">::</span> <span class="dawnfox_haskell -punctuation-bracket"><span class="dawnfox_haskell Type">[</span></span><span class="dawnfox_haskell Type">Int</span><span class="dawnfox_haskell -punctuation-bracket"><span class="dawnfox_haskell Type">]</span></span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr"> 12 </span><span class="dawnfox_haskell -ibl-indent-char-1">│</span><span class="dawnfox_haskell -ibl-whitespace-char-1"> </span><span class="dawnfox_haskell -punctuation-bracket">&#125;</span> <span class="dawnfox_haskell Keyword">deriving</span> <span class="dawnfox_haskell -punctuation-bracket">(</span><span class="dawnfox_haskell Type">Show</span><span class="dawnfox_haskell -punctuation-bracket">)</span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr"> 13 </span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr"> 14 </span><span class="dawnfox_haskell Comment"><span class="dawnfox_haskell -spell">-- Create a new instance of ComplexData</span></span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr"> 15 </span><span class="dawnfox_haskell -variable"><span class="dawnfox_haskell Function"><span class="dawnfox_haskell Function"><span class="dawnfox_haskell Function">newComplexData</span></span></span></span><span class="dawnfox_haskell Function"> <span class="dawnfox_haskell Operator">::</span> <span class="dawnfox_haskell Type">Int</span> <span class="dawnfox_haskell Operator">-&gt;</span> <span class="dawnfox_haskell Type">String</span> <span class="dawnfox_haskell Operator">-&gt;</span> <span class="dawnfox_haskell Type">ComplexData</span></span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr"> 16 </span><span class="dawnfox_haskell -variable"><span class="dawnfox_haskell Function"><span class="dawnfox_haskell Function">newComplexData</span></span></span> <span class="dawnfox_haskell -variable"><span class="dawnfox_haskell -variable-parameter">id</span></span> <span class="dawnfox_haskell -variable"><span class="dawnfox_haskell -variable-parameter">name</span></span> <span class="dawnfox_haskell Operator">=</span> <span class="dawnfox_haskell -constructor">ComplexData</span> <span class="dawnfox_haskell -variable"><span class="dawnfox_haskell Function"><span class="dawnfox_haskell -variable">id</span></span></span> <span class="dawnfox_haskell -variable"><span class="dawnfox_haskell Function"><span class="dawnfox_haskell -variable">name</span></span></span> <span class="dawnfox_haskell -punctuation-bracket">[</span><span class="dawnfox_haskell -variable"><span class="dawnfox_haskell Function"><span class="dawnfox_haskell -variable">id</span></span></span> <span class="dawnfox_haskell Operator">*</span> <span class="dawnfox_haskell Number">10</span><span class="dawnfox_haskell -punctuation-delimiter">,</span> <span class="dawnfox_haskell -variable"><span class="dawnfox_haskell Function"><span class="dawnfox_haskell -variable">id</span></span></span> <span class="dawnfox_haskell Operator">*</span> <span class="dawnfox_haskell Number">20</span><span class="dawnfox_haskell -punctuation-delimiter">,</span> <span class="dawnfox_haskell -variable"><span class="dawnfox_haskell Function"><span class="dawnfox_haskell -variable">id</span></span></span> <span class="dawnfox_haskell Operator">*</span> <span class="dawnfox_haskell Number">30</span><span class="dawnfox_haskell -punctuation-bracket">]</span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr"> 17 </span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr"> 18 </span><span class="dawnfox_haskell Comment"><span class="dawnfox_haskell -spell">-- Calculate the average of values in ComplexData</span></span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr"> 19 </span><span class="dawnfox_haskell -variable"><span class="dawnfox_haskell Function"><span class="dawnfox_haskell Function"><span class="dawnfox_haskell Function">calculate</span></span></span></span><span class="dawnfox_haskell Function"> <span class="dawnfox_haskell Operator">::</span> <span class="dawnfox_haskell Type">ComplexData</span> <span class="dawnfox_haskell Operator">-&gt;</span> <span class="dawnfox_haskell Type">Double</span></span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr"> 20 </span><span class="dawnfox_haskell -variable"><span class="dawnfox_haskell Function"><span class="dawnfox_haskell Function">calculate</span></span></span> <span class="dawnfox_haskell -variable-parameter"><span class="dawnfox_haskell -punctuation-bracket">(</span><span class="dawnfox_haskell -constructor">ComplexData</span> <span class="dawnfox_haskell Special">_</span> <span class="dawnfox_haskell Special">_</span> <span class="dawnfox_haskell -variable">values</span><span class="dawnfox_haskell -punctuation-bracket">)</span></span> <span class="dawnfox_haskell Operator">=</span> 
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr"> 21 </span><span class="dawnfox_haskell -ibl-indent-char-1">│</span><span class="dawnfox_haskell -ibl-whitespace-char-1"> </span><span class="dawnfox_haskell -variable"><span class="dawnfox_haskell Function">fromIntegral</span></span> <span class="dawnfox_haskell -punctuation-bracket">(</span><span class="dawnfox_haskell -variable"><span class="dawnfox_haskell Function">sum</span></span> <span class="dawnfox_haskell -variable"><span class="dawnfox_haskell Function"><span class="dawnfox_haskell -variable">values</span></span></span><span class="dawnfox_haskell -punctuation-bracket">)</span> <span class="dawnfox_haskell Operator">/</span> <span class="dawnfox_haskell -variable"><span class="dawnfox_haskell Function">fromIntegral</span></span> <span class="dawnfox_haskell -punctuation-bracket">(</span><span class="dawnfox_haskell -variable"><span class="dawnfox_haskell Function">length</span></span> <span class="dawnfox_haskell -variable"><span class="dawnfox_haskell Function"><span class="dawnfox_haskell -variable">values</span></span></span><span class="dawnfox_haskell -punctuation-bracket">)</span>
<span class="dawnfox_haskell SignColumn">  </span><span class="dawnfox_haskell LineNr"> 22 </span>

</pre>
</section>