<script> import "$lib/vihtml/dayfox_go.css" </script>

<section class="dayfox_go boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr">  1 </span>use std::&#123;collections::&#123;HashMap, HashSet&#125;, fs::File, io::&#123;self, Write&#125;, thread, time::Duration&#125;;
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr">  2 </span>
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr">  3 </span>#[derive(Debug, Clone)]
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr">  4 </span><span class="dayfox_go Keyword">struct</span> ComplexData &#123;
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr">  5 </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span>id: u32,
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr">  6 </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span>name: String,
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr">  7 </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span>values: HashSet&lt;u32&gt;,
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr">  8 </span>&#125;
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr">  9 </span>
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr"> 10 </span>impl ComplexData &#123;
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr"> 11 </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span>fn <span class="dayfox_go Identifier">new</span>(id: u32, name: &amp;str) -&gt; Self &#123;
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr"> 12 </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span>let mut values = HashSet::<span class="dayfox_go Identifier">new</span>();
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr"> 13 </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span>values.insert(id * <span class="dayfox_go Number">10</span>);
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr"> 14 </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span>values.insert(id * <span class="dayfox_go Number">20</span>);
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr"> 15 </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span>ComplexData &#123;
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr"> 16 </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span>id,
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr"> 17 </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span>name: name.to_string(),
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr"> 18 </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span>values,
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr"> 19 </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span>&#125;
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr"> 20 </span><span class="dayfox_go -ibl-indent-char-1">│</span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span><span class="dayfox_go -ibl-whitespace-char-1"> </span>&#125;
<span class="dayfox_go SignColumn">  </span><span class="dayfox_go LineNr"> 21 </span><span class="dayfox_go -ibl-indent-char-1">│</span>

</pre>
</section>