<script> import "$lib/vicss/dayfox.css" </script>

<section class="dayfox boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  1 </span><span class="dayfox Keyword">local</span> <span class="dayfox -variable">utils</span> <span class="dayfox Operator">=</span> <span class="dayfox -variable"><span class="dayfox Function"><span class="dayfox -function-builtin">require</span></span></span> <span class="dayfox String">&quot;vihtml.utils&quot;</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  2 </span><span class="dayfox Keyword">local</span> <span class="dayfox -variable"><span class="dayfox Constant">M</span></span> <span class="dayfox Operator">=</span> <span class="dayfox -punctuation-bracket"><span class="dayfox -constructor-lua">&#123;</span></span><span class="dayfox -punctuation-bracket"><span class="dayfox -constructor-lua">&#125;</span></span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  3 </span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  4 </span><span class="dayfox -variable"><span class="dayfox Constant">M</span></span><span class="dayfox -punctuation-delimiter">.</span><span class="dayfox -variable"><span class="dayfox -variable-member"><span class="dayfox Function">write_file</span></span></span> <span class="dayfox Operator">=</span> <span class="dayfox -keyword-function">function</span><span class="dayfox -punctuation-bracket">(</span><span class="dayfox -variable"><span class="dayfox -variable-parameter">path</span></span><span class="dayfox -punctuation-delimiter">,</span> <span class="dayfox -variable"><span class="dayfox -variable-parameter">str</span></span><span class="dayfox -punctuation-bracket">)</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  5 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox Keyword">local</span> <span class="dayfox -variable">file</span> <span class="dayfox Operator">=</span> <span class="dayfox -variable"><span class="dayfox Special">io</span></span><span class="dayfox -punctuation-delimiter">.</span><span class="dayfox -variable"><span class="dayfox -variable-member"><span class="dayfox Function">open</span></span></span><span class="dayfox -punctuation-bracket">(</span><span class="dayfox -variable">path</span><span class="dayfox -punctuation-delimiter">,</span> <span class="dayfox String">&quot;wb&quot;</span><span class="dayfox -punctuation-bracket">)</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  6 </span><span class="dayfox -ibl-indent-char-1">│</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  7 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox Conditional">if</span> <span class="dayfox -variable">file</span> <span class="dayfox Conditional">then</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  8 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox -variable">file</span><span class="dayfox -punctuation-delimiter">:</span><span class="dayfox -variable"><span class="dayfox Function">write</span></span><span class="dayfox -punctuation-bracket">(</span><span class="dayfox -variable">str</span><span class="dayfox -punctuation-bracket">)</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  9 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox -variable">file</span><span class="dayfox -punctuation-delimiter">:</span><span class="dayfox -variable"><span class="dayfox Function">close</span></span><span class="dayfox -punctuation-bracket">(</span><span class="dayfox -punctuation-bracket">)</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 10 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox Conditional">end</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 11 </span><span class="dayfox -keyword-function">end</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 12 </span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 13 </span><span class="dayfox -variable"><span class="dayfox Constant">M</span></span><span class="dayfox -punctuation-delimiter">.</span><span class="dayfox -variable"><span class="dayfox -variable-member"><span class="dayfox Function">get_theme_list</span></span></span> <span class="dayfox Operator">=</span> <span class="dayfox -keyword-function">function</span><span class="dayfox -punctuation-bracket">(</span><span class="dayfox -punctuation-bracket">)</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 14 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox Keyword">local</span> <span class="dayfox -variable">list</span> <span class="dayfox Operator">=</span> <span class="dayfox -punctuation-bracket"><span class="dayfox -constructor-lua">&#123;</span></span><span class="dayfox -punctuation-bracket"><span class="dayfox -constructor-lua">&#125;</span></span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 15 </span><span class="dayfox -ibl-indent-char-1">│</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 16 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox Conditional">for</span> <span class="dayfox -variable">_</span><span class="dayfox -punctuation-delimiter">,</span> <span class="dayfox -variable">v</span> <span class="dayfox Keyword">in</span> <span class="dayfox -variable"><span class="dayfox Function"><span class="dayfox -function-builtin">ipairs</span></span></span><span class="dayfox -punctuation-bracket">(</span><span class="dayfox -variable"><span class="dayfox Function"><span class="dayfox -function-builtin">require</span></span></span> <span class="dayfox String">&quot;themelist&quot;</span><span class="dayfox -punctuation-bracket">)</span> <span class="dayfox Conditional">do</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 17 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox -variable">list</span> <span class="dayfox Operator">=</span> <span class="dayfox -variable">vim</span><span class="dayfox -punctuation-delimiter">.</span><span class="dayfox -variable"><span class="dayfox -variable-member"><span class="dayfox Function">list_extend</span></span></span><span class="dayfox -punctuation-bracket">(</span><span class="dayfox -variable">list</span><span class="dayfox -punctuation-delimiter">,</span> <span class="dayfox -variable">v</span><span class="dayfox -punctuation-delimiter">.</span><span class="dayfox -variable"><span class="dayfox -variable-member">variants</span></span><span class="dayfox -punctuation-bracket">)</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 18 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox Conditional">end</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 19 </span><span class="dayfox -ibl-indent-char-1">│</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 20 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox -keyword-return">return</span> <span class="dayfox -variable">list</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 21 </span><span class="dayfox -keyword-function">end</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 22 </span>

</pre>
</section>