<script> import "$lib/vicss/dayfox.css" </script>

<section class="dayfox boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  1 </span><span class="dayfox -variable"><span class="dayfox Function"><span class="dayfox -function-builtin">require</span></span></span> <span class="dayfox String">&quot;options&quot;</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  2 </span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  3 </span><span class="dayfox Keyword">local</span> <span class="dayfox -variable">lazypath</span> <span class="dayfox Operator">=</span> <span class="dayfox -variable">vim</span><span class="dayfox -punctuation-delimiter">.</span><span class="dayfox -variable"><span class="dayfox -variable-member">fn</span></span><span class="dayfox -punctuation-delimiter">.</span><span class="dayfox -variable"><span class="dayfox -variable-member"><span class="dayfox Function">stdpath</span></span></span> <span class="dayfox String">&quot;data&quot;</span> <span class="dayfox Operator">..</span> <span class="dayfox String">&quot;/lazy/lazy.nvim&quot;</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  4 </span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  5 </span><span class="dayfox Conditional">if</span> <span class="dayfox -keyword-operator">not</span> <span class="dayfox -variable">vim</span><span class="dayfox -punctuation-delimiter">.</span><span class="dayfox -variable"><span class="dayfox -variable-member">loop</span></span><span class="dayfox -punctuation-delimiter">.</span><span class="dayfox -variable"><span class="dayfox -variable-member"><span class="dayfox Function">fs_stat</span></span></span><span class="dayfox -punctuation-bracket">(</span><span class="dayfox -variable">lazypath</span><span class="dayfox -punctuation-bracket">)</span> <span class="dayfox Conditional">then</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  6 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox -variable">vim</span><span class="dayfox -punctuation-delimiter">.</span><span class="dayfox -variable"><span class="dayfox -variable-member">fn</span></span><span class="dayfox -punctuation-delimiter">.</span><span class="dayfox -variable"><span class="dayfox -variable-member"><span class="dayfox Function">system</span></span></span> <span class="dayfox -punctuation-bracket"><span class="dayfox -constructor-lua">&#123;</span></span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  7 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox String">&quot;git&quot;</span><span class="dayfox -punctuation-delimiter">,</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  8 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox String">&quot;clone&quot;</span><span class="dayfox -punctuation-delimiter">,</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr">  9 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox String">&quot;--filter=blob:none&quot;</span><span class="dayfox -punctuation-delimiter">,</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 10 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox String">&quot;https://github.com/folke/lazy.nvim.git&quot;</span><span class="dayfox -punctuation-delimiter">,</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 11 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox String">&quot;--branch=stable&quot;</span><span class="dayfox -punctuation-delimiter">,</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 12 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox -variable">lazypath</span><span class="dayfox -punctuation-delimiter">,</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 13 </span><span class="dayfox -ibl-indent-char-1">│</span><span class="dayfox -ibl-whitespace-char-1"> </span><span class="dayfox -punctuation-bracket"><span class="dayfox -constructor-lua">&#125;</span></span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 14 </span><span class="dayfox Conditional">end</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 15 </span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 16 </span><span class="dayfox -variable">vim</span><span class="dayfox -punctuation-delimiter">.</span><span class="dayfox -variable"><span class="dayfox -variable-member">opt</span></span><span class="dayfox -punctuation-delimiter">.</span><span class="dayfox -variable"><span class="dayfox -variable-member">rtp</span></span><span class="dayfox -punctuation-delimiter">:</span><span class="dayfox -variable"><span class="dayfox Function">prepend</span></span><span class="dayfox -punctuation-bracket">(</span><span class="dayfox -variable">lazypath</span><span class="dayfox -punctuation-bracket">)</span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 17 </span>
<span class="dayfox SignColumn">  </span><span class="dayfox LineNr"> 18 </span><span class="dayfox -variable"><span class="dayfox Function"><span class="dayfox -function-builtin">require</span></span></span><span class="dayfox -punctuation-bracket">(</span><span class="dayfox String">&quot;lazy&quot;</span><span class="dayfox -punctuation-bracket">)</span><span class="dayfox -punctuation-delimiter">.</span><span class="dayfox -variable"><span class="dayfox -variable-member"><span class="dayfox Function">setup</span></span></span><span class="dayfox -punctuation-bracket">(</span><span class="dayfox -variable"><span class="dayfox Function"><span class="dayfox -function-builtin">require</span></span></span> <span class="dayfox String">&quot;plugins&quot;</span><span class="dayfox -punctuation-bracket">)</span>

</pre>
</section>