<script> import "$lib/vihtml/dayfox_c.css" </script>

<section class="dayfox_c boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr">  1 </span><span class="dayfox_c PreProc">#include</span> <span class="dayfox_c String">&lt;stdio.h&gt;</span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr">  2 </span><span class="dayfox_c PreProc">#include</span> <span class="dayfox_c String">&lt;stdlib.h&gt;</span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr">  3 </span><span class="dayfox_c PreProc">#include</span> <span class="dayfox_c String">&lt;stdbool.h&gt;</span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr">  4 </span><span class="dayfox_c PreProc">#include</span> <span class="dayfox_c String">&lt;math.h&gt;</span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr">  5 </span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr">  6 </span><span class="dayfox_c Keyword">#define</span> <span class="dayfox_c -variable"><span class="dayfox_c Constant"><span class="dayfox_c PreProc">PI</span></span></span> <span class="dayfox_c -variable"><span class="dayfox_c Number">3.14159</span></span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr">  7 </span><span class="dayfox_c Keyword">#define</span> <span class="dayfox_c -variable"><span class="dayfox_c Constant"><span class="dayfox_c -function-macro">SQUARE</span></span></span><span class="dayfox_c -punctuation-bracket">(</span><span class="dayfox_c -variable"><span class="dayfox_c -variable-parameter">x</span></span><span class="dayfox_c -punctuation-bracket">)</span> <span class="dayfox_c -punctuation-bracket">(</span><span class="dayfox_c -punctuation-bracket">(</span><span class="dayfox_c Type"><span class="dayfox_c Type">x</span></span><span class="dayfox_c -punctuation-bracket">)</span> <span class="dayfox_c Operator">*</span> <span class="dayfox_c -punctuation-bracket">(</span><span class="dayfox_c -variable">x</span><span class="dayfox_c -punctuation-bracket">)</span><span class="dayfox_c -punctuation-bracket">)</span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr">  8 </span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr">  9 </span><span class="dayfox_c Keyword">typedef</span> <span class="dayfox_c Keyword">struct</span> <span class="dayfox_c -punctuation-bracket">&#123;</span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr"> 10 </span><span class="dayfox_c -ibl-indent-char-1">│</span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -type-builtin">double</span> <span class="dayfox_c -property">x</span><span class="dayfox_c -punctuation-delimiter">,</span> <span class="dayfox_c -property">y</span><span class="dayfox_c -punctuation-delimiter">;</span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr"> 11 </span><span class="dayfox_c -ibl-indent-char-1">│</span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -type-builtin">double</span> <span class="dayfox_c -property">radius</span><span class="dayfox_c -punctuation-delimiter">;</span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr"> 12 </span><span class="dayfox_c -punctuation-bracket">&#125;</span> <span class="dayfox_c Type"><span class="dayfox_c Type">Circle</span></span><span class="dayfox_c -punctuation-delimiter">;</span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr"> 13 </span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr"> 14 </span><span class="dayfox_c -type-builtin">double</span> <span class="dayfox_c -variable"><span class="dayfox_c Function">calculate_area</span></span><span class="dayfox_c -punctuation-bracket">(</span><span class="dayfox_c Keyword">const</span> <span class="dayfox_c Type">Circle</span> <span class="dayfox_c -variable-parameter"><span class="dayfox_c Operator">*</span><span class="dayfox_c -variable">c</span></span><span class="dayfox_c -punctuation-bracket">)</span> <span class="dayfox_c -punctuation-bracket">&#123;</span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr"> 15 </span><span class="dayfox_c -ibl-indent-char-1">│</span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -keyword-return">return</span> <span class="dayfox_c -variable"><span class="dayfox_c Constant">PI</span></span> <span class="dayfox_c Operator">*</span> <span class="dayfox_c -variable"><span class="dayfox_c Constant"><span class="dayfox_c Function">SQUARE</span></span></span><span class="dayfox_c -punctuation-bracket">(</span><span class="dayfox_c -_parent"><span class="dayfox_c -variable">c</span><span class="dayfox_c Operator">-&gt;</span><span class="dayfox_c -property">radius</span></span><span class="dayfox_c -punctuation-bracket">)</span><span class="dayfox_c -punctuation-delimiter">;</span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr"> 16 </span><span class="dayfox_c -punctuation-bracket">&#125;</span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr"> 17 </span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr"> 18 </span><span class="dayfox_c -type-builtin">void</span> <span class="dayfox_c -variable"><span class="dayfox_c Function">print_array</span></span><span class="dayfox_c -punctuation-bracket">(</span><span class="dayfox_c Keyword">const</span> <span class="dayfox_c -type-builtin">char</span> <span class="dayfox_c -variable-parameter"><span class="dayfox_c Operator">*</span><span class="dayfox_c -variable">msg</span></span><span class="dayfox_c -punctuation-delimiter">,</span> <span class="dayfox_c -type-builtin">int</span> <span class="dayfox_c -variable-parameter"><span class="dayfox_c Operator">*</span><span class="dayfox_c -variable">arr</span></span><span class="dayfox_c -punctuation-delimiter">,</span> <span class="dayfox_c -type-builtin">size_t</span> <span class="dayfox_c -variable"><span class="dayfox_c -variable-parameter">size</span></span><span class="dayfox_c -punctuation-bracket">)</span> <span class="dayfox_c -punctuation-bracket">&#123;</span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr"> 19 </span><span class="dayfox_c -ibl-indent-char-1">│</span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -variable"><span class="dayfox_c Function">printf</span></span><span class="dayfox_c -punctuation-bracket">(</span><span class="dayfox_c String">&quot;%s: &quot;</span><span class="dayfox_c -punctuation-delimiter">,</span> <span class="dayfox_c -variable">msg</span><span class="dayfox_c -punctuation-bracket">)</span><span class="dayfox_c -punctuation-delimiter">;</span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr"> 20 </span><span class="dayfox_c -ibl-indent-char-1">│</span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c Conditional">for</span> <span class="dayfox_c -punctuation-bracket">(</span><span class="dayfox_c -type-builtin">size_t</span> <span class="dayfox_c -variable">i</span> <span class="dayfox_c Operator">=</span> <span class="dayfox_c Number">0</span><span class="dayfox_c -punctuation-delimiter">;</span> <span class="dayfox_c -variable">i</span> <span class="dayfox_c Operator">&lt;</span> <span class="dayfox_c -variable">size</span><span class="dayfox_c -punctuation-delimiter">;</span> <span class="dayfox_c -variable">i</span><span class="dayfox_c Operator">++</span><span class="dayfox_c -punctuation-bracket">)</span> <span class="dayfox_c -variable"><span class="dayfox_c Function">printf</span></span><span class="dayfox_c -punctuation-bracket">(</span><span class="dayfox_c String">&quot;%d &quot;</span><span class="dayfox_c -punctuation-delimiter">,</span> <span class="dayfox_c -variable">arr</span><span class="dayfox_c -punctuation-bracket">[</span><span class="dayfox_c -variable">i</span><span class="dayfox_c -punctuation-bracket">]</span><span class="dayfox_c -punctuation-bracket">)</span><span class="dayfox_c -punctuation-delimiter">;</span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr"> 21 </span><span class="dayfox_c -ibl-indent-char-1">│</span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -ibl-whitespace-char-1"> </span><span class="dayfox_c -variable"><span class="dayfox_c Function">printf</span></span><span class="dayfox_c -punctuation-bracket">(</span><span class="dayfox_c String">&quot;<span class="dayfox_c -string-escape">\n</span>&quot;</span><span class="dayfox_c -punctuation-bracket">)</span><span class="dayfox_c -punctuation-delimiter">;</span>
<span class="dayfox_c SignColumn">  </span><span class="dayfox_c LineNr"> 22 </span><span class="dayfox_c -punctuation-bracket">&#125;</span>

</pre>
</section>