<script> import "$lib/vicss/everforest.css" </script>

<div class='nvim_box'><div class='nvimbufdiv'><pre><span class="stl1teverforest">                               </span><span class="stl2teverforest">  </span><span class="stl3teverforest">  </span><span class="stl4teverforest">+page.svelte  </span><span class="stl5teverforest"> 󰅖 </span><span class="stl6teverforest">   </span><span class="stl7teverforest">  </span><span class="stl8teverforest">format.lua   </span><span class="stl9teverforest"> 󰅖 </span><span class="stl10teverforest">    </span><span class="stl11teverforest">  </span><span class="stl12teverforest">init.lua    </span><span class="stl13teverforest"> 󰅖 </span><span class="stl14teverforest">                              </span><span class="stl15teverforest">   </span><span class="stl16teverforest"></span></pre></div><div style="display:flex;" class="nvimbufdiv"><section class="everforest boxbg" style="display: flex; padding:1rem;"  border='0 r-1 solid #3a4248'>
<pre>
<span class="everforest NvimTreeFolderArrowClosed"> </span><span class="everforest NvimTreeFolderIcon"></span> <span class="everforest NvimTreeFolderName">.git</span>
<span class="everforest NvimTreeFolderArrowOpen"> </span><span class="everforest NvimTreeFolderIcon"></span> <span class="everforest NvimTreeGitDirty">✗</span> <span class="everforest NvimTreeOpenedFolderName"><span class="everforest NvimTreeGitDirty">src</span></span>
<span class="everforest NvimTreeIndentMarker">  </span><span class="everforest NvimTreeFolderArrowOpen"> </span><span class="everforest NvimTreeFolderIcon"></span> <span class="everforest NvimTreeGitDirty">✗</span> <span class="everforest NvimTreeOpenedFolderName"><span class="everforest NvimTreeGitDirty">lib</span></span>
<span class="everforest NvimTreeIndentMarker">  │ </span><span class="everforest NvimTreeFolderArrowOpen"> </span><span class="everforest NvimTreeFolderIcon"></span> <span class="everforest NvimTreeOpenedFolderName">css</span>
<span class="everforest NvimTreeIndentMarker">  │ │ └ </span><span class="everforest DevIconcss"></span> style.css
<span class="everforest NvimTreeIndentMarker">  │ </span><span class="everforest NvimTreeFolderArrowClosed"> </span><span class="everforest NvimTreeFolderIcon"></span> <span class="everforest NvimTreeGitDirty">✗</span> <span class="everforest NvimTreeFolderName"><span class="everforest NvimTreeGitDirty">vicss</span></span>
<span class="everforest NvimTreeIndentMarker">  │ </span><span class="everforest NvimTreeFolderArrowClosed"> </span><span class="everforest NvimTreeFolderIcon"></span> <span class="everforest NvimTreeGitDirty">✗</span> <span class="everforest NvimTreeFolderName"><span class="everforest NvimTreeGitDirty">vihtml</span></span>
<span class="everforest NvimTreeIndentMarker">  │ └ </span><span class="everforest DevIconts">󰛦</span> index.ts
<span class="everforest NvimTreeIndentMarker">  </span><span class="everforest NvimTreeFolderArrowOpen"> </span><span class="everforest NvimTreeFolderIcon"></span> <span class="everforest NvimTreeGitDirty">✗</span> <span class="everforest NvimTreeOpenedFolderName"><span class="everforest NvimTreeGitDirty">routes</span></span>
<span class="everforest NvimTreeIndentMarker">  │ └ </span><span class="everforest DevIconSvelte"></span> <span class="everforest NvimTreeGitDirty">✗</span> <span class="everforest NvimTreeGitDirty">+page.svelte</span>
<span class="everforest NvimTreeIndentMarker">  │ </span><span class="everforest DevIconTypeScriptDeclaration"></span> app.d.ts
<span class="everforest NvimTreeIndentMarker">  └ </span><span class="everforest DevIconhtml"></span> app.html
<span class="everforest NvimTreeFolderArrowOpen"> </span><span class="everforest NvimTreeFolderIcon"></span> <span class="everforest NvimTreeOpenedFolderName">static</span>
<span class="everforest NvimTreeIndentMarker">  └ </span><span class="everforest DevIconTrueTypeFont"></span> nerdfont.ttf
<span class="everforest NvimTreeFolderArrowOpen"> </span><span class="everforest NvimTreeFolderIcon"></span> <span class="everforest NvimTreeGitDirty">✗</span> <span class="everforest NvimTreeOpenedFolderName"><span class="everforest NvimTreeGitDirty">vihtml</span></span>
<span class="everforest NvimTreeIndentMarker">  │ </span><span class="everforest DevIconlua"></span> format.lua
<span class="everforest NvimTreeIndentMarker">  │ </span><span class="everforest DevIconlua"></span> <span class="everforest NvimTreeGitDirty">✗</span> <span class="everforest NvimTreeGitDirty">init.lua</span>
<span class="everforest NvimTreeIndentMarker">  │ </span><span class="everforest DevIconlua"></span> <span class="everforest NvimTreeGitDirty">✗</span> <span class="everforest NvimTreeGitDirty">stl_html.lua</span>
<span class="everforest NvimTreeIndentMarker">  └ </span><span class="everforest DevIconlua"></span> <span class="everforest NvimTreeGitDirty">✗</span> <span class="everforest NvimTreeGitDirty">utils.lua</span>
<span class="everforest NvimTreeIndentMarker">  </span><span class="everforest DevIconGitIgnore"></span> .gitignore
<span class="everforest NvimTreeIndentMarker">  </span><span class="everforest DevIconNPMrc"></span> .npmrc
<span class="everforest NvimTreeIndentMarker">  </span><span class="everforest DevIconBunLockfile"></span> <span class="everforest Question">bun.lockb</span>
<span class="everforest NvimTreeIndentMarker">  </span><span class="everforest DevIconLicense"></span> LICENSE
<span class="everforest NvimTreeIndentMarker">  </span><span class="everforest DevIconPackageJson"></span> package.json
<span class="everforest NvimTreeIndentMarker">  </span><span class="everforest DevIconSvelteConfig"></span> svelte.config.js
<span class="everforest NvimTreeIndentMarker">  </span><span class="everforest DevIconTSConfig"></span> tsconfig.json
<span class="everforest NvimTreeIndentMarker">  </span><span class="everforest DevIconts">󰛦</span> uno.config.ts
<span class="everforest NvimTreeIndentMarker">  </span><span class="everforest DevIconts">󰛦</span> vite.config.ts

</pre>
</section><section class="everforest boxbg" style="display: flex; padding:1rem;"  border='0 r-1 solid #3a4248'>
<pre>
<span class="everforest -keyword">local</span> <span class="everforest -variable">utils</span> <span class="everforest -operator">=</span> <span class="everforest -variable"><span class="everforest -function-call"><span class="everforest -function-builtin">require</span></span></span> <span class="everforest -string">&quot;vihtml.utils&quot;</span>
<span class="everforest -keyword">local</span> <span class="everforest -variable"><span class="everforest -constant">M</span></span> <span class="everforest -operator">=</span> <span class="everforest -punctuation-bracket"><span class="everforest -constructor">&#123;</span></span><span class="everforest -punctuation-bracket"><span class="everforest -constructor">&#125;</span></span>

<span class="everforest -variable"><span class="everforest -constant"><span class="everforest -ibl-scope-underline-1">M</span></span><span class="everforest -ibl-scope-underline-1"></span></span><span class="everforest -ibl-scope-underline-1"><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function">save_html</span></span></span> <span class="everforest -operator">=</span> <span class="everforest -keyword-function">function</span><span class="everforest -punctuation-bracket">(</span><span class="everforest -variable"><span class="everforest -variable-parameter">path</span></span><span class="everforest -punctuation-delimiter">,</span> <span class="everforest -variable"><span class="everforest -variable-parameter">str</span></span><span class="everforest -punctuation-bracket">)</span></span><span class="everforest -punctuation-bracket"></span>
<span class="everforest -ibl-scope-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -keyword">local</span> <span class="everforest -variable">file</span> <span class="everforest -operator">=</span> <span class="everforest -variable"><span class="everforest Special">io</span></span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">open</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -variable">path</span><span class="everforest -punctuation-delimiter">,</span> <span class="everforest -string">&quot;wb&quot;</span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest -ibl-scope-char-1">│</span>
<span class="everforest -ibl-scope-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -keyword-conditional">if</span> <span class="everforest -variable">file</span> <span class="everforest -keyword-conditional">then</span>
<span class="everforest -ibl-scope-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -variable">file</span><span class="everforest -punctuation-delimiter">:</span><span class="everforest -variable"><span class="everforest -function-method-call">write</span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -variable">str</span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest -ibl-scope-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -variable">file</span><span class="everforest -punctuation-delimiter">:</span><span class="everforest -variable"><span class="everforest -function-method-call">close</span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest -ibl-scope-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -keyword-conditional">end</span>
<span class="everforest -keyword-function">end</span>

<span class="everforest -variable"><span class="everforest -constant">M</span></span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function">base46_themes_html</span></span></span> <span class="everforest -operator">=</span> <span class="everforest -keyword-function">function</span><span class="everforest -punctuation-bracket">(</span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -variable"><span class="everforest -function-call"><span class="everforest -function-builtin">require</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -string">'plenary.reload'</span><span class="everforest -punctuation-bracket">)</span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">reload_module</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -string">'vihtml'</span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest NonText"> </span>
<span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -comment"><span class="everforest -spell">-- local list = require(&quot;nvchad.utils&quot;).list_themes()</span></span>
<span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -keyword">local</span> <span class="everforest -variable">cwd</span> <span class="everforest -operator">=</span> <span class="everforest -variable">vim</span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member">uv</span></span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">cwd</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -keyword">local</span> <span class="everforest -variable">html_path</span> <span class="everforest -operator">=</span> <span class="everforest -variable">cwd</span> <span class="everforest -operator">..</span> <span class="everforest -string">&quot;/src/lib/vihtml/&quot;</span>
<span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -keyword">local</span> <span class="everforest -variable">css_path</span> <span class="everforest -operator">=</span> <span class="everforest -variable">cwd</span> <span class="everforest -operator">..</span> <span class="everforest -string">&quot;/src/lib/vicss/&quot;</span>
<span class="everforest NonText"> </span>
<span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -keyword">local</span> <span class="everforest -variable">list</span> <span class="everforest -operator">=</span> <span class="everforest -punctuation-bracket"><span class="everforest -constructor">&#123;</span></span> <span class="everforest -string">&quot;onedark&quot;</span><span class="everforest -punctuation-delimiter">,</span> <span class="everforest -string">'nord'</span><span class="everforest -punctuation-delimiter">,</span> <span class="everforest -string">'everforest'</span> <span class="everforest -punctuation-bracket"><span class="everforest -constructor">&#125;</span></span>
<span class="everforest NonText"> </span>
<span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -keyword-repeat">for</span> <span class="everforest -variable">_</span><span class="everforest -punctuation-delimiter">,</span> <span class="everforest -variable">v</span> <span class="everforest -keyword">in</span> <span class="everforest -variable"><span class="everforest -function-call"><span class="everforest -function-builtin">ipairs</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -variable">list</span><span class="everforest -punctuation-bracket">)</span> <span class="everforest -keyword-repeat">do</span>
<span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -variable"><span class="everforest -function-call"><span class="everforest -function-builtin">require</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -string">&quot;nvconfig&quot;</span><span class="everforest -punctuation-bracket">)</span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member">base46</span></span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member">theme</span></span> <span class="everforest -operator">=</span> <span class="everforest -variable">v</span>
<span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -variable"><span class="everforest -function-call"><span class="everforest -function-builtin">require</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -string">&quot;base46&quot;</span><span class="everforest -punctuation-bracket">)</span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">load_all_highlights</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span>
<span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -keyword">local</span> <span class="everforest -variable">code</span> <span class="everforest -operator">=</span> <span class="everforest -variable">utils</span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">wins_to_html</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -variable">v</span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span>
<span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -variable"><span class="everforest -constant">M</span></span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">save_html</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -variable">html_path</span> <span class="everforest -operator">..</span> <span class="everforest -variable">v</span> <span class="everforest -operator">..</span> <span class="everforest -string">&quot;.svelte&quot;</span><span class="everforest -punctuation-delimiter">,</span> <span class="everforest -variable">code</span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member">html</span></span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -variable"><span class="everforest -constant">M</span></span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">save_html</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -variable">css_path</span> <span class="everforest -operator">..</span> <span class="everforest -variable">v</span> <span class="everforest -operator">..</span> <span class="everforest -string">&quot;.css&quot;</span><span class="everforest -punctuation-delimiter">,</span> <span class="everforest -variable">code</span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member">css</span></span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -keyword-repeat">end</span>
<span class="everforest -keyword-function">end</span>

<span class="everforest -variable"><span class="everforest -constant">M</span></span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">base46_themes_html</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -punctuation-bracket">)</span>

</pre>
</section></div><div class='nvimbufdiv'><pre><span class="stl1severforest">  NORMAL</span><span class="stl2severforest"></span><span class="stl3severforest"></span><span class="stl4severforest">  init.lua </span><span class="stl5severforest"></span><span class="stl6severforest">  main  1                            </span><span class="stl7severforest">                             </span><span class="stl8severforest">   LSP ~ lua_ls </span><span class="stl9severforest"></span><span class="stl10severforest">󰉋 </span><span class="stl11severforest"> base46-site </span><span class="stl12severforest"></span><span class="stl13severforest"> </span><span class="stl14severforest"></span></pre></div></div>