<script> import "$lib/vicss/everforest.css" </script>

<div class='nvim_box'><div class='stl w-[1180px]'><pre bg-blue><span class="stl1teverforest"></span><span class="stl2teverforest">  </span><span class="stl3teverforest">  </span><span class="stl4teverforest">stl_html.lua  </span><span class="stl5teverforest"> 󰅖 </span><span class="stl6teverforest">    </span><span class="stl7teverforest">  </span><span class="stl8teverforest">init.lua    </span><span class="stl9teverforest"> 󰅖 </span><span class="stl10teverforest">   </span><span class="stl11teverforest">  </span><span class="stl12teverforest">utils.lua   </span><span class="stl13teverforest"> 󰅖 </span><span class="stl14teverforest">                                              </span><span class="stl15teverforest">   </span><span class="stl16teverforest"> 󰅖 </span></pre></div><div style="display:flex;" class="nvimbufdiv"><section class="everforest boxbg p-1 flex bg-[#2b3339] text-[#d3c6aa] w-[1180px]"  border='0 r-1 solid #3a4248'>
<pre>
<span class="everforest SignColumn">  </span><span class="everforest LineNr"> 1 </span><span class="everforest -keyword">local</span> <span class="everforest -variable">utils</span> <span class="everforest -operator">=</span> <span class="everforest -variable"><span class="everforest -function-call"><span class="everforest -function-builtin">require</span></span></span> <span class="everforest -string">&quot;vihtml.utils&quot;</span>
<span class="everforest Added">┃ </span><span class="everforest LineNr"> 2 </span><span class="everforest -keyword">local</span> <span class="everforest -variable">state</span> <span class="everforest -operator">=</span> <span class="everforest -variable"><span class="everforest -function-call"><span class="everforest -function-builtin">require</span></span></span> <span class="everforest -string">&quot;vihtml.state&quot;</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr"> 3 </span><span class="everforest -keyword">local</span> <span class="everforest -variable"><span class="everforest -constant">M</span></span> <span class="everforest -operator">=</span> <span class="everforest -punctuation-bracket"><span class="everforest -constructor">&#123;</span></span><span class="everforest -punctuation-bracket"><span class="everforest -constructor">&#125;</span></span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr"> 4 </span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr"> 5 </span><span class="everforest -variable"><span class="everforest -constant">M</span></span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function">save_html</span></span></span> <span class="everforest -operator">=</span> <span class="everforest -keyword-function">function</span><span class="everforest -punctuation-bracket">(</span><span class="everforest -variable"><span class="everforest -variable-parameter">path</span></span><span class="everforest -punctuation-delimiter">,</span> <span class="everforest -variable"><span class="everforest -variable-parameter">str</span></span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr"> 6 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -keyword">local</span> <span class="everforest -variable">file</span> <span class="everforest -operator">=</span> <span class="everforest -variable"><span class="everforest Special">io</span></span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">open</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -variable">path</span><span class="everforest -punctuation-delimiter">,</span> <span class="everforest -string">&quot;wb&quot;</span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr"> 7 </span><span class="everforest NonText"> </span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr"> 8 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -keyword-conditional">if</span> <span class="everforest -variable">file</span> <span class="everforest -keyword-conditional">then</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr"> 9 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -variable">file</span><span class="everforest -punctuation-delimiter">:</span><span class="everforest -variable"><span class="everforest -function-method-call">write</span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -variable">str</span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">10 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -variable">file</span><span class="everforest -punctuation-delimiter">:</span><span class="everforest -variable"><span class="everforest -function-method-call">close</span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">11 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -keyword-conditional">end</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">12 </span><span class="everforest -keyword-function">end</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">13 </span>
<span class="everforest SignColumn">  </span><span class="everforest CursorLineNr">14 </span><span class="everforest -variable"><span class="everforest -constant">M</span></span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function">base46_themes_html</span></span></span> <span class="everforest -operator">=</span> <span class="everforest -keyword-function">function</span><span class="everforest -punctuation-bracket"><span class="everforest MatchWord">(</span></span><span class="everforest -punctuation-bracket"><span class="everforest MatchWord">)</span></span>
<span class="everforest Changed">┃ </span><span class="everforest LineNr">15 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -variable"><span class="everforest -function-call"><span class="everforest -function-builtin">require</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -string">&quot;plenary.reload&quot;</span><span class="everforest -punctuation-bracket">)</span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">reload_module</span></span></span> <span class="everforest -string">&quot;vihtml&quot;</span>
<span class="everforest Added">┃ </span><span class="everforest LineNr">16 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -variable">utils</span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">save_term_w</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">17 </span><span class="everforest NonText"> </span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">18 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -comment"><span class="everforest -spell">-- local list = require(&quot;nvchad.utils&quot;).list_themes()</span></span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">19 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -keyword">local</span> <span class="everforest -variable">cwd</span> <span class="everforest -operator">=</span> <span class="everforest -variable">vim</span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member">uv</span></span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">cwd</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">20 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -keyword">local</span> <span class="everforest -variable">html_path</span> <span class="everforest -operator">=</span> <span class="everforest -variable">cwd</span> <span class="everforest -operator">..</span> <span class="everforest -string">&quot;/src/lib/vihtml/&quot;</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">21 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -keyword">local</span> <span class="everforest -variable">css_path</span> <span class="everforest -operator">=</span> <span class="everforest -variable">cwd</span> <span class="everforest -operator">..</span> <span class="everforest -string">&quot;/src/lib/vicss/&quot;</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">22 </span><span class="everforest NonText"> </span>
<span class="everforest Changed">┃ </span><span class="everforest LineNr">23 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -keyword">local</span> <span class="everforest -variable">list</span> <span class="everforest -operator">=</span> <span class="everforest -punctuation-bracket"><span class="everforest -constructor">&#123;</span></span> <span class="everforest -string">&quot;onedark&quot;</span><span class="everforest -punctuation-delimiter">,</span> <span class="everforest -string">&quot;nord&quot;</span><span class="everforest -punctuation-delimiter">,</span> <span class="everforest -string">&quot;everforest&quot;</span> <span class="everforest -punctuation-bracket"><span class="everforest -constructor">&#125;</span></span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">24 </span><span class="everforest NonText"> </span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">25 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -keyword-repeat">for</span> <span class="everforest -variable">_</span><span class="everforest -punctuation-delimiter">,</span> <span class="everforest -variable">v</span> <span class="everforest -keyword">in</span> <span class="everforest -variable"><span class="everforest -function-call"><span class="everforest -function-builtin">ipairs</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -variable">list</span><span class="everforest -punctuation-bracket">)</span> <span class="everforest -keyword-repeat">do</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">26 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -variable"><span class="everforest -function-call"><span class="everforest -function-builtin">require</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -string">&quot;nvconfig&quot;</span><span class="everforest -punctuation-bracket">)</span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member">base46</span></span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member">theme</span></span> <span class="everforest -operator">=</span> <span class="everforest -variable">v</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">27 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -variable"><span class="everforest -function-call"><span class="everforest -function-builtin">require</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -string">&quot;base46&quot;</span><span class="everforest -punctuation-bracket">)</span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">load_all_highlights</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">28 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">29 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -keyword">local</span> <span class="everforest -variable">code</span> <span class="everforest -operator">=</span> <span class="everforest -variable">utils</span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">wins_to_html</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -variable">v</span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">30 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">31 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -variable"><span class="everforest -constant">M</span></span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">save_html</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -variable">html_path</span> <span class="everforest -operator">..</span> <span class="everforest -variable">v</span> <span class="everforest -operator">..</span> <span class="everforest -string">&quot;.svelte&quot;</span><span class="everforest -punctuation-delimiter">,</span> <span class="everforest -variable">code</span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member">html</span></span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest Added">┃ </span><span class="everforest LineNr">32 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">33 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -variable"><span class="everforest -constant">M</span></span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">save_html</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -variable">css_path</span> <span class="everforest -operator">..</span> <span class="everforest -variable">v</span> <span class="everforest -operator">..</span> <span class="everforest -string">&quot;.css&quot;</span><span class="everforest -punctuation-delimiter">,</span> <span class="everforest -variable">code</span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member">css</span></span><span class="everforest -punctuation-bracket">)</span>
<span class="everforest Added">┃ </span><span class="everforest LineNr">34 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span>
<span class="everforest Added">┃ </span><span class="everforest LineNr">35 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -ibl-indent-char-1">│</span><span class="everforest NonText"> </span><span class="everforest -variable">state</span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member">stl_w</span></span> <span class="everforest -operator">=</span> <span class="everforest -number">0</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">36 </span><span class="everforest NonText"> </span><span class="everforest NonText"> </span><span class="everforest -keyword-repeat">end</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">37 </span><span class="everforest -keyword-function">end</span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">38 </span>
<span class="everforest SignColumn">  </span><span class="everforest LineNr">39 </span><span class="everforest -variable"><span class="everforest -constant">M</span></span><span class="everforest -punctuation-delimiter">.</span><span class="everforest -variable"><span class="everforest -variable-member"><span class="everforest -function-call">base46_themes_html</span></span></span><span class="everforest -punctuation-bracket">(</span><span class="everforest -punctuation-bracket">)</span>

</pre>
</section></div><div class='stl w-[1180px]'><pre bg-blue><span class="stl1severforest">  NORMAL</span><span class="stl2severforest"></span><span class="stl3severforest"></span><span class="stl4severforest">  init.lua </span><span class="stl5severforest"></span><span class="stl6severforest">  main  5  2                  </span><span class="stl7severforest">                   </span><span class="stl8severforest">   LSP ~ lua_ls </span><span class="stl9severforest"></span><span class="stl10severforest">󰉋 </span><span class="stl11severforest"> base46-site </span><span class="stl12severforest"></span><span class="stl13severforest"> </span><span class="stl14severforest"> 35 % </span></pre></div></div>