<script> import "$lib/vihtml/fluoromachine_c.css" </script>

<section class="fluoromachine_c boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr">  1 </span><span class="fluoromachine_c Keyword">#include</span> <span class="fluoromachine_c String">&lt;stdio.h&gt;</span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr">  2 </span><span class="fluoromachine_c Keyword">#include</span> <span class="fluoromachine_c String">&lt;stdlib.h&gt;</span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr">  3 </span><span class="fluoromachine_c Keyword">#include</span> <span class="fluoromachine_c String">&lt;stdbool.h&gt;</span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr">  4 </span><span class="fluoromachine_c Keyword">#include</span> <span class="fluoromachine_c String">&lt;math.h&gt;</span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr">  5 </span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr">  6 </span><span class="fluoromachine_c Keyword">#define</span> <span class="fluoromachine_c Identifier"><span class="fluoromachine_c Constant"><span class="fluoromachine_c Constant">PI</span></span></span> <span class="fluoromachine_c Identifier"><span class="fluoromachine_c Constant">3.14159</span></span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr">  7 </span><span class="fluoromachine_c Keyword">#define</span> <span class="fluoromachine_c Identifier"><span class="fluoromachine_c Constant"><span class="fluoromachine_c Function">SQUARE</span></span></span><span class="fluoromachine_c -punctuation-bracket">(</span><span class="fluoromachine_c Identifier"><span class="fluoromachine_c -variable-parameter">x</span></span><span class="fluoromachine_c -punctuation-bracket">)</span> <span class="fluoromachine_c -punctuation-bracket">(</span><span class="fluoromachine_c -punctuation-bracket">(</span><span class="fluoromachine_c Identifier">x</span><span class="fluoromachine_c -punctuation-bracket">)</span> <span class="fluoromachine_c Keyword">*</span> <span class="fluoromachine_c -punctuation-bracket">(</span><span class="fluoromachine_c Identifier">x</span><span class="fluoromachine_c -punctuation-bracket">)</span><span class="fluoromachine_c -punctuation-bracket">)</span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr">  8 </span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr">  9 </span><span class="fluoromachine_c Keyword">typedef</span> <span class="fluoromachine_c Keyword">struct</span> <span class="fluoromachine_c -punctuation-bracket">&#123;</span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr"> 10 </span><span class="fluoromachine_c -ibl-indent-char-1">│</span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c Keyword">double</span> <span class="fluoromachine_c -property">x</span><span class="fluoromachine_c Delimiter">,</span> <span class="fluoromachine_c -property">y</span><span class="fluoromachine_c Delimiter">;</span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr"> 11 </span><span class="fluoromachine_c -ibl-indent-char-1">│</span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c Keyword">double</span> <span class="fluoromachine_c -property">radius</span><span class="fluoromachine_c Delimiter">;</span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr"> 12 </span><span class="fluoromachine_c -punctuation-bracket">&#125;</span> <span class="fluoromachine_c Type"><span class="fluoromachine_c Type">Circle</span></span><span class="fluoromachine_c Delimiter">;</span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr"> 13 </span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr"> 14 </span><span class="fluoromachine_c Keyword">double</span> <span class="fluoromachine_c Identifier"><span class="fluoromachine_c Function">calculate_area</span></span><span class="fluoromachine_c -punctuation-bracket">(</span><span class="fluoromachine_c Keyword">const</span> <span class="fluoromachine_c Type">Circle</span> <span class="fluoromachine_c -variable-parameter"><span class="fluoromachine_c Keyword">*</span><span class="fluoromachine_c Identifier">c</span></span><span class="fluoromachine_c -punctuation-bracket">)</span> <span class="fluoromachine_c -punctuation-bracket">&#123;</span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr"> 15 </span><span class="fluoromachine_c -ibl-indent-char-1">│</span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c Keyword">return</span> <span class="fluoromachine_c Identifier"><span class="fluoromachine_c Constant">PI</span></span> <span class="fluoromachine_c Keyword">*</span> <span class="fluoromachine_c Identifier"><span class="fluoromachine_c Constant"><span class="fluoromachine_c Function">SQUARE</span></span></span><span class="fluoromachine_c -punctuation-bracket">(</span><span class="fluoromachine_c -_parent"><span class="fluoromachine_c Identifier">c</span><span class="fluoromachine_c Keyword">-&gt;</span><span class="fluoromachine_c -property">radius</span></span><span class="fluoromachine_c -punctuation-bracket">)</span><span class="fluoromachine_c Delimiter">;</span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr"> 16 </span><span class="fluoromachine_c -punctuation-bracket">&#125;</span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr"> 17 </span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr"> 18 </span><span class="fluoromachine_c Keyword">void</span> <span class="fluoromachine_c Identifier"><span class="fluoromachine_c Function">print_array</span></span><span class="fluoromachine_c -punctuation-bracket">(</span><span class="fluoromachine_c Keyword">const</span> <span class="fluoromachine_c Keyword">char</span> <span class="fluoromachine_c -variable-parameter"><span class="fluoromachine_c Keyword">*</span><span class="fluoromachine_c Identifier">msg</span></span><span class="fluoromachine_c Delimiter">,</span> <span class="fluoromachine_c Keyword">int</span> <span class="fluoromachine_c -variable-parameter"><span class="fluoromachine_c Keyword">*</span><span class="fluoromachine_c Identifier">arr</span></span><span class="fluoromachine_c Delimiter">,</span> <span class="fluoromachine_c Keyword">size_t</span> <span class="fluoromachine_c Identifier"><span class="fluoromachine_c -variable-parameter">size</span></span><span class="fluoromachine_c -punctuation-bracket">)</span> <span class="fluoromachine_c -punctuation-bracket">&#123;</span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr"> 19 </span><span class="fluoromachine_c -ibl-indent-char-1">│</span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c Identifier"><span class="fluoromachine_c Function">printf</span></span><span class="fluoromachine_c -punctuation-bracket">(</span><span class="fluoromachine_c String">&quot;%s: &quot;</span><span class="fluoromachine_c Delimiter">,</span> <span class="fluoromachine_c Identifier">msg</span><span class="fluoromachine_c -punctuation-bracket">)</span><span class="fluoromachine_c Delimiter">;</span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr"> 20 </span><span class="fluoromachine_c -ibl-indent-char-1">│</span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c Keyword">for</span> <span class="fluoromachine_c -punctuation-bracket">(</span><span class="fluoromachine_c Keyword">size_t</span> <span class="fluoromachine_c Identifier">i</span> <span class="fluoromachine_c Keyword">=</span> <span class="fluoromachine_c Constant">0</span><span class="fluoromachine_c Delimiter">;</span> <span class="fluoromachine_c Identifier">i</span> <span class="fluoromachine_c Keyword">&lt;</span> <span class="fluoromachine_c Identifier">size</span><span class="fluoromachine_c Delimiter">;</span> <span class="fluoromachine_c Identifier">i</span><span class="fluoromachine_c Keyword">++</span><span class="fluoromachine_c -punctuation-bracket">)</span> <span class="fluoromachine_c Identifier"><span class="fluoromachine_c Function">printf</span></span><span class="fluoromachine_c -punctuation-bracket">(</span><span class="fluoromachine_c String">&quot;%d &quot;</span><span class="fluoromachine_c Delimiter">,</span> <span class="fluoromachine_c Identifier">arr</span><span class="fluoromachine_c -punctuation-bracket">[</span><span class="fluoromachine_c Identifier">i</span><span class="fluoromachine_c -punctuation-bracket">]</span><span class="fluoromachine_c -punctuation-bracket">)</span><span class="fluoromachine_c Delimiter">;</span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr"> 21 </span><span class="fluoromachine_c -ibl-indent-char-1">│</span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c -ibl-whitespace-char-1"> </span><span class="fluoromachine_c Identifier"><span class="fluoromachine_c Function">printf</span></span><span class="fluoromachine_c -punctuation-bracket">(</span><span class="fluoromachine_c String">&quot;<span class="fluoromachine_c Keyword">\n</span>&quot;</span><span class="fluoromachine_c -punctuation-bracket">)</span><span class="fluoromachine_c Delimiter">;</span>
<span class="fluoromachine_c SignColumn">  </span><span class="fluoromachine_c LineNr"> 22 </span><span class="fluoromachine_c -punctuation-bracket">&#125;</span>

</pre>
</section>