<script> import "$lib/vihtml/github_dark_tritanopia_c.css" </script>

<section class="github_dark_tritanopia_c boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr">  1 </span><span class="github_dark_tritanopia_c Keyword">#include</span> <span class="github_dark_tritanopia_c String">&lt;stdio.h&gt;</span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr">  2 </span><span class="github_dark_tritanopia_c Keyword">#include</span> <span class="github_dark_tritanopia_c String">&lt;stdlib.h&gt;</span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr">  3 </span><span class="github_dark_tritanopia_c Keyword">#include</span> <span class="github_dark_tritanopia_c String">&lt;stdbool.h&gt;</span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr">  4 </span><span class="github_dark_tritanopia_c Keyword">#include</span> <span class="github_dark_tritanopia_c String">&lt;math.h&gt;</span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr">  5 </span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr">  6 </span><span class="github_dark_tritanopia_c Keyword">#define</span> <span class="github_dark_tritanopia_c -variable"><span class="github_dark_tritanopia_c Constant"><span class="github_dark_tritanopia_c PreProc">PI</span></span></span> <span class="github_dark_tritanopia_c -variable"><span class="github_dark_tritanopia_c Number">3.14159</span></span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr">  7 </span><span class="github_dark_tritanopia_c Keyword">#define</span> <span class="github_dark_tritanopia_c -variable"><span class="github_dark_tritanopia_c Constant"><span class="github_dark_tritanopia_c PreProc">SQUARE</span></span></span><span class="github_dark_tritanopia_c -punctuation-bracket">(</span><span class="github_dark_tritanopia_c -variable"><span class="github_dark_tritanopia_c -variable-parameter">x</span></span><span class="github_dark_tritanopia_c -punctuation-bracket">)</span> <span class="github_dark_tritanopia_c -punctuation-bracket">(</span><span class="github_dark_tritanopia_c -punctuation-bracket">(</span><span class="github_dark_tritanopia_c -variable">x</span><span class="github_dark_tritanopia_c -punctuation-bracket">)</span> <span class="github_dark_tritanopia_c Operator">*</span> <span class="github_dark_tritanopia_c -punctuation-bracket">(</span><span class="github_dark_tritanopia_c -variable">x</span><span class="github_dark_tritanopia_c -punctuation-bracket">)</span><span class="github_dark_tritanopia_c -punctuation-bracket">)</span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr">  8 </span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr">  9 </span><span class="github_dark_tritanopia_c Keyword">typedef</span> <span class="github_dark_tritanopia_c Keyword">struct</span> <span class="github_dark_tritanopia_c -punctuation-bracket">&#123;</span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr"> 10 </span><span class="github_dark_tritanopia_c -ibl-indent-char-1">│</span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c -type-builtin">double</span> <span class="github_dark_tritanopia_c -variable-member">x</span><span class="github_dark_tritanopia_c Special">,</span> <span class="github_dark_tritanopia_c -variable-member">y</span><span class="github_dark_tritanopia_c Special">;</span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr"> 11 </span><span class="github_dark_tritanopia_c -ibl-indent-char-1">│</span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c -type-builtin">double</span> <span class="github_dark_tritanopia_c -variable-member">radius</span><span class="github_dark_tritanopia_c Special">;</span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr"> 12 </span><span class="github_dark_tritanopia_c -punctuation-bracket">&#125;</span> <span class="github_dark_tritanopia_c -type-c"><span class="github_dark_tritanopia_c Type">Circle</span></span><span class="github_dark_tritanopia_c Special">;</span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr"> 13 </span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr"> 14 </span><span class="github_dark_tritanopia_c -type-builtin">double</span> <span class="github_dark_tritanopia_c -variable"><span class="github_dark_tritanopia_c Function">calculate_area</span></span><span class="github_dark_tritanopia_c -punctuation-bracket">(</span><span class="github_dark_tritanopia_c Keyword">const</span> <span class="github_dark_tritanopia_c -type-c">Circle</span> <span class="github_dark_tritanopia_c -variable-parameter"><span class="github_dark_tritanopia_c Operator">*</span><span class="github_dark_tritanopia_c -variable">c</span></span><span class="github_dark_tritanopia_c -punctuation-bracket">)</span> <span class="github_dark_tritanopia_c -punctuation-bracket">&#123;</span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr"> 15 </span><span class="github_dark_tritanopia_c -ibl-indent-char-1">│</span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c Keyword">return</span> <span class="github_dark_tritanopia_c -variable"><span class="github_dark_tritanopia_c Constant">PI</span></span> <span class="github_dark_tritanopia_c Operator">*</span> <span class="github_dark_tritanopia_c -variable"><span class="github_dark_tritanopia_c Constant"><span class="github_dark_tritanopia_c Function">SQUARE</span></span></span><span class="github_dark_tritanopia_c -punctuation-bracket">(</span><span class="github_dark_tritanopia_c -_parent"><span class="github_dark_tritanopia_c -variable">c</span><span class="github_dark_tritanopia_c Operator">-&gt;</span><span class="github_dark_tritanopia_c -variable-member">radius</span></span><span class="github_dark_tritanopia_c -punctuation-bracket">)</span><span class="github_dark_tritanopia_c Special">;</span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr"> 16 </span><span class="github_dark_tritanopia_c -punctuation-bracket">&#125;</span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr"> 17 </span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr"> 18 </span><span class="github_dark_tritanopia_c -type-builtin">void</span> <span class="github_dark_tritanopia_c -variable"><span class="github_dark_tritanopia_c Function">print_array</span></span><span class="github_dark_tritanopia_c -punctuation-bracket">(</span><span class="github_dark_tritanopia_c Keyword">const</span> <span class="github_dark_tritanopia_c -type-builtin">char</span> <span class="github_dark_tritanopia_c -variable-parameter"><span class="github_dark_tritanopia_c Operator">*</span><span class="github_dark_tritanopia_c -variable">msg</span></span><span class="github_dark_tritanopia_c Special">,</span> <span class="github_dark_tritanopia_c -type-builtin">int</span> <span class="github_dark_tritanopia_c -variable-parameter"><span class="github_dark_tritanopia_c Operator">*</span><span class="github_dark_tritanopia_c -variable">arr</span></span><span class="github_dark_tritanopia_c Special">,</span> <span class="github_dark_tritanopia_c -type-builtin">size_t</span> <span class="github_dark_tritanopia_c -variable"><span class="github_dark_tritanopia_c -variable-parameter">size</span></span><span class="github_dark_tritanopia_c -punctuation-bracket">)</span> <span class="github_dark_tritanopia_c -punctuation-bracket">&#123;</span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr"> 19 </span><span class="github_dark_tritanopia_c -ibl-indent-char-1">│</span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c -variable"><span class="github_dark_tritanopia_c Function">printf</span></span><span class="github_dark_tritanopia_c -punctuation-bracket">(</span><span class="github_dark_tritanopia_c String">&quot;%s: &quot;</span><span class="github_dark_tritanopia_c Special">,</span> <span class="github_dark_tritanopia_c -variable">msg</span><span class="github_dark_tritanopia_c -punctuation-bracket">)</span><span class="github_dark_tritanopia_c Special">;</span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr"> 20 </span><span class="github_dark_tritanopia_c -ibl-indent-char-1">│</span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c Keyword">for</span> <span class="github_dark_tritanopia_c -punctuation-bracket">(</span><span class="github_dark_tritanopia_c -type-builtin">size_t</span> <span class="github_dark_tritanopia_c -variable">i</span> <span class="github_dark_tritanopia_c Operator">=</span> <span class="github_dark_tritanopia_c Number">0</span><span class="github_dark_tritanopia_c Special">;</span> <span class="github_dark_tritanopia_c -variable">i</span> <span class="github_dark_tritanopia_c Operator">&lt;</span> <span class="github_dark_tritanopia_c -variable">size</span><span class="github_dark_tritanopia_c Special">;</span> <span class="github_dark_tritanopia_c -variable">i</span><span class="github_dark_tritanopia_c Operator">++</span><span class="github_dark_tritanopia_c -punctuation-bracket">)</span> <span class="github_dark_tritanopia_c -variable"><span class="github_dark_tritanopia_c Function">printf</span></span><span class="github_dark_tritanopia_c -punctuation-bracket">(</span><span class="github_dark_tritanopia_c String">&quot;%d &quot;</span><span class="github_dark_tritanopia_c Special">,</span> <span class="github_dark_tritanopia_c -variable">arr</span><span class="github_dark_tritanopia_c -punctuation-bracket">[</span><span class="github_dark_tritanopia_c -variable">i</span><span class="github_dark_tritanopia_c -punctuation-bracket">]</span><span class="github_dark_tritanopia_c -punctuation-bracket">)</span><span class="github_dark_tritanopia_c Special">;</span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr"> 21 </span><span class="github_dark_tritanopia_c -ibl-indent-char-1">│</span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c -ibl-whitespace-char-1"> </span><span class="github_dark_tritanopia_c -variable"><span class="github_dark_tritanopia_c Function">printf</span></span><span class="github_dark_tritanopia_c -punctuation-bracket">(</span><span class="github_dark_tritanopia_c String">&quot;<span class="github_dark_tritanopia_c -string-escape">\n</span>&quot;</span><span class="github_dark_tritanopia_c -punctuation-bracket">)</span><span class="github_dark_tritanopia_c Special">;</span>
<span class="github_dark_tritanopia_c SignColumn">  </span><span class="github_dark_tritanopia_c LineNr"> 22 </span><span class="github_dark_tritanopia_c -punctuation-bracket">&#125;</span>

</pre>
</section>