<script> import "$lib/vihtml/material-deep-ocean_c.css" </script>

<section class="material-deep-ocean_c boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr">  1 </span><span class="material-deep-ocean_c Macro">#include</span> <span class="material-deep-ocean_c String">&lt;stdio.h&gt;</span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr">  2 </span><span class="material-deep-ocean_c Macro">#include</span> <span class="material-deep-ocean_c String">&lt;stdlib.h&gt;</span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr">  3 </span><span class="material-deep-ocean_c Macro">#include</span> <span class="material-deep-ocean_c String">&lt;stdbool.h&gt;</span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr">  4 </span><span class="material-deep-ocean_c Macro">#include</span> <span class="material-deep-ocean_c String">&lt;math.h&gt;</span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr">  5 </span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr">  6 </span><span class="material-deep-ocean_c -keyword-directive">#define</span> <span class="material-deep-ocean_c Identifier"><span class="material-deep-ocean_c -constant"><span class="material-deep-ocean_c -constant-macro">PI</span></span></span> <span class="material-deep-ocean_c Identifier"><span class="material-deep-ocean_c Number">3.14159</span></span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr">  7 </span><span class="material-deep-ocean_c -keyword-directive">#define</span> <span class="material-deep-ocean_c Identifier"><span class="material-deep-ocean_c -constant"><span class="material-deep-ocean_c Function">SQUARE</span></span></span><span class="material-deep-ocean_c -punctuation-bracket">(</span><span class="material-deep-ocean_c Identifier"><span class="material-deep-ocean_c Identifier">x</span></span><span class="material-deep-ocean_c -punctuation-bracket">)</span> <span class="material-deep-ocean_c -punctuation-bracket">(</span><span class="material-deep-ocean_c -punctuation-bracket">(</span><span class="material-deep-ocean_c Identifier">x</span><span class="material-deep-ocean_c -punctuation-bracket">)</span> <span class="material-deep-ocean_c Operator">*</span> <span class="material-deep-ocean_c -punctuation-bracket">(</span><span class="material-deep-ocean_c Identifier">x</span><span class="material-deep-ocean_c -punctuation-bracket">)</span><span class="material-deep-ocean_c -punctuation-bracket">)</span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr">  8 </span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr">  9 </span><span class="material-deep-ocean_c -keyword">typedef</span> <span class="material-deep-ocean_c -keyword">struct</span> <span class="material-deep-ocean_c -punctuation-bracket">&#123;</span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr"> 10 </span><span class="material-deep-ocean_c -ibl-indent-char-1">│</span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c -type-builtin">double</span> <span class="material-deep-ocean_c -property">x</span><span class="material-deep-ocean_c -punctuation-delimiter">,</span> <span class="material-deep-ocean_c -property">y</span><span class="material-deep-ocean_c -punctuation-delimiter">;</span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr"> 11 </span><span class="material-deep-ocean_c -ibl-indent-char-1">│</span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c -type-builtin">double</span> <span class="material-deep-ocean_c -property">radius</span><span class="material-deep-ocean_c -punctuation-delimiter">;</span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr"> 12 </span><span class="material-deep-ocean_c -punctuation-bracket">&#125;</span> <span class="material-deep-ocean_c -type"><span class="material-deep-ocean_c -type-definition">Circle</span></span><span class="material-deep-ocean_c -punctuation-delimiter">;</span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr"> 13 </span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr"> 14 </span><span class="material-deep-ocean_c -type-builtin">double</span> <span class="material-deep-ocean_c Identifier"><span class="material-deep-ocean_c Function">calculate_area</span></span><span class="material-deep-ocean_c -punctuation-bracket">(</span><span class="material-deep-ocean_c -keyword">const</span> <span class="material-deep-ocean_c -type">Circle</span> <span class="material-deep-ocean_c Identifier"><span class="material-deep-ocean_c Operator">*</span><span class="material-deep-ocean_c Identifier">c</span></span><span class="material-deep-ocean_c -punctuation-bracket">)</span> <span class="material-deep-ocean_c -punctuation-bracket">&#123;</span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr"> 15 </span><span class="material-deep-ocean_c -ibl-indent-char-1">│</span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c -keyword">return</span> <span class="material-deep-ocean_c Identifier"><span class="material-deep-ocean_c -constant">PI</span></span> <span class="material-deep-ocean_c Operator">*</span> <span class="material-deep-ocean_c Identifier"><span class="material-deep-ocean_c -constant"><span class="material-deep-ocean_c Function">SQUARE</span></span></span><span class="material-deep-ocean_c -punctuation-bracket">(</span><span class="material-deep-ocean_c -_parent"><span class="material-deep-ocean_c Identifier">c</span><span class="material-deep-ocean_c Operator">-&gt;</span><span class="material-deep-ocean_c -property">radius</span></span><span class="material-deep-ocean_c -punctuation-bracket">)</span><span class="material-deep-ocean_c -punctuation-delimiter">;</span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr"> 16 </span><span class="material-deep-ocean_c -punctuation-bracket">&#125;</span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr"> 17 </span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr"> 18 </span><span class="material-deep-ocean_c -type-builtin">void</span> <span class="material-deep-ocean_c Identifier"><span class="material-deep-ocean_c Function">print_array</span></span><span class="material-deep-ocean_c -punctuation-bracket">(</span><span class="material-deep-ocean_c -keyword">const</span> <span class="material-deep-ocean_c -type-builtin">char</span> <span class="material-deep-ocean_c Identifier"><span class="material-deep-ocean_c Operator">*</span><span class="material-deep-ocean_c Identifier">msg</span></span><span class="material-deep-ocean_c -punctuation-delimiter">,</span> <span class="material-deep-ocean_c -type-builtin">int</span> <span class="material-deep-ocean_c Identifier"><span class="material-deep-ocean_c Operator">*</span><span class="material-deep-ocean_c Identifier">arr</span></span><span class="material-deep-ocean_c -punctuation-delimiter">,</span> <span class="material-deep-ocean_c -type-builtin">size_t</span> <span class="material-deep-ocean_c Identifier"><span class="material-deep-ocean_c Identifier">size</span></span><span class="material-deep-ocean_c -punctuation-bracket">)</span> <span class="material-deep-ocean_c -punctuation-bracket">&#123;</span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr"> 19 </span><span class="material-deep-ocean_c -ibl-indent-char-1">│</span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c Identifier"><span class="material-deep-ocean_c Function">printf</span></span><span class="material-deep-ocean_c -punctuation-bracket">(</span><span class="material-deep-ocean_c String">&quot;%s: &quot;</span><span class="material-deep-ocean_c -punctuation-delimiter">,</span> <span class="material-deep-ocean_c Identifier">msg</span><span class="material-deep-ocean_c -punctuation-bracket">)</span><span class="material-deep-ocean_c -punctuation-delimiter">;</span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr"> 20 </span><span class="material-deep-ocean_c -ibl-indent-char-1">│</span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c Repeat">for</span> <span class="material-deep-ocean_c -punctuation-bracket">(</span><span class="material-deep-ocean_c -type-builtin">size_t</span> <span class="material-deep-ocean_c Identifier">i</span> <span class="material-deep-ocean_c Operator">=</span> <span class="material-deep-ocean_c Number">0</span><span class="material-deep-ocean_c -punctuation-delimiter">;</span> <span class="material-deep-ocean_c Identifier">i</span> <span class="material-deep-ocean_c Operator">&lt;</span> <span class="material-deep-ocean_c Identifier">size</span><span class="material-deep-ocean_c -punctuation-delimiter">;</span> <span class="material-deep-ocean_c Identifier">i</span><span class="material-deep-ocean_c Operator">++</span><span class="material-deep-ocean_c -punctuation-bracket">)</span> <span class="material-deep-ocean_c Identifier"><span class="material-deep-ocean_c Function">printf</span></span><span class="material-deep-ocean_c -punctuation-bracket">(</span><span class="material-deep-ocean_c String">&quot;%d &quot;</span><span class="material-deep-ocean_c -punctuation-delimiter">,</span> <span class="material-deep-ocean_c Identifier">arr</span><span class="material-deep-ocean_c -punctuation-bracket">[</span><span class="material-deep-ocean_c Identifier">i</span><span class="material-deep-ocean_c -punctuation-bracket">]</span><span class="material-deep-ocean_c -punctuation-bracket">)</span><span class="material-deep-ocean_c -punctuation-delimiter">;</span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr"> 21 </span><span class="material-deep-ocean_c -ibl-indent-char-1">│</span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c -ibl-whitespace-char-1"> </span><span class="material-deep-ocean_c Identifier"><span class="material-deep-ocean_c Function">printf</span></span><span class="material-deep-ocean_c -punctuation-bracket">(</span><span class="material-deep-ocean_c String">&quot;<span class="material-deep-ocean_c -string-escape">\n</span>&quot;</span><span class="material-deep-ocean_c -punctuation-bracket">)</span><span class="material-deep-ocean_c -punctuation-delimiter">;</span>
<span class="material-deep-ocean_c SignColumn">  </span><span class="material-deep-ocean_c LineNr"> 22 </span><span class="material-deep-ocean_c -punctuation-bracket">&#125;</span>

</pre>
</section>