<script> import "$lib/vihtml/night-owl_c.css" </script>

<section class="night-owl_c boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr">  1 </span><span class="night-owl_c Keyword">#include</span> <span class="night-owl_c String">&lt;stdio.h&gt;</span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr">  2 </span><span class="night-owl_c Keyword">#include</span> <span class="night-owl_c String">&lt;stdlib.h&gt;</span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr">  3 </span><span class="night-owl_c Keyword">#include</span> <span class="night-owl_c String">&lt;stdbool.h&gt;</span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr">  4 </span><span class="night-owl_c Keyword">#include</span> <span class="night-owl_c String">&lt;math.h&gt;</span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr">  5 </span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr">  6 </span><span class="night-owl_c Keyword">#define</span> <span class="night-owl_c -variable"><span class="night-owl_c Constant"><span class="night-owl_c Constant">PI</span></span></span> <span class="night-owl_c -variable"><span class="night-owl_c Number">3.14159</span></span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr">  7 </span><span class="night-owl_c Keyword">#define</span> <span class="night-owl_c -variable"><span class="night-owl_c Constant"><span class="night-owl_c Function">SQUARE</span></span></span><span class="night-owl_c -punctuation-bracket">(</span><span class="night-owl_c -variable"><span class="night-owl_c -variable-parameter">x</span></span><span class="night-owl_c -punctuation-bracket">)</span> <span class="night-owl_c -punctuation-bracket">(</span><span class="night-owl_c -punctuation-bracket">(</span><span class="night-owl_c -variable">x</span><span class="night-owl_c -punctuation-bracket">)</span> <span class="night-owl_c Keyword">*</span> <span class="night-owl_c -punctuation-bracket">(</span><span class="night-owl_c -variable">x</span><span class="night-owl_c -punctuation-bracket">)</span><span class="night-owl_c -punctuation-bracket">)</span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr">  8 </span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr">  9 </span><span class="night-owl_c Keyword">typedef</span> <span class="night-owl_c Keyword">struct</span> <span class="night-owl_c -punctuation-bracket">&#123;</span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr"> 10 </span><span class="night-owl_c -nowl-indentChar">│</span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c -type-builtin">double</span> <span class="night-owl_c -property">x</span><span class="night-owl_c Delimiter">,</span> <span class="night-owl_c -property">y</span><span class="night-owl_c Delimiter">;</span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr"> 11 </span><span class="night-owl_c -nowl-indentChar">│</span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c -type-builtin">double</span> <span class="night-owl_c -property">radius</span><span class="night-owl_c Delimiter">;</span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr"> 12 </span><span class="night-owl_c -punctuation-bracket">&#125;</span> <span class="night-owl_c -type"><span class="night-owl_c Type">Circle</span></span><span class="night-owl_c Delimiter">;</span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr"> 13 </span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr"> 14 </span><span class="night-owl_c -type-builtin">double</span> <span class="night-owl_c -variable"><span class="night-owl_c Function">calculate_area</span></span><span class="night-owl_c -punctuation-bracket">(</span><span class="night-owl_c Keyword">const</span> <span class="night-owl_c -type">Circle</span> <span class="night-owl_c -variable-parameter"><span class="night-owl_c Keyword">*</span><span class="night-owl_c -variable">c</span></span><span class="night-owl_c -punctuation-bracket">)</span> <span class="night-owl_c -punctuation-bracket">&#123;</span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr"> 15 </span><span class="night-owl_c -nowl-indentChar">│</span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c Statement">return</span> <span class="night-owl_c -variable"><span class="night-owl_c Constant">PI</span></span> <span class="night-owl_c Keyword">*</span> <span class="night-owl_c -variable"><span class="night-owl_c Constant"><span class="night-owl_c Function">SQUARE</span></span></span><span class="night-owl_c -punctuation-bracket">(</span><span class="night-owl_c -_parent"><span class="night-owl_c -variable">c</span><span class="night-owl_c Keyword">-&gt;</span><span class="night-owl_c -property">radius</span></span><span class="night-owl_c -punctuation-bracket">)</span><span class="night-owl_c Delimiter">;</span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr"> 16 </span><span class="night-owl_c -punctuation-bracket">&#125;</span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr"> 17 </span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr"> 18 </span><span class="night-owl_c -type-builtin">void</span> <span class="night-owl_c -variable"><span class="night-owl_c Function">print_array</span></span><span class="night-owl_c -punctuation-bracket">(</span><span class="night-owl_c Keyword">const</span> <span class="night-owl_c -type-builtin">char</span> <span class="night-owl_c -variable-parameter"><span class="night-owl_c Keyword">*</span><span class="night-owl_c -variable">msg</span></span><span class="night-owl_c Delimiter">,</span> <span class="night-owl_c -type-builtin">int</span> <span class="night-owl_c -variable-parameter"><span class="night-owl_c Keyword">*</span><span class="night-owl_c -variable">arr</span></span><span class="night-owl_c Delimiter">,</span> <span class="night-owl_c -type-builtin">size_t</span> <span class="night-owl_c -variable"><span class="night-owl_c -variable-parameter">size</span></span><span class="night-owl_c -punctuation-bracket">)</span> <span class="night-owl_c -punctuation-bracket">&#123;</span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr"> 19 </span><span class="night-owl_c -nowl-indentChar">│</span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c -variable"><span class="night-owl_c Function">printf</span></span><span class="night-owl_c -punctuation-bracket">(</span><span class="night-owl_c String">&quot;%s: &quot;</span><span class="night-owl_c Delimiter">,</span> <span class="night-owl_c -variable">msg</span><span class="night-owl_c -punctuation-bracket">)</span><span class="night-owl_c Delimiter">;</span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr"> 20 </span><span class="night-owl_c -nowl-indentChar">│</span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c Statement">for</span> <span class="night-owl_c -punctuation-bracket">(</span><span class="night-owl_c -type-builtin">size_t</span> <span class="night-owl_c -variable">i</span> <span class="night-owl_c Keyword">=</span> <span class="night-owl_c Number">0</span><span class="night-owl_c Delimiter">;</span> <span class="night-owl_c -variable">i</span> <span class="night-owl_c Keyword">&lt;</span> <span class="night-owl_c -variable">size</span><span class="night-owl_c Delimiter">;</span> <span class="night-owl_c -variable">i</span><span class="night-owl_c Keyword">++</span><span class="night-owl_c -punctuation-bracket">)</span> <span class="night-owl_c -variable"><span class="night-owl_c Function">printf</span></span><span class="night-owl_c -punctuation-bracket">(</span><span class="night-owl_c String">&quot;%d &quot;</span><span class="night-owl_c Delimiter">,</span> <span class="night-owl_c -variable">arr</span><span class="night-owl_c -punctuation-bracket">[</span><span class="night-owl_c -variable">i</span><span class="night-owl_c -punctuation-bracket">]</span><span class="night-owl_c -punctuation-bracket">)</span><span class="night-owl_c Delimiter">;</span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr"> 21 </span><span class="night-owl_c -nowl-indentChar">│</span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c Whitespace"> </span><span class="night-owl_c -variable"><span class="night-owl_c Function">printf</span></span><span class="night-owl_c -punctuation-bracket">(</span><span class="night-owl_c String">&quot;<span class="night-owl_c Keyword">\n</span>&quot;</span><span class="night-owl_c -punctuation-bracket">)</span><span class="night-owl_c Delimiter">;</span>
<span class="night-owl_c SignColumn">  </span><span class="night-owl_c LineNr"> 22 </span><span class="night-owl_c -punctuation-bracket">&#125;</span>

</pre>
</section>