<script> import "$lib/vihtml/nightfly_c.css" </script>

<section class="nightfly_c boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr">  1 </span><span class="nightfly_c NightflyWatermelon">#include</span> <span class="nightfly_c NightflyTan">&lt;stdio.h&gt;</span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr">  2 </span><span class="nightfly_c NightflyWatermelon">#include</span> <span class="nightfly_c NightflyTan">&lt;stdlib.h&gt;</span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr">  3 </span><span class="nightfly_c NightflyWatermelon">#include</span> <span class="nightfly_c NightflyTan">&lt;stdbool.h&gt;</span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr">  4 </span><span class="nightfly_c NightflyWatermelon">#include</span> <span class="nightfly_c NightflyTan">&lt;math.h&gt;</span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr">  5 </span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr">  6 </span><span class="nightfly_c NightflyWatermelon">#define</span> <span class="nightfly_c NightflyWhite"><span class="nightfly_c NightflyTurquoise"><span class="nightfly_c NightflyViolet">PI</span></span></span> <span class="nightfly_c NightflyWhite"><span class="nightfly_c NightflyOrange">3.14159</span></span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr">  7 </span><span class="nightfly_c NightflyWatermelon">#define</span> <span class="nightfly_c NightflyWhite"><span class="nightfly_c NightflyTurquoise"><span class="nightfly_c NightflyTurquoise">SQUARE</span></span></span><span class="nightfly_c NightflyWhite">(</span><span class="nightfly_c NightflyWhite"><span class="nightfly_c NightflyOrchid">x</span></span><span class="nightfly_c NightflyWhite">)</span> <span class="nightfly_c NightflyWhite">(</span><span class="nightfly_c NightflyWhite">(</span><span class="nightfly_c NightflyWhite">x</span><span class="nightfly_c NightflyWhite">)</span> <span class="nightfly_c NightflyWatermelon">*</span> <span class="nightfly_c NightflyWhite">(</span><span class="nightfly_c NightflyWhite">x</span><span class="nightfly_c NightflyWhite">)</span><span class="nightfly_c NightflyWhite">)</span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr">  8 </span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr">  9 </span><span class="nightfly_c Statement">typedef</span> <span class="nightfly_c Statement">struct</span> <span class="nightfly_c NightflyWhite">&#123;</span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr"> 10 </span><span class="nightfly_c -ibl-indent-char-1">│</span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c NightflyEmerald">double</span> <span class="nightfly_c NightflyLavender">x</span><span class="nightfly_c NightflyWhite">,</span> <span class="nightfly_c NightflyLavender">y</span><span class="nightfly_c NightflyWhite">;</span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr"> 11 </span><span class="nightfly_c -ibl-indent-char-1">│</span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c NightflyEmerald">double</span> <span class="nightfly_c NightflyLavender">radius</span><span class="nightfly_c NightflyWhite">;</span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr"> 12 </span><span class="nightfly_c NightflyWhite">&#125;</span> <span class="nightfly_c Type"><span class="nightfly_c Type">Circle</span></span><span class="nightfly_c NightflyWhite">;</span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr"> 13 </span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr"> 14 </span><span class="nightfly_c NightflyEmerald">double</span> <span class="nightfly_c NightflyWhite"><span class="nightfly_c NightflyBlue">calculate_area</span></span><span class="nightfly_c NightflyWhite">(</span><span class="nightfly_c Statement">const</span> <span class="nightfly_c Type">Circle</span> <span class="nightfly_c NightflyOrchid"><span class="nightfly_c NightflyWatermelon">*</span><span class="nightfly_c NightflyWhite">c</span></span><span class="nightfly_c NightflyWhite">)</span> <span class="nightfly_c NightflyWhite">&#123;</span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr"> 15 </span><span class="nightfly_c -ibl-indent-char-1">│</span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c Statement">return</span> <span class="nightfly_c NightflyWhite"><span class="nightfly_c NightflyTurquoise">PI</span></span> <span class="nightfly_c NightflyWatermelon">*</span> <span class="nightfly_c NightflyWhite"><span class="nightfly_c NightflyTurquoise"><span class="nightfly_c NightflyBlue">SQUARE</span></span></span><span class="nightfly_c NightflyWhite">(</span><span class="nightfly_c -_parent"><span class="nightfly_c NightflyWhite">c</span><span class="nightfly_c NightflyWatermelon">-&gt;</span><span class="nightfly_c NightflyLavender">radius</span></span><span class="nightfly_c NightflyWhite">)</span><span class="nightfly_c NightflyWhite">;</span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr"> 16 </span><span class="nightfly_c NightflyWhite">&#125;</span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr"> 17 </span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr"> 18 </span><span class="nightfly_c NightflyEmerald">void</span> <span class="nightfly_c NightflyWhite"><span class="nightfly_c NightflyBlue">print_array</span></span><span class="nightfly_c NightflyWhite">(</span><span class="nightfly_c Statement">const</span> <span class="nightfly_c NightflyEmerald">char</span> <span class="nightfly_c NightflyOrchid"><span class="nightfly_c NightflyWatermelon">*</span><span class="nightfly_c NightflyWhite">msg</span></span><span class="nightfly_c NightflyWhite">,</span> <span class="nightfly_c NightflyEmerald">int</span> <span class="nightfly_c NightflyOrchid"><span class="nightfly_c NightflyWatermelon">*</span><span class="nightfly_c NightflyWhite">arr</span></span><span class="nightfly_c NightflyWhite">,</span> <span class="nightfly_c NightflyEmerald">size_t</span> <span class="nightfly_c NightflyWhite"><span class="nightfly_c NightflyOrchid">size</span></span><span class="nightfly_c NightflyWhite">)</span> <span class="nightfly_c NightflyWhite">&#123;</span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr"> 19 </span><span class="nightfly_c -ibl-indent-char-1">│</span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c NightflyWhite"><span class="nightfly_c NightflyBlue">printf</span></span><span class="nightfly_c NightflyWhite">(</span><span class="nightfly_c NightflyTan">&quot;%s: &quot;</span><span class="nightfly_c NightflyWhite">,</span> <span class="nightfly_c NightflyWhite">msg</span><span class="nightfly_c NightflyWhite">)</span><span class="nightfly_c NightflyWhite">;</span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr"> 20 </span><span class="nightfly_c -ibl-indent-char-1">│</span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c NightflyViolet">for</span> <span class="nightfly_c NightflyWhite">(</span><span class="nightfly_c NightflyEmerald">size_t</span> <span class="nightfly_c NightflyWhite">i</span> <span class="nightfly_c NightflyWatermelon">=</span> <span class="nightfly_c NightflyOrange">0</span><span class="nightfly_c NightflyWhite">;</span> <span class="nightfly_c NightflyWhite">i</span> <span class="nightfly_c NightflyWatermelon">&lt;</span> <span class="nightfly_c NightflyWhite">size</span><span class="nightfly_c NightflyWhite">;</span> <span class="nightfly_c NightflyWhite">i</span><span class="nightfly_c NightflyWatermelon">++</span><span class="nightfly_c NightflyWhite">)</span> <span class="nightfly_c NightflyWhite"><span class="nightfly_c NightflyBlue">printf</span></span><span class="nightfly_c NightflyWhite">(</span><span class="nightfly_c NightflyTan">&quot;%d &quot;</span><span class="nightfly_c NightflyWhite">,</span> <span class="nightfly_c NightflyWhite">arr</span><span class="nightfly_c NightflyWhite">[</span><span class="nightfly_c NightflyWhite">i</span><span class="nightfly_c NightflyWhite">]</span><span class="nightfly_c NightflyWhite">)</span><span class="nightfly_c NightflyWhite">;</span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr"> 21 </span><span class="nightfly_c -ibl-indent-char-1">│</span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c -ibl-whitespace-char-1"> </span><span class="nightfly_c NightflyWhite"><span class="nightfly_c NightflyBlue">printf</span></span><span class="nightfly_c NightflyWhite">(</span><span class="nightfly_c NightflyTan">&quot;<span class="nightfly_c NightflyWatermelon">\n</span>&quot;</span><span class="nightfly_c NightflyWhite">)</span><span class="nightfly_c NightflyWhite">;</span>
<span class="nightfly_c SignColumn">  </span><span class="nightfly_c LineNr"> 22 </span><span class="nightfly_c NightflyWhite">&#125;</span>

</pre>
</section>