<script> import "$lib/vihtml/nightfly_rust.css" </script>

<section class="nightfly_rust boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr">  1 </span><span class="nightfly_rust Statement">use</span> <span class="nightfly_rust NightflyWatermelon">std</span><span class="nightfly_rust NightflyWhite">::</span><span class="nightfly_rust NightflyWatermelon">collections</span><span class="nightfly_rust NightflyWhite">::</span>HashMap;
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr">  2 </span><span class="nightfly_rust Statement">use</span> <span class="nightfly_rust NightflyWatermelon">std</span><span class="nightfly_rust NightflyWhite">::</span><span class="nightfly_rust NightflyWatermelon">fs</span><span class="nightfly_rust NightflyWhite">::</span>File;
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr">  3 </span><span class="nightfly_rust Statement">use</span> <span class="nightfly_rust NightflyWatermelon">std</span><span class="nightfly_rust NightflyWhite">::</span><span class="nightfly_rust NightflyWatermelon">io</span><span class="nightfly_rust NightflyWhite">::</span>&#123;<span class="nightfly_rust NightflyOrange">self</span>, Write&#125;;
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr">  4 </span>
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr">  5 </span><span class="nightfly_rust Comment">// Enum to represent different shapes</span>
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr">  6 </span><span class="nightfly_rust Statement">enum</span> <span class="nightfly_rust NightflyTurquoise">Shape</span> &#123;
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr">  7 </span><span class="nightfly_rust -ibl-indent-char-1">│</span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span>Rectangle &#123; width: <span class="nightfly_rust Type">u32</span>, height: <span class="nightfly_rust Type">u32</span> &#125;,
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr">  8 </span><span class="nightfly_rust -ibl-indent-char-1">│</span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span>Triangle &#123; base: <span class="nightfly_rust Type">u32</span>, height: <span class="nightfly_rust Type">u32</span> &#125;,
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr">  9 </span><span class="nightfly_rust -ibl-indent-char-1">│</span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust NightflyBlue">Circle</span>(<span class="nightfly_rust Type">f64</span>),
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr"> 10 </span>&#125;
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr"> 11 </span>
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr"> 12 </span><span class="nightfly_rust Comment">// Function to calculate the area of a shape</span>
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr"> 13 </span><span class="nightfly_rust Statement">fn</span> <span class="nightfly_rust NightflyBlue">calculate_area</span>(shape: <span class="nightfly_rust NightflyViolet">&amp;</span>Shape) <span class="nightfly_rust NightflyWatermelon">-&gt;</span> <span class="nightfly_rust Type">f64</span> &#123;
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr"> 14 </span><span class="nightfly_rust -ibl-indent-char-1">│</span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust Statement">match</span> shape &#123;
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr"> 15 </span><span class="nightfly_rust -ibl-indent-char-1">│</span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-indent-char-1">│</span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust NightflyWatermelon">Shape</span><span class="nightfly_rust NightflyWhite">::</span>Rectangle &#123; width, height &#125; <span class="nightfly_rust NightflyWatermelon">=&gt;</span> (<span class="nightfly_rust NightflyViolet">*</span>width <span class="nightfly_rust NightflyWatermelon">as</span> <span class="nightfly_rust Type">f64</span>) <span class="nightfly_rust NightflyWatermelon">*</span> (<span class="nightfly_rust NightflyViolet">*</span>height <span class="nightfly_rust NightflyWatermelon">as</span> <span class="nightfly_rust Type">f64</span>),
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr"> 16 </span><span class="nightfly_rust -ibl-indent-char-1">│</span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-indent-char-1">│</span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust NightflyWatermelon">Shape</span><span class="nightfly_rust NightflyWhite">::</span>Triangle &#123; base, height &#125; <span class="nightfly_rust NightflyWatermelon">=&gt;</span> <span class="nightfly_rust NightflyOrange">0.5</span> <span class="nightfly_rust NightflyWatermelon">*</span> (<span class="nightfly_rust NightflyViolet">*</span>base <span class="nightfly_rust NightflyWatermelon">as</span> <span class="nightfly_rust Type">f64</span>) <span class="nightfly_rust NightflyWatermelon">*</span> (<span class="nightfly_rust NightflyViolet">*</span>height <span class="nightfly_rust NightflyWatermelon">as</span> <span class="nightfly_rust Type">f64</span>),
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr"> 17 </span><span class="nightfly_rust -ibl-indent-char-1">│</span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-indent-char-1">│</span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust NightflyWatermelon">Shape</span><span class="nightfly_rust NightflyWhite">::</span><span class="nightfly_rust NightflyBlue">Circle</span>(radius) <span class="nightfly_rust NightflyWatermelon">=&gt;</span> <span class="nightfly_rust NightflyWatermelon">std</span><span class="nightfly_rust NightflyWhite">::</span><span class="nightfly_rust Type">f64</span><span class="nightfly_rust NightflyWhite">::</span><span class="nightfly_rust NightflyWatermelon">consts</span><span class="nightfly_rust NightflyWhite">::</span>PI <span class="nightfly_rust NightflyWatermelon">*</span> radius.<span class="nightfly_rust NightflyBlue">powi</span>(<span class="nightfly_rust NightflyOrange">2</span>),
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr"> 18 </span><span class="nightfly_rust -ibl-indent-char-1">│</span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span><span class="nightfly_rust -ibl-whitespace-char-1"> </span>&#125;
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr"> 19 </span>&#125;
<span class="nightfly_rust SignColumn">  </span><span class="nightfly_rust LineNr"> 20 </span>

</pre>
</section>