<script> import "$lib/vihtml/night-owl_go.css" </script>

<section class="night-owl_go boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr">  1 </span><span class="night-owl_go -label">use</span> <span class="night-owl_go -variable">std</span><span class="night-owl_go Delimiter">:</span><span class="night-owl_go Delimiter">:</span><span class="night-owl_go -punctuation-bracket">&#123;</span><span class="night-owl_go -label">collections</span><span class="night-owl_go Delimiter">:</span><span class="night-owl_go Delimiter">:</span><span class="night-owl_go -punctuation-bracket">&#123;</span><span class="night-owl_go -variable">HashMap</span><span class="night-owl_go Delimiter">,</span> <span class="night-owl_go -variable">HashSet</span><span class="night-owl_go -punctuation-bracket">&#125;</span><span class="night-owl_go Delimiter">,</span> <span class="night-owl_go -variable">fs</span><span class="night-owl_go Delimiter">:</span><span class="night-owl_go Delimiter">:</span><span class="night-owl_go -variable">File</span><span class="night-owl_go Delimiter">,</span> <span class="night-owl_go -variable">io</span><span class="night-owl_go Delimiter">:</span><span class="night-owl_go Delimiter">:</span><span class="night-owl_go -punctuation-bracket">&#123;</span><span class="night-owl_go -variable">self</span><span class="night-owl_go Delimiter">,</span> <span class="night-owl_go -variable">Write</span><span class="night-owl_go -punctuation-bracket">&#125;</span><span class="night-owl_go Delimiter">,</span> <span class="night-owl_go -variable">thread</span><span class="night-owl_go Delimiter">,</span> <span class="night-owl_go -variable">time</span><span class="night-owl_go Delimiter">:</span><span class="night-owl_go Delimiter">:</span><span class="night-owl_go -variable">Duration</span><span class="night-owl_go -punctuation-bracket">&#125;</span><span class="night-owl_go Delimiter">;</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr">  2 </span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr">  3 </span>#<span class="night-owl_go -punctuation-bracket">[</span><span class="night-owl_go -variable"><span class="night-owl_go Function">derive</span></span><span class="night-owl_go -punctuation-bracket">(</span><span class="night-owl_go -variable">Debug</span><span class="night-owl_go Delimiter">,</span> <span class="night-owl_go -variable">Clone</span><span class="night-owl_go -punctuation-bracket">)</span><span class="night-owl_go -punctuation-bracket">]</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr">  4 </span><span class="night-owl_go Keyword">struct</span> <span class="night-owl_go -type">ComplexData</span> <span class="night-owl_go -punctuation-bracket">&#123;</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr">  5 </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -variable"><span class="night-owl_go -variable-member">id</span></span><span class="night-owl_go Delimiter">:</span> <span class="night-owl_go -variable">u32</span><span class="night-owl_go Delimiter">,</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr">  6 </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -variable"><span class="night-owl_go -variable-member">name</span></span><span class="night-owl_go Delimiter">:</span> <span class="night-owl_go -variable">String</span><span class="night-owl_go Delimiter">,</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr">  7 </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -variable"><span class="night-owl_go -variable-member">values</span></span><span class="night-owl_go Delimiter">:</span> <span class="night-owl_go -variable">HashSet</span><span class="night-owl_go Keyword">&lt;</span><span class="night-owl_go -variable">u32</span><span class="night-owl_go Keyword">&gt;</span><span class="night-owl_go Delimiter">,</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr">  8 </span><span class="night-owl_go -punctuation-bracket">&#125;</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr">  9 </span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr"> 10 </span><span class="night-owl_go -variable">impl</span> <span class="night-owl_go -type">ComplexData</span> <span class="night-owl_go -punctuation-bracket">&#123;</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr"> 11 </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -variable">fn</span> <span class="night-owl_go -variable"><span class="night-owl_go Function"><span class="night-owl_go Function">new</span></span></span><span class="night-owl_go -punctuation-bracket">(</span><span class="night-owl_go -type">id</span><span class="night-owl_go Delimiter">:</span> <span class="night-owl_go -variable">u32</span><span class="night-owl_go Delimiter">,</span> <span class="night-owl_go -variable"><span class="night-owl_go -variable-member">name</span></span><span class="night-owl_go Delimiter">:</span> <span class="night-owl_go Keyword">&amp;</span><span class="night-owl_go -variable">str</span><span class="night-owl_go -punctuation-bracket">)</span> <span class="night-owl_go Keyword">-</span><span class="night-owl_go Keyword">&gt;</span> <span class="night-owl_go -type">Self</span> <span class="night-owl_go -punctuation-bracket">&#123;</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr"> 12 </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -variable">let</span> <span class="night-owl_go -variable">mut</span> <span class="night-owl_go -variable">values</span> <span class="night-owl_go Keyword">=</span> <span class="night-owl_go -variable"><span class="night-owl_go -variable-member">HashSet</span></span><span class="night-owl_go Delimiter">:</span><span class="night-owl_go Delimiter">:</span><span class="night-owl_go -variable"><span class="night-owl_go Function"><span class="night-owl_go Function">new</span></span></span><span class="night-owl_go -punctuation-bracket">(</span><span class="night-owl_go -punctuation-bracket">)</span><span class="night-owl_go Delimiter">;</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr"> 13 </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -variable">values</span><span class="night-owl_go Delimiter">.</span><span class="night-owl_go -property"><span class="night-owl_go Function">insert</span></span><span class="night-owl_go -punctuation-bracket">(</span><span class="night-owl_go -variable">id</span> <span class="night-owl_go Keyword">*</span> <span class="night-owl_go Number">10</span><span class="night-owl_go -punctuation-bracket">)</span><span class="night-owl_go Delimiter">;</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr"> 14 </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -variable">values</span><span class="night-owl_go Delimiter">.</span><span class="night-owl_go -property"><span class="night-owl_go Function">insert</span></span><span class="night-owl_go -punctuation-bracket">(</span><span class="night-owl_go -variable">id</span> <span class="night-owl_go Keyword">*</span> <span class="night-owl_go Number">20</span><span class="night-owl_go -punctuation-bracket">)</span><span class="night-owl_go Delimiter">;</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr"> 15 </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -type">ComplexData</span> <span class="night-owl_go -punctuation-bracket">&#123;</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr"> 16 </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -variable">id</span><span class="night-owl_go Delimiter">,</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr"> 17 </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -variable"><span class="night-owl_go -variable-member">name</span></span><span class="night-owl_go Delimiter">:</span> <span class="night-owl_go -variable">name</span><span class="night-owl_go Delimiter">.</span><span class="night-owl_go -property"><span class="night-owl_go Function">to_string</span></span><span class="night-owl_go -punctuation-bracket">(</span><span class="night-owl_go -punctuation-bracket">)</span><span class="night-owl_go Delimiter">,</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr"> 18 </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -variable">values</span><span class="night-owl_go Delimiter">,</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr"> 19 </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -punctuation-bracket">&#125;</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr"> 20 </span><span class="night-owl_go -nowl-indentChar">│</span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go Whitespace"> </span><span class="night-owl_go -punctuation-bracket">&#125;</span>
<span class="night-owl_go SignColumn">  </span><span class="night-owl_go LineNr"> 21 </span><span class="night-owl_go -nowl-indentChar">│</span>

</pre>
</section>