<script> import "$lib/vihtml/nordic_haskell.css" </script>

<section class="nordic_haskell boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr">  1 </span><span class="nordic_haskell Macro">&#123;-# LANGUAGE DeriveFunctor, DeriveFoldable, DeriveTraversable #-&#125;</span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr">  2 </span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr">  3 </span><span class="nordic_haskell Macro">import</span> <span class="nordic_haskell -module">Data</span><span class="nordic_haskell -operator">.</span><span class="nordic_haskell -module">Map</span> <span class="nordic_haskell -operator">(</span><span class="nordic_haskell Type">Map</span><span class="nordic_haskell Delimiter">,</span> <span class="nordic_haskell Variable">fromList</span><span class="nordic_haskell Delimiter">,</span> <span class="nordic_haskell Variable">toList</span><span class="nordic_haskell -operator">)</span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr">  4 </span><span class="nordic_haskell Macro">import</span> <span class="nordic_haskell -module">Data</span><span class="nordic_haskell -operator">.</span><span class="nordic_haskell -module">List</span> <span class="nordic_haskell -operator">(</span><span class="nordic_haskell Variable">foldl'</span><span class="nordic_haskell -operator">)</span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr">  5 </span><span class="nordic_haskell Macro">import</span> <span class="nordic_haskell -module">Text</span><span class="nordic_haskell -operator">.</span><span class="nordic_haskell -module">Printf</span> <span class="nordic_haskell -operator">(</span><span class="nordic_haskell Variable">printf</span><span class="nordic_haskell -operator">)</span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr">  6 </span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr">  7 </span><span class="nordic_haskell Comment"><span class="nordic_haskell -spell">-- Define a data type to hold complex data</span></span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr">  8 </span><span class="nordic_haskell Keyword">data</span> <span class="nordic_haskell Type">ComplexData</span> <span class="nordic_haskell -operator">=</span> <span class="nordic_haskell Function">ComplexData</span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr">  9 </span><span class="nordic_haskell -ibl-indent-char-1">│</span><span class="nordic_haskell -ibl-whitespace-char-1"> </span><span class="nordic_haskell -operator">&#123;</span> <span class="nordic_haskell Variable"><span class="nordic_haskell Field">id</span></span> <span class="nordic_haskell -operator">::</span> <span class="nordic_haskell Type">Int</span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr"> 10 </span><span class="nordic_haskell -ibl-indent-char-1">│</span><span class="nordic_haskell -ibl-whitespace-char-1"> </span><span class="nordic_haskell Delimiter">,</span> <span class="nordic_haskell Variable"><span class="nordic_haskell Field">name</span></span> <span class="nordic_haskell -operator">::</span> <span class="nordic_haskell Type">String</span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr"> 11 </span><span class="nordic_haskell -ibl-indent-char-1">│</span><span class="nordic_haskell -ibl-whitespace-char-1"> </span><span class="nordic_haskell Delimiter">,</span> <span class="nordic_haskell Variable"><span class="nordic_haskell Field">values</span></span> <span class="nordic_haskell -operator">::</span> <span class="nordic_haskell -operator"><span class="nordic_haskell Type">[</span></span><span class="nordic_haskell Type">Int</span><span class="nordic_haskell -operator"><span class="nordic_haskell Type">]</span></span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr"> 12 </span><span class="nordic_haskell -ibl-indent-char-1">│</span><span class="nordic_haskell -ibl-whitespace-char-1"> </span><span class="nordic_haskell -operator">&#125;</span> <span class="nordic_haskell Keyword">deriving</span> <span class="nordic_haskell -operator">(</span><span class="nordic_haskell Type">Show</span><span class="nordic_haskell -operator">)</span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr"> 13 </span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr"> 14 </span><span class="nordic_haskell Comment"><span class="nordic_haskell -spell">-- Create a new instance of ComplexData</span></span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr"> 15 </span><span class="nordic_haskell Variable"><span class="nordic_haskell Function"><span class="nordic_haskell Function"><span class="nordic_haskell Function">newComplexData</span></span></span></span><span class="nordic_haskell Function"> <span class="nordic_haskell -operator">::</span> <span class="nordic_haskell Type">Int</span> <span class="nordic_haskell -operator">-&gt;</span> <span class="nordic_haskell Type">String</span> <span class="nordic_haskell -operator">-&gt;</span> <span class="nordic_haskell Type">ComplexData</span></span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr"> 16 </span><span class="nordic_haskell Variable"><span class="nordic_haskell Function"><span class="nordic_haskell Function">newComplexData</span></span></span> <span class="nordic_haskell Variable"><span class="nordic_haskell Variable">id</span></span> <span class="nordic_haskell Variable"><span class="nordic_haskell Variable">name</span></span> <span class="nordic_haskell -operator">=</span> <span class="nordic_haskell Function">ComplexData</span> <span class="nordic_haskell Variable"><span class="nordic_haskell Function"><span class="nordic_haskell Variable">id</span></span></span> <span class="nordic_haskell Variable"><span class="nordic_haskell Function"><span class="nordic_haskell Variable">name</span></span></span> <span class="nordic_haskell -operator">[</span><span class="nordic_haskell Variable"><span class="nordic_haskell Function"><span class="nordic_haskell Variable">id</span></span></span> <span class="nordic_haskell -operator">*</span> <span class="nordic_haskell Constant">10</span><span class="nordic_haskell Delimiter">,</span> <span class="nordic_haskell Variable"><span class="nordic_haskell Function"><span class="nordic_haskell Variable">id</span></span></span> <span class="nordic_haskell -operator">*</span> <span class="nordic_haskell Constant">20</span><span class="nordic_haskell Delimiter">,</span> <span class="nordic_haskell Variable"><span class="nordic_haskell Function"><span class="nordic_haskell Variable">id</span></span></span> <span class="nordic_haskell -operator">*</span> <span class="nordic_haskell Constant">30</span><span class="nordic_haskell -operator">]</span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr"> 17 </span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr"> 18 </span><span class="nordic_haskell Comment"><span class="nordic_haskell -spell">-- Calculate the average of values in ComplexData</span></span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr"> 19 </span><span class="nordic_haskell Variable"><span class="nordic_haskell Function"><span class="nordic_haskell Function"><span class="nordic_haskell Function">calculate</span></span></span></span><span class="nordic_haskell Function"> <span class="nordic_haskell -operator">::</span> <span class="nordic_haskell Type">ComplexData</span> <span class="nordic_haskell -operator">-&gt;</span> <span class="nordic_haskell Type">Double</span></span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr"> 20 </span><span class="nordic_haskell Variable"><span class="nordic_haskell Function"><span class="nordic_haskell Function">calculate</span></span></span> <span class="nordic_haskell Variable"><span class="nordic_haskell -operator">(</span><span class="nordic_haskell Function">ComplexData</span> <span class="nordic_haskell Special">_</span> <span class="nordic_haskell Special">_</span> <span class="nordic_haskell Variable">values</span><span class="nordic_haskell -operator">)</span></span> <span class="nordic_haskell -operator">=</span> 
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr"> 21 </span><span class="nordic_haskell -ibl-indent-char-1">│</span><span class="nordic_haskell -ibl-whitespace-char-1"> </span><span class="nordic_haskell Variable"><span class="nordic_haskell Function">fromIntegral</span></span> <span class="nordic_haskell -operator">(</span><span class="nordic_haskell Variable"><span class="nordic_haskell Function">sum</span></span> <span class="nordic_haskell Variable"><span class="nordic_haskell Function"><span class="nordic_haskell Variable">values</span></span></span><span class="nordic_haskell -operator">)</span> <span class="nordic_haskell -operator">/</span> <span class="nordic_haskell Variable"><span class="nordic_haskell Function">fromIntegral</span></span> <span class="nordic_haskell -operator">(</span><span class="nordic_haskell Variable"><span class="nordic_haskell Function">length</span></span> <span class="nordic_haskell Variable"><span class="nordic_haskell Function"><span class="nordic_haskell Variable">values</span></span></span><span class="nordic_haskell -operator">)</span>
<span class="nordic_haskell SignColumn">  </span><span class="nordic_haskell LineNr"> 22 </span>

</pre>
</section>