<script> import "$lib/vicss/nordfox.css" </script>

<section class="nordfox boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr">  1 </span><span class="nordfox Keyword">local</span> <span class="nordfox -variable">utils</span> <span class="nordfox Operator">=</span> <span class="nordfox -variable"><span class="nordfox Function"><span class="nordfox -function-builtin">require</span></span></span> <span class="nordfox String">&quot;vihtml.utils&quot;</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr">  2 </span><span class="nordfox Keyword">local</span> <span class="nordfox -variable"><span class="nordfox Constant">M</span></span> <span class="nordfox Operator">=</span> <span class="nordfox -punctuation-bracket"><span class="nordfox -constructor-lua">&#123;</span></span><span class="nordfox -punctuation-bracket"><span class="nordfox -constructor-lua">&#125;</span></span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr">  3 </span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr">  4 </span><span class="nordfox -variable"><span class="nordfox Constant">M</span></span><span class="nordfox -punctuation-delimiter">.</span><span class="nordfox -variable"><span class="nordfox -variable-member"><span class="nordfox Function">write_file</span></span></span> <span class="nordfox Operator">=</span> <span class="nordfox -keyword-function">function</span><span class="nordfox -punctuation-bracket">(</span><span class="nordfox -variable"><span class="nordfox -variable-parameter">path</span></span><span class="nordfox -punctuation-delimiter">,</span> <span class="nordfox -variable"><span class="nordfox -variable-parameter">str</span></span><span class="nordfox -punctuation-bracket">)</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr">  5 </span><span class="nordfox -ibl-indent-char-1">│</span><span class="nordfox -ibl-whitespace-char-1"> </span><span class="nordfox Keyword">local</span> <span class="nordfox -variable">file</span> <span class="nordfox Operator">=</span> <span class="nordfox -variable"><span class="nordfox Special">io</span></span><span class="nordfox -punctuation-delimiter">.</span><span class="nordfox -variable"><span class="nordfox -variable-member"><span class="nordfox Function">open</span></span></span><span class="nordfox -punctuation-bracket">(</span><span class="nordfox -variable">path</span><span class="nordfox -punctuation-delimiter">,</span> <span class="nordfox String">&quot;wb&quot;</span><span class="nordfox -punctuation-bracket">)</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr">  6 </span><span class="nordfox -ibl-indent-char-1">│</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr">  7 </span><span class="nordfox -ibl-indent-char-1">│</span><span class="nordfox -ibl-whitespace-char-1"> </span><span class="nordfox Conditional">if</span> <span class="nordfox -variable">file</span> <span class="nordfox Conditional">then</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr">  8 </span><span class="nordfox -ibl-indent-char-1">│</span><span class="nordfox -ibl-whitespace-char-1"> </span><span class="nordfox -ibl-indent-char-1">│</span><span class="nordfox -ibl-whitespace-char-1"> </span><span class="nordfox -variable">file</span><span class="nordfox -punctuation-delimiter">:</span><span class="nordfox -variable"><span class="nordfox Function">write</span></span><span class="nordfox -punctuation-bracket">(</span><span class="nordfox -variable">str</span><span class="nordfox -punctuation-bracket">)</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr">  9 </span><span class="nordfox -ibl-indent-char-1">│</span><span class="nordfox -ibl-whitespace-char-1"> </span><span class="nordfox -ibl-indent-char-1">│</span><span class="nordfox -ibl-whitespace-char-1"> </span><span class="nordfox -variable">file</span><span class="nordfox -punctuation-delimiter">:</span><span class="nordfox -variable"><span class="nordfox Function">close</span></span><span class="nordfox -punctuation-bracket">(</span><span class="nordfox -punctuation-bracket">)</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr"> 10 </span><span class="nordfox -ibl-indent-char-1">│</span><span class="nordfox -ibl-whitespace-char-1"> </span><span class="nordfox Conditional">end</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr"> 11 </span><span class="nordfox -keyword-function">end</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr"> 12 </span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr"> 13 </span><span class="nordfox -variable"><span class="nordfox Constant">M</span></span><span class="nordfox -punctuation-delimiter">.</span><span class="nordfox -variable"><span class="nordfox -variable-member"><span class="nordfox Function">get_theme_list</span></span></span> <span class="nordfox Operator">=</span> <span class="nordfox -keyword-function">function</span><span class="nordfox -punctuation-bracket">(</span><span class="nordfox -punctuation-bracket">)</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr"> 14 </span><span class="nordfox -ibl-indent-char-1">│</span><span class="nordfox -ibl-whitespace-char-1"> </span><span class="nordfox Keyword">local</span> <span class="nordfox -variable">list</span> <span class="nordfox Operator">=</span> <span class="nordfox -punctuation-bracket"><span class="nordfox -constructor-lua">&#123;</span></span><span class="nordfox -punctuation-bracket"><span class="nordfox -constructor-lua">&#125;</span></span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr"> 15 </span><span class="nordfox -ibl-indent-char-1">│</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr"> 16 </span><span class="nordfox -ibl-indent-char-1">│</span><span class="nordfox -ibl-whitespace-char-1"> </span><span class="nordfox Conditional">for</span> <span class="nordfox -variable">_</span><span class="nordfox -punctuation-delimiter">,</span> <span class="nordfox -variable">v</span> <span class="nordfox Keyword">in</span> <span class="nordfox -variable"><span class="nordfox Function"><span class="nordfox -function-builtin">ipairs</span></span></span><span class="nordfox -punctuation-bracket">(</span><span class="nordfox -variable"><span class="nordfox Function"><span class="nordfox -function-builtin">require</span></span></span> <span class="nordfox String">&quot;themelist&quot;</span><span class="nordfox -punctuation-bracket">)</span> <span class="nordfox Conditional">do</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr"> 17 </span><span class="nordfox -ibl-indent-char-1">│</span><span class="nordfox -ibl-whitespace-char-1"> </span><span class="nordfox -ibl-indent-char-1">│</span><span class="nordfox -ibl-whitespace-char-1"> </span><span class="nordfox -variable">list</span> <span class="nordfox Operator">=</span> <span class="nordfox -variable">vim</span><span class="nordfox -punctuation-delimiter">.</span><span class="nordfox -variable"><span class="nordfox -variable-member"><span class="nordfox Function">list_extend</span></span></span><span class="nordfox -punctuation-bracket">(</span><span class="nordfox -variable">list</span><span class="nordfox -punctuation-delimiter">,</span> <span class="nordfox -variable">v</span><span class="nordfox -punctuation-delimiter">.</span><span class="nordfox -variable"><span class="nordfox -variable-member">variants</span></span><span class="nordfox -punctuation-bracket">)</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr"> 18 </span><span class="nordfox -ibl-indent-char-1">│</span><span class="nordfox -ibl-whitespace-char-1"> </span><span class="nordfox Conditional">end</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr"> 19 </span><span class="nordfox -ibl-indent-char-1">│</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr"> 20 </span><span class="nordfox -ibl-indent-char-1">│</span><span class="nordfox -ibl-whitespace-char-1"> </span><span class="nordfox -keyword-return">return</span> <span class="nordfox -variable">list</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr"> 21 </span><span class="nordfox -keyword-function">end</span>
<span class="nordfox SignColumn">  </span><span class="nordfox LineNr"> 22 </span>

</pre>
</section>