<script> import "$lib/vihtml/nordic_go.css" </script>

<section class="nordic_go boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr">  1 </span><span class="nordic_go Keyword">use</span> <span class="nordic_go Variable">std</span><span class="nordic_go Delimiter">:</span><span class="nordic_go Delimiter">:</span><span class="nordic_go -operator">&#123;</span><span class="nordic_go Keyword">collections</span><span class="nordic_go Delimiter">:</span><span class="nordic_go Delimiter">:</span><span class="nordic_go -operator">&#123;</span><span class="nordic_go Variable">HashMap</span><span class="nordic_go Delimiter">,</span> <span class="nordic_go Variable">HashSet</span><span class="nordic_go -operator">&#125;</span><span class="nordic_go Delimiter">,</span> <span class="nordic_go Variable">fs</span><span class="nordic_go Delimiter">:</span><span class="nordic_go Delimiter">:</span><span class="nordic_go Variable">File</span><span class="nordic_go Delimiter">,</span> <span class="nordic_go Variable">io</span><span class="nordic_go Delimiter">:</span><span class="nordic_go Delimiter">:</span><span class="nordic_go -operator">&#123;</span><span class="nordic_go Variable">self</span><span class="nordic_go Delimiter">,</span> <span class="nordic_go Variable">Write</span><span class="nordic_go -operator">&#125;</span><span class="nordic_go Delimiter">,</span> <span class="nordic_go Variable">thread</span><span class="nordic_go Delimiter">,</span> <span class="nordic_go Variable">time</span><span class="nordic_go Delimiter">:</span><span class="nordic_go Delimiter">:</span><span class="nordic_go Variable">Duration</span><span class="nordic_go -operator">&#125;</span><span class="nordic_go Delimiter">;</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr">  2 </span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr">  3 </span>#<span class="nordic_go -operator">[</span><span class="nordic_go Variable"><span class="nordic_go Function">derive</span></span><span class="nordic_go -operator">(</span><span class="nordic_go Variable">Debug</span><span class="nordic_go Delimiter">,</span> <span class="nordic_go Variable">Clone</span><span class="nordic_go -operator">)</span><span class="nordic_go -operator">]</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr">  4 </span><span class="nordic_go Keyword">struct</span> <span class="nordic_go Type">ComplexData</span> <span class="nordic_go -operator">&#123;</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr">  5 </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go Variable"><span class="nordic_go Field">id</span></span><span class="nordic_go Delimiter">:</span> <span class="nordic_go Variable">u32</span><span class="nordic_go Delimiter">,</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr">  6 </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go Variable"><span class="nordic_go Field">name</span></span><span class="nordic_go Delimiter">:</span> <span class="nordic_go Variable">String</span><span class="nordic_go Delimiter">,</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr">  7 </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go Variable"><span class="nordic_go Field">values</span></span><span class="nordic_go Delimiter">:</span> <span class="nordic_go Variable">HashSet</span><span class="nordic_go -operator">&lt;</span><span class="nordic_go Variable">u32</span><span class="nordic_go -operator">&gt;</span><span class="nordic_go Delimiter">,</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr">  8 </span><span class="nordic_go -operator">&#125;</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr">  9 </span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr"> 10 </span><span class="nordic_go Variable">impl</span> <span class="nordic_go Type">ComplexData</span> <span class="nordic_go -operator">&#123;</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr"> 11 </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go Variable">fn</span> <span class="nordic_go Variable"><span class="nordic_go Function"><span class="nordic_go Function">new</span></span></span><span class="nordic_go -operator">(</span><span class="nordic_go Type">id</span><span class="nordic_go Delimiter">:</span> <span class="nordic_go Variable">u32</span><span class="nordic_go Delimiter">,</span> <span class="nordic_go Variable"><span class="nordic_go Field">name</span></span><span class="nordic_go Delimiter">:</span> <span class="nordic_go -operator">&amp;</span><span class="nordic_go Variable">str</span><span class="nordic_go -operator">)</span> <span class="nordic_go -operator">-</span><span class="nordic_go -operator">&gt;</span> <span class="nordic_go Type">Self</span> <span class="nordic_go -operator">&#123;</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr"> 12 </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go Variable">let</span> <span class="nordic_go Variable">mut</span> <span class="nordic_go Variable">values</span> <span class="nordic_go -operator">=</span> <span class="nordic_go Variable"><span class="nordic_go Field">HashSet</span></span><span class="nordic_go Delimiter">:</span><span class="nordic_go Delimiter">:</span><span class="nordic_go Variable"><span class="nordic_go Function"><span class="nordic_go Function">new</span></span></span><span class="nordic_go -operator">(</span><span class="nordic_go -operator">)</span><span class="nordic_go Delimiter">;</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr"> 13 </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go Variable">values</span><span class="nordic_go Delimiter">.</span><span class="nordic_go Field"><span class="nordic_go Function">insert</span></span><span class="nordic_go -operator">(</span><span class="nordic_go Variable">id</span> <span class="nordic_go -operator">*</span> <span class="nordic_go Constant">10</span><span class="nordic_go -operator">)</span><span class="nordic_go Delimiter">;</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr"> 14 </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go Variable">values</span><span class="nordic_go Delimiter">.</span><span class="nordic_go Field"><span class="nordic_go Function">insert</span></span><span class="nordic_go -operator">(</span><span class="nordic_go Variable">id</span> <span class="nordic_go -operator">*</span> <span class="nordic_go Constant">20</span><span class="nordic_go -operator">)</span><span class="nordic_go Delimiter">;</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr"> 15 </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go Type">ComplexData</span> <span class="nordic_go -operator">&#123;</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr"> 16 </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go Variable">id</span><span class="nordic_go Delimiter">,</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr"> 17 </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go Variable"><span class="nordic_go Field">name</span></span><span class="nordic_go Delimiter">:</span> <span class="nordic_go Variable">name</span><span class="nordic_go Delimiter">.</span><span class="nordic_go Field"><span class="nordic_go Function">to_string</span></span><span class="nordic_go -operator">(</span><span class="nordic_go -operator">)</span><span class="nordic_go Delimiter">,</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr"> 18 </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go Variable">values</span><span class="nordic_go Delimiter">,</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr"> 19 </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -operator">&#125;</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr"> 20 </span><span class="nordic_go -ibl-indent-char-1">│</span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -ibl-whitespace-char-1"> </span><span class="nordic_go -operator">&#125;</span>
<span class="nordic_go SignColumn">  </span><span class="nordic_go LineNr"> 21 </span><span class="nordic_go -ibl-indent-char-1">│</span>

</pre>
</section>