<script> import "$lib/vicss/nord.css" </script>

<div style="display:flex;" class="nvimbufdiv"><section class="nord boxbg border_r" style="display: flex; padding:1rem;">
<pre>
<span class="nord NvimTreeFolderArrowClosed"> </span><span class="nord NvimTreeFolderIcon"></span> <span class="nord NvimTreeFolderName">.git</span>
<span class="nord NvimTreeFolderArrowOpen"> </span><span class="nord NvimTreeFolderIcon"></span> <span class="nord NvimTreeGitDirty">✗</span> <span class="nord NvimTreeGitNew">★</span> <span class="nord NvimTreeOpenedFolderName"><span class="nord NvimTreeGitNew">src</span></span>
<span class="nord NvimTreeIndentMarker">  </span><span class="nord NvimTreeFolderArrowOpen"> </span><span class="nord NvimTreeFolderIcon"></span> <span class="nord NvimTreeGitNew">★</span> <span class="nord NvimTreeOpenedFolderName"><span class="nord NvimTreeGitNew">lib</span></span>
<span class="nord NvimTreeIndentMarker">  │ </span><span class="nord NvimTreeFolderArrowClosed"> </span><span class="nord NvimTreeFolderIcon"></span> <span class="nord NvimTreeGitNew">★</span> <span class="nord NvimTreeFolderName"><span class="nord NvimTreeGitNew">vicss</span></span>
<span class="nord NvimTreeIndentMarker">  │ </span><span class="nord NvimTreeFolderArrowOpen"> </span><span class="nord NvimTreeFolderIcon"></span> <span class="nord NvimTreeGitNew">★</span> <span class="nord NvimTreeOpenedFolderName"><span class="nord NvimTreeGitNew">vihtml</span></span>
<span class="nord NvimTreeIndentMarker">  │ │ │ </span><span class="nord DevIconSvelte"></span> <span class="nord NvimTreeGitNew">★</span> <span class="nord NvimTreeGitNew">everforest.svelte</span>
<span class="nord NvimTreeIndentMarker">  │ │ │ </span><span class="nord DevIconSvelte"></span> <span class="nord NvimTreeGitNew">★</span> <span class="nord NvimTreeGitNew">nord.svelte</span>
<span class="nord NvimTreeIndentMarker">  │ │ └ </span><span class="nord DevIconSvelte"></span> <span class="nord NvimTreeGitNew">★</span> <span class="nord NvimTreeGitNew">onedark.svelte</span>
<span class="nord NvimTreeIndentMarker">  │ └ </span><span class="nord DevIconts">󰛦</span> index.ts
<span class="nord NvimTreeIndentMarker">  </span><span class="nord NvimTreeFolderArrowClosed"> </span><span class="nord NvimTreeFolderIcon"></span> <span class="nord NvimTreeGitDirty">✗</span> <span class="nord NvimTreeFolderName"><span class="nord NvimTreeGitDirty">routes</span></span>
<span class="nord NvimTreeIndentMarker">  │ </span><span class="nord DevIconTypeScriptDeclaration"></span> app.d.ts
<span class="nord NvimTreeIndentMarker">  └ </span><span class="nord DevIconhtml"></span> app.html
<span class="nord NvimTreeFolderArrowOpen"> </span><span class="nord NvimTreeFolderIcon"></span> <span class="nord NvimTreeOpenedFolderName">static</span>
<span class="nord NvimTreeIndentMarker">  └ </span><span class="nord DevIconpng"></span> <span class="nord Question">favicon.png</span>
<span class="nord NvimTreeFolderArrowOpen"> </span><span class="nord NvimTreeFolderIcon"></span> <span class="nord NvimTreeGitNew">★</span> <span class="nord NvimTreeOpenedFolderName"><span class="nord NvimTreeGitNew">vihtml</span></span>
<span class="nord NvimTreeIndentMarker">  │ </span><span class="nord DevIconlua"></span> <span class="nord NvimTreeGitNew">★</span> <span class="nord NvimTreeGitNew">format.lua</span>
<span class="nord NvimTreeIndentMarker">  │ </span><span class="nord DevIconlua"></span> <span class="nord NvimTreeGitNew">★</span> <span class="nord NvimTreeGitNew">init.lua</span>
<span class="nord NvimTreeIndentMarker">  └ </span><span class="nord DevIconlua"></span> <span class="nord NvimTreeGitNew">★</span> <span class="nord NvimTreeGitNew">utils.lua</span>
<span class="nord NvimTreeIndentMarker">  </span><span class="nord DevIconGitIgnore"></span> .gitignore
<span class="nord NvimTreeIndentMarker">  </span><span class="nord DevIconNPMrc"></span> .npmrc
<span class="nord NvimTreeIndentMarker">  </span><span class="nord DevIconBunLockfile"></span> <span class="nord Question">bun.lockb</span>
<span class="nord NvimTreeIndentMarker">  </span><span class="nord DevIconLicense"></span> LICENSE
<span class="nord NvimTreeIndentMarker">  </span><span class="nord DevIconPackageJson"></span> package.json
<span class="nord NvimTreeIndentMarker">  </span><span class="nord DevIconSvelteConfig"></span> svelte.config.js
<span class="nord NvimTreeIndentMarker">  </span><span class="nord DevIconTSConfig"></span> tsconfig.json
<span class="nord NvimTreeIndentMarker">  </span><span class="nord DevIconts">󰛦</span> vite.config.ts

</pre>
</section><section class="nord boxbg border_r" style="display: flex; padding:1rem;">
<pre>
<span class="nord -keyword">local</span> <span class="nord -variable">utils</span> <span class="nord -operator">=</span> <span class="nord -variable"><span class="nord -function-call"><span class="nord -function-builtin">require</span></span></span> <span class="nord -string">&quot;vihtml.utils&quot;</span>
<span class="nord -keyword">local</span> <span class="nord -variable"><span class="nord -constant">M</span></span> <span class="nord -operator">=</span> <span class="nord -punctuation-bracket"><span class="nord -constructor">{</span></span><span class="nord -punctuation-bracket"><span class="nord -constructor">}</span></span>

<span class="nord -variable"><span class="nord -constant">M</span></span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function">save_html</span></span></span> <span class="nord -operator">=</span> <span class="nord -keyword-function">function</span><span class="nord -punctuation-bracket">(</span><span class="nord -variable"><span class="nord -variable-parameter">path</span></span><span class="nord -punctuation-delimiter">,</span> <span class="nord -variable"><span class="nord -variable-parameter">str</span></span><span class="nord -punctuation-bracket">)</span>
<span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -keyword">local</span> <span class="nord -variable">file</span> <span class="nord -operator">=</span> <span class="nord -variable"><span class="nord Special">io</span></span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">open</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -variable">path</span><span class="nord -punctuation-delimiter">,</span> <span class="nord -string">&quot;wb&quot;</span><span class="nord -punctuation-bracket">)</span>
<span class="nord NonText"> </span>
<span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -keyword-conditional">if</span> <span class="nord -variable">file</span> <span class="nord -keyword-conditional">then</span>
<span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span><span class="nord NonText"> </span><span class="nord -variable">file</span><span class="nord -punctuation-delimiter">:</span><span class="nord -variable"><span class="nord -function-method-call">write</span></span><span class="nord -punctuation-bracket">(</span><span class="nord -variable">str</span><span class="nord -punctuation-bracket">)</span>
<span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span><span class="nord NonText"> </span><span class="nord -variable">file</span><span class="nord -punctuation-delimiter">:</span><span class="nord -variable"><span class="nord -function-method-call">close</span></span><span class="nord -punctuation-bracket">(</span><span class="nord -punctuation-bracket">)</span>
<span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -keyword-conditional">end</span>
<span class="nord -keyword-function">end</span>

<span class="nord -variable"><span class="nord -constant"><span class="nord -ibl-scope-underline-1">M</span></span><span class="nord -ibl-scope-underline-1"></span></span><span class="nord -ibl-scope-underline-1"><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function">base46_themes_html</span></span></span> <span class="nord -operator">=</span> <span class="nord -keyword-function">function</span><span class="nord -punctuation-bracket">(</span><span class="nord -punctuation-bracket">)</span></span><span class="nord -punctuation-bracket"></span>
<span class="nord -ibl-scope-char-1">│</span><span class="nord NonText"> </span><span class="nord -variable"><span class="nord -function-call"><span class="nord -function-builtin">require</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -string">'plenary.reload'</span><span class="nord -punctuation-bracket">)</span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">reload_module</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -string">'vihtml'</span><span class="nord -punctuation-bracket">)</span>
<span class="nord -ibl-scope-char-1">│</span>
<span class="nord -ibl-scope-char-1">│</span><span class="nord NonText"> </span><span class="nord -comment"><span class="nord -spell">-- local list = require(&quot;nvchad.utils&quot;).list_themes()</span></span>
<span class="nord -ibl-scope-char-1">│</span><span class="nord NonText"> </span><span class="nord -keyword">local</span> <span class="nord -variable">cwd</span> <span class="nord -operator">=</span> <span class="nord -variable">vim</span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member">uv</span></span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">cwd</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -punctuation-bracket">)</span>
<span class="nord -ibl-scope-char-1">│</span><span class="nord NonText"> </span><span class="nord -keyword">local</span> <span class="nord -variable">html_path</span> <span class="nord -operator">=</span> <span class="nord -variable">cwd</span> <span class="nord -operator">..</span> <span class="nord -string">&quot;/src/lib/vihtml/&quot;</span>
<span class="nord -ibl-scope-char-1">│</span><span class="nord NonText"> </span><span class="nord -keyword">local</span> <span class="nord -variable">css_path</span> <span class="nord -operator">=</span> <span class="nord -variable">cwd</span> <span class="nord -operator">..</span> <span class="nord -string">&quot;/src/lib/vicss/&quot;</span>
<span class="nord -ibl-scope-char-1">│</span>
<span class="nord -ibl-scope-char-1">│</span><span class="nord NonText"> </span><span class="nord -keyword">local</span> <span class="nord -variable">list</span> <span class="nord -operator">=</span> <span class="nord -punctuation-bracket"><span class="nord -constructor">{</span></span> <span class="nord -string">&quot;onedark&quot;</span><span class="nord -punctuation-delimiter">,</span> <span class="nord -string">&quot;nord&quot;</span><span class="nord -punctuation-delimiter">,</span> <span class="nord -string">&quot;everforest&quot;</span> <span class="nord -punctuation-bracket"><span class="nord -constructor">}</span></span>
<span class="nord -ibl-scope-char-1">│</span>
<span class="nord -ibl-scope-char-1">│</span><span class="nord NonText"> </span><span class="nord -keyword-repeat">for</span> <span class="nord -variable">_</span><span class="nord -punctuation-delimiter">,</span> <span class="nord -variable">v</span> <span class="nord -keyword">in</span> <span class="nord -variable"><span class="nord -function-call"><span class="nord -function-builtin">ipairs</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -variable">list</span><span class="nord -punctuation-bracket">)</span> <span class="nord -keyword-repeat">do</span>
<span class="nord -ibl-scope-char-1">│</span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span><span class="nord NonText"> </span><span class="nord -variable"><span class="nord -function-call"><span class="nord -function-builtin">require</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -string">&quot;nvconfig&quot;</span><span class="nord -punctuation-bracket">)</span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member">base46</span></span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member">theme</span></span> <span class="nord -operator">=</span> <span class="nord -variable">v</span>
<span class="nord -ibl-scope-char-1">│</span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span><span class="nord NonText"> </span><span class="nord -variable"><span class="nord -function-call"><span class="nord -function-builtin">require</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -string">&quot;base46&quot;</span><span class="nord -punctuation-bracket">)</span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">load_all_highlights</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -punctuation-bracket">)</span>
<span class="nord -ibl-scope-char-1">│</span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span>
<span class="nord -ibl-scope-char-1">│</span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span><span class="nord NonText"> </span><span class="nord -keyword">local</span> <span class="nord -variable">code</span> <span class="nord -operator">=</span> <span class="nord -variable">utils</span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">wins_to_html</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -variable">v</span><span class="nord -punctuation-bracket">)</span>
<span class="nord -ibl-scope-char-1">│</span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span>
<span class="nord -ibl-scope-char-1">│</span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span><span class="nord NonText"> </span><span class="nord -variable"><span class="nord -constant">M</span></span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">save_html</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -variable">html_path</span> <span class="nord -operator">..</span> <span class="nord -variable">v</span> <span class="nord -operator">..</span> <span class="nord -string">&quot;.svelte&quot;</span><span class="nord -punctuation-delimiter">,</span> <span class="nord -variable">code</span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member">html</span></span><span class="nord -punctuation-bracket">)</span>
<span class="nord -ibl-scope-char-1">│</span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span><span class="nord NonText"> </span><span class="nord -variable"><span class="nord -constant">M</span></span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">save_html</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -variable">css_path</span> <span class="nord -operator">..</span> <span class="nord -variable">v</span> <span class="nord -operator">..</span> <span class="nord -string">&quot;.css&quot;</span><span class="nord -punctuation-delimiter">,</span> <span class="nord -variable">code</span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member">css</span></span><span class="nord -punctuation-bracket">)</span>
<span class="nord -ibl-scope-char-1">│</span><span class="nord NonText"> </span><span class="nord -keyword-repeat">end</span>
<span class="nord -keyword-function">end</span>

<span class="nord -variable"><span class="nord -constant">M</span></span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">base46_themes_html</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -punctuation-bracket">)</span>

</pre>
</section></div>