<script> import "$lib/vihtml/nord_haskell.css" </script>

<section class="nord_haskell boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr">  1 </span><span class="nord_haskell -keyword-directive">&#123;-# LANGUAGE DeriveFunctor, DeriveFoldable, DeriveTraversable #-&#125;</span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr">  2 </span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr">  3 </span><span class="nord_haskell Include">import</span> <span class="nord_haskell -module">Data</span><span class="nord_haskell -operator">.</span><span class="nord_haskell -module">Map</span> <span class="nord_haskell -punctuation-bracket">(</span><span class="nord_haskell Type">Map</span><span class="nord_haskell -punctuation-delimiter">,</span> <span class="nord_haskell -variable">fromList</span><span class="nord_haskell -punctuation-delimiter">,</span> <span class="nord_haskell -variable">toList</span><span class="nord_haskell -punctuation-bracket">)</span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr">  4 </span><span class="nord_haskell Include">import</span> <span class="nord_haskell -module">Data</span><span class="nord_haskell -operator">.</span><span class="nord_haskell -module">List</span> <span class="nord_haskell -punctuation-bracket">(</span><span class="nord_haskell -variable">foldl'</span><span class="nord_haskell -punctuation-bracket">)</span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr">  5 </span><span class="nord_haskell Include">import</span> <span class="nord_haskell -module">Text</span><span class="nord_haskell -operator">.</span><span class="nord_haskell -module">Printf</span> <span class="nord_haskell -punctuation-bracket">(</span><span class="nord_haskell -variable">printf</span><span class="nord_haskell -punctuation-bracket">)</span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr">  6 </span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr">  7 </span><span class="nord_haskell -comment"><span class="nord_haskell -spell">-- Define a data type to hold complex data</span></span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr">  8 </span><span class="nord_haskell -keyword">data</span> <span class="nord_haskell Type">ComplexData</span> <span class="nord_haskell -operator">=</span> <span class="nord_haskell -constructor">ComplexData</span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr">  9 </span><span class="nord_haskell NonText">│</span><span class="nord_haskell NonText"> </span><span class="nord_haskell -punctuation-bracket">&#123;</span> <span class="nord_haskell -variable"><span class="nord_haskell -variable-member">id</span></span> <span class="nord_haskell -operator">::</span> <span class="nord_haskell Type">Int</span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr"> 10 </span><span class="nord_haskell NonText">│</span><span class="nord_haskell NonText"> </span><span class="nord_haskell -punctuation-delimiter">,</span> <span class="nord_haskell -variable"><span class="nord_haskell -variable-member">name</span></span> <span class="nord_haskell -operator">::</span> <span class="nord_haskell Type">String</span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr"> 11 </span><span class="nord_haskell NonText">│</span><span class="nord_haskell NonText"> </span><span class="nord_haskell -punctuation-delimiter">,</span> <span class="nord_haskell -variable"><span class="nord_haskell -variable-member">values</span></span> <span class="nord_haskell -operator">::</span> <span class="nord_haskell -punctuation-bracket"><span class="nord_haskell Type">[</span></span><span class="nord_haskell Type">Int</span><span class="nord_haskell -punctuation-bracket"><span class="nord_haskell Type">]</span></span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr"> 12 </span><span class="nord_haskell NonText">│</span><span class="nord_haskell NonText"> </span><span class="nord_haskell -punctuation-bracket">&#125;</span> <span class="nord_haskell -keyword">deriving</span> <span class="nord_haskell -punctuation-bracket">(</span><span class="nord_haskell Type">Show</span><span class="nord_haskell -punctuation-bracket">)</span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr"> 13 </span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr"> 14 </span><span class="nord_haskell -comment"><span class="nord_haskell -spell">-- Create a new instance of ComplexData</span></span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr"> 15 </span><span class="nord_haskell -variable"><span class="nord_haskell -function"><span class="nord_haskell -function"><span class="nord_haskell -function">newComplexData</span></span></span></span><span class="nord_haskell -function"> <span class="nord_haskell -operator">::</span> <span class="nord_haskell Type">Int</span> <span class="nord_haskell -operator">-&gt;</span> <span class="nord_haskell Type">String</span> <span class="nord_haskell -operator">-&gt;</span> <span class="nord_haskell Type">ComplexData</span></span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr"> 16 </span><span class="nord_haskell -variable"><span class="nord_haskell -function"><span class="nord_haskell -function">newComplexData</span></span></span> <span class="nord_haskell -variable"><span class="nord_haskell -variable-parameter">id</span></span> <span class="nord_haskell -variable"><span class="nord_haskell -variable-parameter">name</span></span> <span class="nord_haskell -operator">=</span> <span class="nord_haskell -constructor">ComplexData</span> <span class="nord_haskell -variable"><span class="nord_haskell -function-call"><span class="nord_haskell -variable">id</span></span></span> <span class="nord_haskell -variable"><span class="nord_haskell -function-call"><span class="nord_haskell -variable">name</span></span></span> <span class="nord_haskell -punctuation-bracket">[</span><span class="nord_haskell -variable"><span class="nord_haskell -function-call"><span class="nord_haskell -variable">id</span></span></span> <span class="nord_haskell -operator">*</span> <span class="nord_haskell -number">10</span><span class="nord_haskell -punctuation-delimiter">,</span> <span class="nord_haskell -variable"><span class="nord_haskell -function-call"><span class="nord_haskell -variable">id</span></span></span> <span class="nord_haskell -operator">*</span> <span class="nord_haskell -number">20</span><span class="nord_haskell -punctuation-delimiter">,</span> <span class="nord_haskell -variable"><span class="nord_haskell -function-call"><span class="nord_haskell -variable">id</span></span></span> <span class="nord_haskell -operator">*</span> <span class="nord_haskell -number">30</span><span class="nord_haskell -punctuation-bracket">]</span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr"> 17 </span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr"> 18 </span><span class="nord_haskell -comment"><span class="nord_haskell -spell">-- Calculate the average of values in ComplexData</span></span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr"> 19 </span><span class="nord_haskell -variable"><span class="nord_haskell -function"><span class="nord_haskell -function"><span class="nord_haskell -function">calculate</span></span></span></span><span class="nord_haskell -function"> <span class="nord_haskell -operator">::</span> <span class="nord_haskell Type">ComplexData</span> <span class="nord_haskell -operator">-&gt;</span> <span class="nord_haskell Type">Double</span></span>
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr"> 20 </span><span class="nord_haskell -variable"><span class="nord_haskell -function"><span class="nord_haskell -function">calculate</span></span></span> <span class="nord_haskell -variable-parameter"><span class="nord_haskell -punctuation-bracket">(</span><span class="nord_haskell -constructor">ComplexData</span> <span class="nord_haskell SpecialChar">_</span> <span class="nord_haskell SpecialChar">_</span> <span class="nord_haskell -variable">values</span><span class="nord_haskell -punctuation-bracket">)</span></span> <span class="nord_haskell -operator">=</span> 
<span class="nord_haskell SignColumn">  </span><span class="nord_haskell LineNr"> 21 </span><span class="nord_haskell NonText">│</span><span class="nord_haskell NonText"> </span><span class="nord_haskell -variable"><span class="nord_haskell -function-call">fromIntegral</span></span> <span class="nord_haskell -punctuation-bracket">(</span><span class="nord_haskell -variable"><span class="nord_haskell -function-call">sum</span></span> <span class="nord_haskell -variable"><span class="nord_haskell -function-call"><span class="nord_haskell -variable">values</span></span></span><span class="nord_haskell -punctuation-bracket">)</span> <span class="nord_haskell -operator">/</span> <span class="nord_haskell -variable"><span class="nord_haskell -function-call">fromIntegral</span></span> <span class="nord_haskell -punctuation-bracket">(</span><span class="nord_haskell -variable"><span class="nord_haskell -function-call">length</span></span> <span class="nord_haskell -variable"><span class="nord_haskell -function-call"><span class="nord_haskell -variable">values</span></span></span><span class="nord_haskell -punctuation-bracket">)</span>

</pre>
</section>