<script> import "$lib/vicss/nord.css" </script>

<div class='nvim_box'><div class='stl w-[1180px]'><pre bg-blue><span class="stl1tnord"></span><span class="stl2tnord">  </span><span class="stl3tnord">  </span><span class="stl4tnord">stl_html.lua  </span><span class="stl5tnord"> 󰅖 </span><span class="stl6tnord">    </span><span class="stl7tnord">  </span><span class="stl8tnord">init.lua    </span><span class="stl9tnord"> 󰅖 </span><span class="stl10tnord">   </span><span class="stl11tnord">  </span><span class="stl12tnord">utils.lua   </span><span class="stl13tnord"> 󰅖 </span><span class="stl14tnord">                                              </span><span class="stl15tnord">   </span><span class="stl16tnord"> 󰅖 </span></pre></div><div style="display:flex;" class="nvimbufdiv"><section class="nord boxbg p-1 flex bg-[#2e3440] text-[#e5e9f0] w-[1180px]"  border='0 r-1 solid #414753'>
<pre>
<span class="nord SignColumn">  </span><span class="nord LineNr"> 1 </span><span class="nord -keyword">local</span> <span class="nord -variable">utils</span> <span class="nord -operator">=</span> <span class="nord -variable"><span class="nord -function-call"><span class="nord -function-builtin">require</span></span></span> <span class="nord -string">&quot;vihtml.utils&quot;</span>
<span class="nord Added">┃ </span><span class="nord LineNr"> 2 </span><span class="nord -keyword">local</span> <span class="nord -variable">state</span> <span class="nord -operator">=</span> <span class="nord -variable"><span class="nord -function-call"><span class="nord -function-builtin">require</span></span></span> <span class="nord -string">&quot;vihtml.state&quot;</span>
<span class="nord SignColumn">  </span><span class="nord LineNr"> 3 </span><span class="nord -keyword">local</span> <span class="nord -variable"><span class="nord -constant">M</span></span> <span class="nord -operator">=</span> <span class="nord -punctuation-bracket"><span class="nord -constructor">&#123;</span></span><span class="nord -punctuation-bracket"><span class="nord -constructor">&#125;</span></span>
<span class="nord SignColumn">  </span><span class="nord LineNr"> 4 </span>
<span class="nord SignColumn">  </span><span class="nord LineNr"> 5 </span><span class="nord -variable"><span class="nord -constant">M</span></span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function">save_html</span></span></span> <span class="nord -operator">=</span> <span class="nord -keyword-function">function</span><span class="nord -punctuation-bracket">(</span><span class="nord -variable"><span class="nord -variable-parameter">path</span></span><span class="nord -punctuation-delimiter">,</span> <span class="nord -variable"><span class="nord -variable-parameter">str</span></span><span class="nord -punctuation-bracket">)</span>
<span class="nord SignColumn">  </span><span class="nord LineNr"> 6 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -keyword">local</span> <span class="nord -variable">file</span> <span class="nord -operator">=</span> <span class="nord -variable"><span class="nord Special">io</span></span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">open</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -variable">path</span><span class="nord -punctuation-delimiter">,</span> <span class="nord -string">&quot;wb&quot;</span><span class="nord -punctuation-bracket">)</span>
<span class="nord SignColumn">  </span><span class="nord LineNr"> 7 </span><span class="nord NonText"> </span>
<span class="nord SignColumn">  </span><span class="nord LineNr"> 8 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -keyword-conditional">if</span> <span class="nord -variable">file</span> <span class="nord -keyword-conditional">then</span>
<span class="nord SignColumn">  </span><span class="nord LineNr"> 9 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span><span class="nord NonText"> </span><span class="nord -variable">file</span><span class="nord -punctuation-delimiter">:</span><span class="nord -variable"><span class="nord -function-method-call">write</span></span><span class="nord -punctuation-bracket">(</span><span class="nord -variable">str</span><span class="nord -punctuation-bracket">)</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">10 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span><span class="nord NonText"> </span><span class="nord -variable">file</span><span class="nord -punctuation-delimiter">:</span><span class="nord -variable"><span class="nord -function-method-call">close</span></span><span class="nord -punctuation-bracket">(</span><span class="nord -punctuation-bracket">)</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">11 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -keyword-conditional">end</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">12 </span><span class="nord -keyword-function">end</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">13 </span>
<span class="nord SignColumn">  </span><span class="nord CursorLineNr">14 </span><span class="nord -variable"><span class="nord -constant">M</span></span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function">base46_themes_html</span></span></span> <span class="nord -operator">=</span> <span class="nord -keyword-function">function</span><span class="nord -punctuation-bracket"><span class="nord MatchWord">(</span></span><span class="nord -punctuation-bracket"><span class="nord MatchWord">)</span></span>
<span class="nord Changed">┃ </span><span class="nord LineNr">15 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -variable"><span class="nord -function-call"><span class="nord -function-builtin">require</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -string">&quot;plenary.reload&quot;</span><span class="nord -punctuation-bracket">)</span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">reload_module</span></span></span> <span class="nord -string">&quot;vihtml&quot;</span>
<span class="nord Added">┃ </span><span class="nord LineNr">16 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -variable">utils</span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">save_term_w</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -punctuation-bracket">)</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">17 </span><span class="nord NonText"> </span>
<span class="nord SignColumn">  </span><span class="nord LineNr">18 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -comment"><span class="nord -spell">-- local list = require(&quot;nvchad.utils&quot;).list_themes()</span></span>
<span class="nord SignColumn">  </span><span class="nord LineNr">19 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -keyword">local</span> <span class="nord -variable">cwd</span> <span class="nord -operator">=</span> <span class="nord -variable">vim</span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member">uv</span></span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">cwd</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -punctuation-bracket">)</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">20 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -keyword">local</span> <span class="nord -variable">html_path</span> <span class="nord -operator">=</span> <span class="nord -variable">cwd</span> <span class="nord -operator">..</span> <span class="nord -string">&quot;/src/lib/vihtml/&quot;</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">21 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -keyword">local</span> <span class="nord -variable">css_path</span> <span class="nord -operator">=</span> <span class="nord -variable">cwd</span> <span class="nord -operator">..</span> <span class="nord -string">&quot;/src/lib/vicss/&quot;</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">22 </span><span class="nord NonText"> </span>
<span class="nord Changed">┃ </span><span class="nord LineNr">23 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -keyword">local</span> <span class="nord -variable">list</span> <span class="nord -operator">=</span> <span class="nord -punctuation-bracket"><span class="nord -constructor">&#123;</span></span> <span class="nord -string">&quot;onedark&quot;</span><span class="nord -punctuation-delimiter">,</span> <span class="nord -string">&quot;nord&quot;</span><span class="nord -punctuation-delimiter">,</span> <span class="nord -string">&quot;everforest&quot;</span> <span class="nord -punctuation-bracket"><span class="nord -constructor">&#125;</span></span>
<span class="nord SignColumn">  </span><span class="nord LineNr">24 </span><span class="nord NonText"> </span>
<span class="nord SignColumn">  </span><span class="nord LineNr">25 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -keyword-repeat">for</span> <span class="nord -variable">_</span><span class="nord -punctuation-delimiter">,</span> <span class="nord -variable">v</span> <span class="nord -keyword">in</span> <span class="nord -variable"><span class="nord -function-call"><span class="nord -function-builtin">ipairs</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -variable">list</span><span class="nord -punctuation-bracket">)</span> <span class="nord -keyword-repeat">do</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">26 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span><span class="nord NonText"> </span><span class="nord -variable"><span class="nord -function-call"><span class="nord -function-builtin">require</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -string">&quot;nvconfig&quot;</span><span class="nord -punctuation-bracket">)</span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member">base46</span></span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member">theme</span></span> <span class="nord -operator">=</span> <span class="nord -variable">v</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">27 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span><span class="nord NonText"> </span><span class="nord -variable"><span class="nord -function-call"><span class="nord -function-builtin">require</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -string">&quot;base46&quot;</span><span class="nord -punctuation-bracket">)</span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">load_all_highlights</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -punctuation-bracket">)</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">28 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">29 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span><span class="nord NonText"> </span><span class="nord -keyword">local</span> <span class="nord -variable">code</span> <span class="nord -operator">=</span> <span class="nord -variable">utils</span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">wins_to_html</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -variable">v</span><span class="nord -punctuation-bracket">)</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">30 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">31 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span><span class="nord NonText"> </span><span class="nord -variable"><span class="nord -constant">M</span></span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">save_html</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -variable">html_path</span> <span class="nord -operator">..</span> <span class="nord -variable">v</span> <span class="nord -operator">..</span> <span class="nord -string">&quot;.svelte&quot;</span><span class="nord -punctuation-delimiter">,</span> <span class="nord -variable">code</span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member">html</span></span><span class="nord -punctuation-bracket">)</span>
<span class="nord Added">┃ </span><span class="nord LineNr">32 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">33 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span><span class="nord NonText"> </span><span class="nord -variable"><span class="nord -constant">M</span></span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">save_html</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -variable">css_path</span> <span class="nord -operator">..</span> <span class="nord -variable">v</span> <span class="nord -operator">..</span> <span class="nord -string">&quot;.css&quot;</span><span class="nord -punctuation-delimiter">,</span> <span class="nord -variable">code</span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member">css</span></span><span class="nord -punctuation-bracket">)</span>
<span class="nord Added">┃ </span><span class="nord LineNr">34 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span>
<span class="nord Added">┃ </span><span class="nord LineNr">35 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -ibl-indent-char-1">│</span><span class="nord NonText"> </span><span class="nord -variable">state</span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member">stl_w</span></span> <span class="nord -operator">=</span> <span class="nord -number">0</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">36 </span><span class="nord NonText"> </span><span class="nord NonText"> </span><span class="nord -keyword-repeat">end</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">37 </span><span class="nord -keyword-function">end</span>
<span class="nord SignColumn">  </span><span class="nord LineNr">38 </span>
<span class="nord SignColumn">  </span><span class="nord LineNr">39 </span><span class="nord -variable"><span class="nord -constant">M</span></span><span class="nord -punctuation-delimiter">.</span><span class="nord -variable"><span class="nord -variable-member"><span class="nord -function-call">base46_themes_html</span></span></span><span class="nord -punctuation-bracket">(</span><span class="nord -punctuation-bracket">)</span>

</pre>
</section></div><div class='stl w-[1180px]'><pre bg-blue><span class="stl1snord">  NORMAL</span><span class="stl2snord"></span><span class="stl3snord"></span><span class="stl4snord">  init.lua </span><span class="stl5snord"></span><span class="stl6snord">  main  5  2                  </span><span class="stl7snord">                   </span><span class="stl8snord">   LSP ~ lua_ls </span><span class="stl9snord"></span><span class="stl10snord">󰉋 </span><span class="stl11snord"> base46-site </span><span class="stl12snord"></span><span class="stl13snord"> </span><span class="stl14snord"> 35 % </span></pre></div></div>