<script> import "$lib/vihtml/onedark_rust.css" </script>

<section class="onedark_rust boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr">  1 </span><span class="onedark_rust Keyword">use</span> <span class="onedark_rust Include">std</span><span class="onedark_rust Delimiter">::</span><span class="onedark_rust Include">collections</span><span class="onedark_rust Delimiter">::</span>HashMap;
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr">  2 </span><span class="onedark_rust Keyword">use</span> <span class="onedark_rust Include">std</span><span class="onedark_rust Delimiter">::</span><span class="onedark_rust Include">fs</span><span class="onedark_rust Delimiter">::</span>File;
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr">  3 </span><span class="onedark_rust Keyword">use</span> <span class="onedark_rust Include">std</span><span class="onedark_rust Delimiter">::</span><span class="onedark_rust Include">io</span><span class="onedark_rust Delimiter">::</span>&#123;<span class="onedark_rust Constant">self</span>, Write&#125;;
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr">  4 </span>
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr">  5 </span><span class="onedark_rust Comment">// Enum to represent different shapes</span>
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr">  6 </span><span class="onedark_rust Keyword">enum</span> <span class="onedark_rust Identifier">Shape</span> &#123;
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr">  7 </span><span class="onedark_rust IndentLine">│</span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span>Rectangle &#123; width: <span class="onedark_rust Type">u32</span>, height: <span class="onedark_rust Type">u32</span> &#125;,
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr">  8 </span><span class="onedark_rust IndentLine">│</span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span>Triangle &#123; base: <span class="onedark_rust Type">u32</span>, height: <span class="onedark_rust Type">u32</span> &#125;,
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr">  9 </span><span class="onedark_rust IndentLine">│</span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust Function">Circle</span>(<span class="onedark_rust Type">f64</span>),
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr"> 10 </span>&#125;
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr"> 11 </span>
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr"> 12 </span><span class="onedark_rust Comment">// Function to calculate the area of a shape</span>
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr"> 13 </span><span class="onedark_rust Keyword">fn</span> <span class="onedark_rust Function">calculate_area</span>(shape: <span class="onedark_rust StorageClass">&amp;</span>Shape) <span class="onedark_rust Operator">-&gt;</span> <span class="onedark_rust Type">f64</span> &#123;
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr"> 14 </span><span class="onedark_rust IndentLine">│</span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust Conditional">match</span> shape &#123;
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr"> 15 </span><span class="onedark_rust IndentLine">│</span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust IndentLine">│</span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust Include">Shape</span><span class="onedark_rust Delimiter">::</span>Rectangle &#123; width, height &#125; <span class="onedark_rust Operator">=&gt;</span> (<span class="onedark_rust StorageClass">*</span>width <span class="onedark_rust Operator">as</span> <span class="onedark_rust Type">f64</span>) <span class="onedark_rust Operator">*</span> (<span class="onedark_rust StorageClass">*</span>height <span class="onedark_rust Operator">as</span> <span class="onedark_rust Type">f64</span>),
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr"> 16 </span><span class="onedark_rust IndentLine">│</span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust IndentLine">│</span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust Include">Shape</span><span class="onedark_rust Delimiter">::</span>Triangle &#123; base, height &#125; <span class="onedark_rust Operator">=&gt;</span> <span class="onedark_rust Float">0.5</span> <span class="onedark_rust Operator">*</span> (<span class="onedark_rust StorageClass">*</span>base <span class="onedark_rust Operator">as</span> <span class="onedark_rust Type">f64</span>) <span class="onedark_rust Operator">*</span> (<span class="onedark_rust StorageClass">*</span>height <span class="onedark_rust Operator">as</span> <span class="onedark_rust Type">f64</span>),
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr"> 17 </span><span class="onedark_rust IndentLine">│</span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust IndentLine">│</span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust Include">Shape</span><span class="onedark_rust Delimiter">::</span><span class="onedark_rust Function">Circle</span>(radius) <span class="onedark_rust Operator">=&gt;</span> <span class="onedark_rust Include">std</span><span class="onedark_rust Delimiter">::</span><span class="onedark_rust Type">f64</span><span class="onedark_rust Delimiter">::</span><span class="onedark_rust Include">consts</span><span class="onedark_rust Delimiter">::</span>PI <span class="onedark_rust Operator">*</span> radius.<span class="onedark_rust Function">powi</span>(<span class="onedark_rust Number">2</span>),
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr"> 18 </span><span class="onedark_rust IndentLine">│</span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span><span class="onedark_rust -ibl-whitespace-char-1"> </span>&#125;
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr"> 19 </span>&#125;
<span class="onedark_rust SignColumn">  </span><span class="onedark_rust LineNr"> 20 </span>

</pre>
</section>