<script> import "$lib/vihtml/onedark_vivid_c.css" </script>

<section class="onedark_vivid_c boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr">  1 </span><span class="onedark_vivid_c Keyword">#include</span> <span class="onedark_vivid_c -string">&lt;stdio.h&gt;</span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr">  2 </span><span class="onedark_vivid_c Keyword">#include</span> <span class="onedark_vivid_c -string">&lt;stdlib.h&gt;</span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr">  3 </span><span class="onedark_vivid_c Keyword">#include</span> <span class="onedark_vivid_c -string">&lt;stdbool.h&gt;</span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr">  4 </span><span class="onedark_vivid_c Keyword">#include</span> <span class="onedark_vivid_c -string">&lt;math.h&gt;</span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr">  5 </span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr">  6 </span><span class="onedark_vivid_c Keyword">#define</span> <span class="onedark_vivid_c -variable"><span class="onedark_vivid_c -constant-c"><span class="onedark_vivid_c -constant">PI</span></span></span> <span class="onedark_vivid_c -variable"><span class="onedark_vivid_c Number">3.14159</span></span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr">  7 </span><span class="onedark_vivid_c Keyword">#define</span> <span class="onedark_vivid_c -variable"><span class="onedark_vivid_c -constant-c"><span class="onedark_vivid_c -function-macro">SQUARE</span></span></span><span class="onedark_vivid_c -punctuation-bracket">(</span><span class="onedark_vivid_c -variable"><span class="onedark_vivid_c -variable-parameter-c">x</span></span><span class="onedark_vivid_c -punctuation-bracket">)</span> <span class="onedark_vivid_c -punctuation-bracket">(</span><span class="onedark_vivid_c -punctuation-bracket">(</span><span class="onedark_vivid_c Type"><span class="onedark_vivid_c Type">x</span></span><span class="onedark_vivid_c -punctuation-bracket">)</span> <span class="onedark_vivid_c -operator">*</span> <span class="onedark_vivid_c -punctuation-bracket">(</span><span class="onedark_vivid_c -variable">x</span><span class="onedark_vivid_c -punctuation-bracket">)</span><span class="onedark_vivid_c -punctuation-bracket">)</span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr">  8 </span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr">  9 </span><span class="onedark_vivid_c Keyword">typedef</span> <span class="onedark_vivid_c Keyword">struct</span> <span class="onedark_vivid_c -punctuation-bracket">&#123;</span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr"> 10 </span><span class="onedark_vivid_c IndentLine">│</span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c -type-builtin-c">double</span> <span class="onedark_vivid_c -property">x</span><span class="onedark_vivid_c Delimiter">,</span> <span class="onedark_vivid_c -property">y</span><span class="onedark_vivid_c Delimiter">;</span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr"> 11 </span><span class="onedark_vivid_c IndentLine">│</span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c -type-builtin-c">double</span> <span class="onedark_vivid_c -property">radius</span><span class="onedark_vivid_c Delimiter">;</span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr"> 12 </span><span class="onedark_vivid_c -punctuation-bracket">&#125;</span> <span class="onedark_vivid_c Type"><span class="onedark_vivid_c Type">Circle</span></span><span class="onedark_vivid_c Delimiter">;</span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr"> 13 </span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr"> 14 </span><span class="onedark_vivid_c -type-builtin-c">double</span> <span class="onedark_vivid_c -variable"><span class="onedark_vivid_c -function">calculate_area</span></span><span class="onedark_vivid_c -punctuation-bracket">(</span><span class="onedark_vivid_c Keyword">const</span> <span class="onedark_vivid_c Type">Circle</span> <span class="onedark_vivid_c -variable-parameter-c"><span class="onedark_vivid_c -operator">*</span><span class="onedark_vivid_c -variable">c</span></span><span class="onedark_vivid_c -punctuation-bracket">)</span> <span class="onedark_vivid_c -punctuation-bracket">&#123;</span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr"> 15 </span><span class="onedark_vivid_c IndentLine">│</span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c Keyword">return</span> <span class="onedark_vivid_c -variable"><span class="onedark_vivid_c -constant-c">PI</span></span> <span class="onedark_vivid_c -operator">*</span> <span class="onedark_vivid_c -variable"><span class="onedark_vivid_c -constant-c"><span class="onedark_vivid_c -function">SQUARE</span></span></span><span class="onedark_vivid_c -punctuation-bracket">(</span><span class="onedark_vivid_c -_parent"><span class="onedark_vivid_c -variable">c</span><span class="onedark_vivid_c -operator">-&gt;</span><span class="onedark_vivid_c -property">radius</span></span><span class="onedark_vivid_c -punctuation-bracket">)</span><span class="onedark_vivid_c Delimiter">;</span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr"> 16 </span><span class="onedark_vivid_c -punctuation-bracket">&#125;</span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr"> 17 </span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr"> 18 </span><span class="onedark_vivid_c -type-builtin-c">void</span> <span class="onedark_vivid_c -variable"><span class="onedark_vivid_c -function">print_array</span></span><span class="onedark_vivid_c -punctuation-bracket">(</span><span class="onedark_vivid_c Keyword">const</span> <span class="onedark_vivid_c -type-builtin-c">char</span> <span class="onedark_vivid_c -variable-parameter-c"><span class="onedark_vivid_c -operator">*</span><span class="onedark_vivid_c -variable">msg</span></span><span class="onedark_vivid_c Delimiter">,</span> <span class="onedark_vivid_c -type-builtin-c">int</span> <span class="onedark_vivid_c -variable-parameter-c"><span class="onedark_vivid_c -operator">*</span><span class="onedark_vivid_c -variable">arr</span></span><span class="onedark_vivid_c Delimiter">,</span> <span class="onedark_vivid_c -type-builtin-c">size_t</span> <span class="onedark_vivid_c -variable"><span class="onedark_vivid_c -variable-parameter-c">size</span></span><span class="onedark_vivid_c -punctuation-bracket">)</span> <span class="onedark_vivid_c -punctuation-bracket">&#123;</span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr"> 19 </span><span class="onedark_vivid_c IndentLine">│</span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c -variable"><span class="onedark_vivid_c -function">printf</span></span><span class="onedark_vivid_c -punctuation-bracket">(</span><span class="onedark_vivid_c -string">&quot;%s: &quot;</span><span class="onedark_vivid_c Delimiter">,</span> <span class="onedark_vivid_c -variable">msg</span><span class="onedark_vivid_c -punctuation-bracket">)</span><span class="onedark_vivid_c Delimiter">;</span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr"> 20 </span><span class="onedark_vivid_c IndentLine">│</span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c Keyword">for</span> <span class="onedark_vivid_c -punctuation-bracket">(</span><span class="onedark_vivid_c -type-builtin-c">size_t</span> <span class="onedark_vivid_c -variable">i</span> <span class="onedark_vivid_c -operator">=</span> <span class="onedark_vivid_c Number">0</span><span class="onedark_vivid_c Delimiter">;</span> <span class="onedark_vivid_c -variable">i</span> <span class="onedark_vivid_c -operator">&lt;</span> <span class="onedark_vivid_c -variable">size</span><span class="onedark_vivid_c Delimiter">;</span> <span class="onedark_vivid_c -variable">i</span><span class="onedark_vivid_c -operator">++</span><span class="onedark_vivid_c -punctuation-bracket">)</span> <span class="onedark_vivid_c -variable"><span class="onedark_vivid_c -function">printf</span></span><span class="onedark_vivid_c -punctuation-bracket">(</span><span class="onedark_vivid_c -string">&quot;%d &quot;</span><span class="onedark_vivid_c Delimiter">,</span> <span class="onedark_vivid_c -variable">arr</span><span class="onedark_vivid_c -punctuation-bracket">[</span><span class="onedark_vivid_c -variable">i</span><span class="onedark_vivid_c -punctuation-bracket">]</span><span class="onedark_vivid_c -punctuation-bracket">)</span><span class="onedark_vivid_c Delimiter">;</span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr"> 21 </span><span class="onedark_vivid_c IndentLine">│</span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c -ibl-whitespace-char-1"> </span><span class="onedark_vivid_c -variable"><span class="onedark_vivid_c -function">printf</span></span><span class="onedark_vivid_c -punctuation-bracket">(</span><span class="onedark_vivid_c -string">&quot;<span class="onedark_vivid_c -string-escape">\n</span>&quot;</span><span class="onedark_vivid_c -punctuation-bracket">)</span><span class="onedark_vivid_c Delimiter">;</span>
<span class="onedark_vivid_c SignColumn">  </span><span class="onedark_vivid_c LineNr"> 22 </span><span class="onedark_vivid_c -punctuation-bracket">&#125;</span>

</pre>
</section>