<script> import "$lib/vihtml/oxocarbon_haskell.css" </script>

<section class="oxocarbon_haskell boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr">  1 </span><span class="oxocarbon_haskell -keyword">&#123;-# LANGUAGE DeriveFunctor, DeriveFoldable, DeriveTraversable #-&#125;</span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr">  2 </span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr">  3 </span><span class="oxocarbon_haskell -keyword">import</span> <span class="oxocarbon_haskell Structure">Data</span><span class="oxocarbon_haskell Operator">.</span><span class="oxocarbon_haskell Structure">Map</span> <span class="oxocarbon_haskell -punctuation-bracket">(</span><span class="oxocarbon_haskell Type">Map</span><span class="oxocarbon_haskell -punctuation-delimiter">,</span> <span class="oxocarbon_haskell -variable">fromList</span><span class="oxocarbon_haskell -punctuation-delimiter">,</span> <span class="oxocarbon_haskell -variable">toList</span><span class="oxocarbon_haskell -punctuation-bracket">)</span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr">  4 </span><span class="oxocarbon_haskell -keyword">import</span> <span class="oxocarbon_haskell Structure">Data</span><span class="oxocarbon_haskell Operator">.</span><span class="oxocarbon_haskell Structure">List</span> <span class="oxocarbon_haskell -punctuation-bracket">(</span><span class="oxocarbon_haskell -variable">foldl'</span><span class="oxocarbon_haskell -punctuation-bracket">)</span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr">  5 </span><span class="oxocarbon_haskell -keyword">import</span> <span class="oxocarbon_haskell Structure">Text</span><span class="oxocarbon_haskell Operator">.</span><span class="oxocarbon_haskell Structure">Printf</span> <span class="oxocarbon_haskell -punctuation-bracket">(</span><span class="oxocarbon_haskell -variable">printf</span><span class="oxocarbon_haskell -punctuation-bracket">)</span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr">  6 </span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr">  7 </span><span class="oxocarbon_haskell Comment"><span class="oxocarbon_haskell -spell">-- Define a data type to hold complex data</span></span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr">  8 </span><span class="oxocarbon_haskell -keyword">data</span> <span class="oxocarbon_haskell Type">ComplexData</span> <span class="oxocarbon_haskell Operator">=</span> <span class="oxocarbon_haskell -constructor">ComplexData</span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr">  9 </span><span class="oxocarbon_haskell NonText">│</span><span class="oxocarbon_haskell NonText"> </span><span class="oxocarbon_haskell -punctuation-bracket">&#123;</span> <span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -variable">id</span></span> <span class="oxocarbon_haskell Operator">::</span> <span class="oxocarbon_haskell Type">Int</span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr"> 10 </span><span class="oxocarbon_haskell NonText">│</span><span class="oxocarbon_haskell NonText"> </span><span class="oxocarbon_haskell -punctuation-delimiter">,</span> <span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -variable">name</span></span> <span class="oxocarbon_haskell Operator">::</span> <span class="oxocarbon_haskell Type">String</span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr"> 11 </span><span class="oxocarbon_haskell NonText">│</span><span class="oxocarbon_haskell NonText"> </span><span class="oxocarbon_haskell -punctuation-delimiter">,</span> <span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -variable">values</span></span> <span class="oxocarbon_haskell Operator">::</span> <span class="oxocarbon_haskell -punctuation-bracket"><span class="oxocarbon_haskell Type">[</span></span><span class="oxocarbon_haskell Type">Int</span><span class="oxocarbon_haskell -punctuation-bracket"><span class="oxocarbon_haskell Type">]</span></span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr"> 12 </span><span class="oxocarbon_haskell NonText">│</span><span class="oxocarbon_haskell NonText"> </span><span class="oxocarbon_haskell -punctuation-bracket">&#125;</span> <span class="oxocarbon_haskell -keyword">deriving</span> <span class="oxocarbon_haskell -punctuation-bracket">(</span><span class="oxocarbon_haskell Type">Show</span><span class="oxocarbon_haskell -punctuation-bracket">)</span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr"> 13 </span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr"> 14 </span><span class="oxocarbon_haskell Comment"><span class="oxocarbon_haskell -spell">-- Create a new instance of ComplexData</span></span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr"> 15 </span><span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -function"><span class="oxocarbon_haskell -function"><span class="oxocarbon_haskell -function">newComplexData</span></span></span></span><span class="oxocarbon_haskell -function"> <span class="oxocarbon_haskell Operator">::</span> <span class="oxocarbon_haskell Type">Int</span> <span class="oxocarbon_haskell Operator">-&gt;</span> <span class="oxocarbon_haskell Type">String</span> <span class="oxocarbon_haskell Operator">-&gt;</span> <span class="oxocarbon_haskell Type">ComplexData</span></span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr"> 16 </span><span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -function"><span class="oxocarbon_haskell -function">newComplexData</span></span></span> <span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -variable">id</span></span> <span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -variable">name</span></span> <span class="oxocarbon_haskell Operator">=</span> <span class="oxocarbon_haskell -constructor">ComplexData</span> <span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -function"><span class="oxocarbon_haskell -variable">id</span></span></span> <span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -function"><span class="oxocarbon_haskell -variable">name</span></span></span> <span class="oxocarbon_haskell -punctuation-bracket">[</span><span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -function"><span class="oxocarbon_haskell -variable">id</span></span></span> <span class="oxocarbon_haskell Operator">*</span> <span class="oxocarbon_haskell Number">10</span><span class="oxocarbon_haskell -punctuation-delimiter">,</span> <span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -function"><span class="oxocarbon_haskell -variable">id</span></span></span> <span class="oxocarbon_haskell Operator">*</span> <span class="oxocarbon_haskell Number">20</span><span class="oxocarbon_haskell -punctuation-delimiter">,</span> <span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -function"><span class="oxocarbon_haskell -variable">id</span></span></span> <span class="oxocarbon_haskell Operator">*</span> <span class="oxocarbon_haskell Number">30</span><span class="oxocarbon_haskell -punctuation-bracket">]</span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr"> 17 </span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr"> 18 </span><span class="oxocarbon_haskell Comment"><span class="oxocarbon_haskell -spell">-- Calculate the average of values in ComplexData</span></span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr"> 19 </span><span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -function"><span class="oxocarbon_haskell -function"><span class="oxocarbon_haskell -function">calculate</span></span></span></span><span class="oxocarbon_haskell -function"> <span class="oxocarbon_haskell Operator">::</span> <span class="oxocarbon_haskell Type">ComplexData</span> <span class="oxocarbon_haskell Operator">-&gt;</span> <span class="oxocarbon_haskell Type">Double</span></span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr"> 20 </span><span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -function"><span class="oxocarbon_haskell -function">calculate</span></span></span> <span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -punctuation-bracket">(</span><span class="oxocarbon_haskell -constructor">ComplexData</span> <span class="oxocarbon_haskell SpecialChar">_</span> <span class="oxocarbon_haskell SpecialChar">_</span> <span class="oxocarbon_haskell -variable">values</span><span class="oxocarbon_haskell -punctuation-bracket">)</span></span> <span class="oxocarbon_haskell Operator">=</span> 
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr"> 21 </span><span class="oxocarbon_haskell NonText">│</span><span class="oxocarbon_haskell NonText"> </span><span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -function">fromIntegral</span></span> <span class="oxocarbon_haskell -punctuation-bracket">(</span><span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -function">sum</span></span> <span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -function"><span class="oxocarbon_haskell -variable">values</span></span></span><span class="oxocarbon_haskell -punctuation-bracket">)</span> <span class="oxocarbon_haskell Operator">/</span> <span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -function">fromIntegral</span></span> <span class="oxocarbon_haskell -punctuation-bracket">(</span><span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -function">length</span></span> <span class="oxocarbon_haskell -variable"><span class="oxocarbon_haskell -function"><span class="oxocarbon_haskell -variable">values</span></span></span><span class="oxocarbon_haskell -punctuation-bracket">)</span>
<span class="oxocarbon_haskell SignColumn">  </span><span class="oxocarbon_haskell LineNr"> 22 </span>

</pre>
</section>