<script> import "$lib/vihtml/rose-pine-main_haskell.css" </script>

<section class="rose-pine-main_haskell boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr">  1 </span><span class="rose-pine-main_haskell SpecialComment">&#123;-# LANGUAGE DeriveFunctor, DeriveFoldable, DeriveTraversable #-&#125;</span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr">  2 </span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr">  3 </span><span class="rose-pine-main_haskell Include">import</span><span class="rose-pine-main_haskell hsImportGroup"> </span><span class="rose-pine-main_haskell hsImportModuleName">Data.Map</span><span class="rose-pine-main_haskell hsImportGroup"> </span><span class="rose-pine-main_haskell hsDelimiter">(</span><span class="rose-pine-main_haskell ConId">Map</span><span class="rose-pine-main_haskell hsDelimiter">,</span><span class="rose-pine-main_haskell hsImportList"> </span><span class="rose-pine-main_haskell VarId">fromList</span><span class="rose-pine-main_haskell hsDelimiter">,</span><span class="rose-pine-main_haskell hsImportList"> </span><span class="rose-pine-main_haskell VarId">toList</span><span class="rose-pine-main_haskell hsDelimiter">)</span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr">  4 </span><span class="rose-pine-main_haskell Include">import</span><span class="rose-pine-main_haskell hsImportGroup"> </span><span class="rose-pine-main_haskell hsImportModuleName">Data.List</span><span class="rose-pine-main_haskell hsImportGroup"> </span><span class="rose-pine-main_haskell hsDelimiter">(</span><span class="rose-pine-main_haskell VarId">foldl'</span><span class="rose-pine-main_haskell hsDelimiter">)</span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr">  5 </span><span class="rose-pine-main_haskell Include">import</span><span class="rose-pine-main_haskell hsImportGroup"> </span><span class="rose-pine-main_haskell hsImportModuleName">Text.Printf</span><span class="rose-pine-main_haskell hsImportGroup"> </span><span class="rose-pine-main_haskell hsDelimiter">(</span><span class="rose-pine-main_haskell VarId">printf</span><span class="rose-pine-main_haskell hsDelimiter">)</span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr">  6 </span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr">  7 </span><span class="rose-pine-main_haskell Comment">-- Define a data type to hold complex data</span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr">  8 </span><span class="rose-pine-main_haskell Structure">data</span> <span class="rose-pine-main_haskell ConId">ComplexData</span> <span class="rose-pine-main_haskell Operator">=</span> <span class="rose-pine-main_haskell ConId">ComplexData</span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr">  9 </span><span class="rose-pine-main_haskell -ibl-indent-char-1">│</span><span class="rose-pine-main_haskell -ibl-whitespace-char-1"> </span><span class="rose-pine-main_haskell hsDelimiter">&#123;</span> <span class="rose-pine-main_haskell VarId">id</span> <span class="rose-pine-main_haskell Operator">::</span> <span class="rose-pine-main_haskell ConId">Int</span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr"> 10 </span><span class="rose-pine-main_haskell -ibl-indent-char-1">│</span><span class="rose-pine-main_haskell -ibl-whitespace-char-1"> </span><span class="rose-pine-main_haskell hsDelimiter">,</span> <span class="rose-pine-main_haskell VarId">name</span> <span class="rose-pine-main_haskell Operator">::</span> <span class="rose-pine-main_haskell ConId">String</span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr"> 11 </span><span class="rose-pine-main_haskell -ibl-indent-char-1">│</span><span class="rose-pine-main_haskell -ibl-whitespace-char-1"> </span><span class="rose-pine-main_haskell hsDelimiter">,</span> <span class="rose-pine-main_haskell VarId">values</span> <span class="rose-pine-main_haskell Operator">::</span> <span class="rose-pine-main_haskell hsDelimiter">[</span><span class="rose-pine-main_haskell ConId">Int</span><span class="rose-pine-main_haskell hsDelimiter">]</span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr"> 12 </span><span class="rose-pine-main_haskell -ibl-indent-char-1">│</span><span class="rose-pine-main_haskell -ibl-whitespace-char-1"> </span><span class="rose-pine-main_haskell hsDelimiter">&#125;</span> <span class="rose-pine-main_haskell Structure">deriving</span> <span class="rose-pine-main_haskell hsDelimiter">(</span><span class="rose-pine-main_haskell ConId">Show</span><span class="rose-pine-main_haskell hsDelimiter">)</span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr"> 13 </span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr"> 14 </span><span class="rose-pine-main_haskell Comment">-- Create a new instance of ComplexData</span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr"> 15 </span><span class="rose-pine-main_haskell VarId">newComplexData</span> <span class="rose-pine-main_haskell Operator">::</span> <span class="rose-pine-main_haskell ConId">Int</span> <span class="rose-pine-main_haskell Operator">-&gt;</span> <span class="rose-pine-main_haskell ConId">String</span> <span class="rose-pine-main_haskell Operator">-&gt;</span> <span class="rose-pine-main_haskell ConId">ComplexData</span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr"> 16 </span><span class="rose-pine-main_haskell VarId">newComplexData</span> <span class="rose-pine-main_haskell VarId">id</span> <span class="rose-pine-main_haskell VarId">name</span> <span class="rose-pine-main_haskell Operator">=</span> <span class="rose-pine-main_haskell ConId">ComplexData</span> <span class="rose-pine-main_haskell VarId">id</span> <span class="rose-pine-main_haskell VarId">name</span> <span class="rose-pine-main_haskell hsDelimiter">[</span><span class="rose-pine-main_haskell VarId">id</span> <span class="rose-pine-main_haskell Operator">*</span> <span class="rose-pine-main_haskell Number">10</span><span class="rose-pine-main_haskell hsDelimiter">,</span> <span class="rose-pine-main_haskell VarId">id</span> <span class="rose-pine-main_haskell Operator">*</span> <span class="rose-pine-main_haskell Number">20</span><span class="rose-pine-main_haskell hsDelimiter">,</span> <span class="rose-pine-main_haskell VarId">id</span> <span class="rose-pine-main_haskell Operator">*</span> <span class="rose-pine-main_haskell Number">30</span><span class="rose-pine-main_haskell hsDelimiter">]</span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr"> 17 </span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr"> 18 </span><span class="rose-pine-main_haskell Comment">-- Calculate the average of values in ComplexData</span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr"> 19 </span><span class="rose-pine-main_haskell VarId">calculate</span> <span class="rose-pine-main_haskell Operator">::</span> <span class="rose-pine-main_haskell ConId">ComplexData</span> <span class="rose-pine-main_haskell Operator">-&gt;</span> <span class="rose-pine-main_haskell ConId">Double</span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr"> 20 </span><span class="rose-pine-main_haskell VarId">calculate</span> <span class="rose-pine-main_haskell hsDelimiter">(</span><span class="rose-pine-main_haskell ConId">ComplexData</span> _ _ <span class="rose-pine-main_haskell VarId">values</span><span class="rose-pine-main_haskell hsDelimiter">)</span> <span class="rose-pine-main_haskell Operator">=</span> 
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr"> 21 </span><span class="rose-pine-main_haskell -ibl-indent-char-1">│</span><span class="rose-pine-main_haskell -ibl-whitespace-char-1"> </span><span class="rose-pine-main_haskell VarId">fromIntegral</span> <span class="rose-pine-main_haskell hsDelimiter">(</span><span class="rose-pine-main_haskell VarId">sum</span> <span class="rose-pine-main_haskell VarId">values</span><span class="rose-pine-main_haskell hsDelimiter">)</span> <span class="rose-pine-main_haskell Operator">/</span> <span class="rose-pine-main_haskell VarId">fromIntegral</span> <span class="rose-pine-main_haskell hsDelimiter">(</span><span class="rose-pine-main_haskell VarId">length</span> <span class="rose-pine-main_haskell VarId">values</span><span class="rose-pine-main_haskell hsDelimiter">)</span>
<span class="rose-pine-main_haskell SignColumn">  </span><span class="rose-pine-main_haskell LineNr"> 22 </span>

</pre>
</section>