<script> import "$lib/vihtml/rose-pine-moon_haskell.css" </script>

<section class="rose-pine-moon_haskell boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr">  1 </span><span class="rose-pine-moon_haskell -keyword-directive">&#123;-# LANGUAGE DeriveFunctor, DeriveFoldable, DeriveTraversable #-&#125;</span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr">  2 </span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr">  3 </span><span class="rose-pine-moon_haskell -keyword-import">import</span> <span class="rose-pine-moon_haskell -module">Data</span><span class="rose-pine-moon_haskell Operator">.</span><span class="rose-pine-moon_haskell -module">Map</span> <span class="rose-pine-moon_haskell -punctuation-bracket">(</span><span class="rose-pine-moon_haskell -type">Map</span><span class="rose-pine-moon_haskell -punctuation-delimiter">,</span> <span class="rose-pine-moon_haskell -variable">fromList</span><span class="rose-pine-moon_haskell -punctuation-delimiter">,</span> <span class="rose-pine-moon_haskell -variable">toList</span><span class="rose-pine-moon_haskell -punctuation-bracket">)</span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr">  4 </span><span class="rose-pine-moon_haskell -keyword-import">import</span> <span class="rose-pine-moon_haskell -module">Data</span><span class="rose-pine-moon_haskell Operator">.</span><span class="rose-pine-moon_haskell -module">List</span> <span class="rose-pine-moon_haskell -punctuation-bracket">(</span><span class="rose-pine-moon_haskell -variable">foldl'</span><span class="rose-pine-moon_haskell -punctuation-bracket">)</span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr">  5 </span><span class="rose-pine-moon_haskell -keyword-import">import</span> <span class="rose-pine-moon_haskell -module">Text</span><span class="rose-pine-moon_haskell Operator">.</span><span class="rose-pine-moon_haskell -module">Printf</span> <span class="rose-pine-moon_haskell -punctuation-bracket">(</span><span class="rose-pine-moon_haskell -variable">printf</span><span class="rose-pine-moon_haskell -punctuation-bracket">)</span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr">  6 </span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr">  7 </span><span class="rose-pine-moon_haskell Comment"><span class="rose-pine-moon_haskell -spell">-- Define a data type to hold complex data</span></span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr">  8 </span><span class="rose-pine-moon_haskell Keyword">data</span> <span class="rose-pine-moon_haskell -type">ComplexData</span> <span class="rose-pine-moon_haskell Operator">=</span> <span class="rose-pine-moon_haskell -constructor">ComplexData</span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr">  9 </span><span class="rose-pine-moon_haskell -ibl-indent-char-1">│</span><span class="rose-pine-moon_haskell -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_haskell -punctuation-bracket">&#123;</span> <span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -variable-member">id</span></span> <span class="rose-pine-moon_haskell Operator">::</span> <span class="rose-pine-moon_haskell -type">Int</span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr"> 10 </span><span class="rose-pine-moon_haskell -ibl-indent-char-1">│</span><span class="rose-pine-moon_haskell -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_haskell -punctuation-delimiter">,</span> <span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -variable-member">name</span></span> <span class="rose-pine-moon_haskell Operator">::</span> <span class="rose-pine-moon_haskell -type">String</span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr"> 11 </span><span class="rose-pine-moon_haskell -ibl-indent-char-1">│</span><span class="rose-pine-moon_haskell -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_haskell -punctuation-delimiter">,</span> <span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -variable-member">values</span></span> <span class="rose-pine-moon_haskell Operator">::</span> <span class="rose-pine-moon_haskell -punctuation-bracket"><span class="rose-pine-moon_haskell -type">[</span></span><span class="rose-pine-moon_haskell -type">Int</span><span class="rose-pine-moon_haskell -punctuation-bracket"><span class="rose-pine-moon_haskell -type">]</span></span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr"> 12 </span><span class="rose-pine-moon_haskell -ibl-indent-char-1">│</span><span class="rose-pine-moon_haskell -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_haskell -punctuation-bracket">&#125;</span> <span class="rose-pine-moon_haskell Keyword">deriving</span> <span class="rose-pine-moon_haskell -punctuation-bracket">(</span><span class="rose-pine-moon_haskell -type">Show</span><span class="rose-pine-moon_haskell -punctuation-bracket">)</span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr"> 13 </span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr"> 14 </span><span class="rose-pine-moon_haskell Comment"><span class="rose-pine-moon_haskell -spell">-- Create a new instance of ComplexData</span></span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr"> 15 </span><span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -function"><span class="rose-pine-moon_haskell -function"><span class="rose-pine-moon_haskell -function">newComplexData</span></span></span></span><span class="rose-pine-moon_haskell -function"> <span class="rose-pine-moon_haskell Operator">::</span> <span class="rose-pine-moon_haskell -type">Int</span> <span class="rose-pine-moon_haskell Operator">-&gt;</span> <span class="rose-pine-moon_haskell -type">String</span> <span class="rose-pine-moon_haskell Operator">-&gt;</span> <span class="rose-pine-moon_haskell -type">ComplexData</span></span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr"> 16 </span><span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -function"><span class="rose-pine-moon_haskell -function">newComplexData</span></span></span> <span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -variable-parameter">id</span></span> <span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -variable-parameter">name</span></span> <span class="rose-pine-moon_haskell Operator">=</span> <span class="rose-pine-moon_haskell -constructor">ComplexData</span> <span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -function"><span class="rose-pine-moon_haskell -variable">id</span></span></span> <span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -function"><span class="rose-pine-moon_haskell -variable">name</span></span></span> <span class="rose-pine-moon_haskell -punctuation-bracket">[</span><span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -function"><span class="rose-pine-moon_haskell -variable">id</span></span></span> <span class="rose-pine-moon_haskell Operator">*</span> <span class="rose-pine-moon_haskell Number">10</span><span class="rose-pine-moon_haskell -punctuation-delimiter">,</span> <span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -function"><span class="rose-pine-moon_haskell -variable">id</span></span></span> <span class="rose-pine-moon_haskell Operator">*</span> <span class="rose-pine-moon_haskell Number">20</span><span class="rose-pine-moon_haskell -punctuation-delimiter">,</span> <span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -function"><span class="rose-pine-moon_haskell -variable">id</span></span></span> <span class="rose-pine-moon_haskell Operator">*</span> <span class="rose-pine-moon_haskell Number">30</span><span class="rose-pine-moon_haskell -punctuation-bracket">]</span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr"> 17 </span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr"> 18 </span><span class="rose-pine-moon_haskell Comment"><span class="rose-pine-moon_haskell -spell">-- Calculate the average of values in ComplexData</span></span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr"> 19 </span><span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -function"><span class="rose-pine-moon_haskell -function"><span class="rose-pine-moon_haskell -function">calculate</span></span></span></span><span class="rose-pine-moon_haskell -function"> <span class="rose-pine-moon_haskell Operator">::</span> <span class="rose-pine-moon_haskell -type">ComplexData</span> <span class="rose-pine-moon_haskell Operator">-&gt;</span> <span class="rose-pine-moon_haskell -type">Double</span></span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr"> 20 </span><span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -function"><span class="rose-pine-moon_haskell -function">calculate</span></span></span> <span class="rose-pine-moon_haskell -variable-parameter"><span class="rose-pine-moon_haskell -punctuation-bracket">(</span><span class="rose-pine-moon_haskell -constructor">ComplexData</span> <span class="rose-pine-moon_haskell Character">_</span> <span class="rose-pine-moon_haskell Character">_</span> <span class="rose-pine-moon_haskell -variable">values</span><span class="rose-pine-moon_haskell -punctuation-bracket">)</span></span> <span class="rose-pine-moon_haskell Operator">=</span> 
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr"> 21 </span><span class="rose-pine-moon_haskell -ibl-indent-char-1">│</span><span class="rose-pine-moon_haskell -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -function">fromIntegral</span></span> <span class="rose-pine-moon_haskell -punctuation-bracket">(</span><span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -function">sum</span></span> <span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -function"><span class="rose-pine-moon_haskell -variable">values</span></span></span><span class="rose-pine-moon_haskell -punctuation-bracket">)</span> <span class="rose-pine-moon_haskell Operator">/</span> <span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -function">fromIntegral</span></span> <span class="rose-pine-moon_haskell -punctuation-bracket">(</span><span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -function">length</span></span> <span class="rose-pine-moon_haskell -variable"><span class="rose-pine-moon_haskell -function"><span class="rose-pine-moon_haskell -variable">values</span></span></span><span class="rose-pine-moon_haskell -punctuation-bracket">)</span>
<span class="rose-pine-moon_haskell SignColumn">  </span><span class="rose-pine-moon_haskell LineNr"> 22 </span>

</pre>
</section>