<script> import "$lib/vihtml/rose-pine-moon_elixir.css" </script>

<section class="rose-pine-moon_elixir boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr">  1 </span>defmodule DataProcessor do
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr">  2 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>defmodule ComplexData do
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr">  3 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>defstruct [:id, :name, :values]
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr">  4 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span>
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr">  5 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>def new(id, name) do
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr">  6 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>values = Enum.map([id * 10, id * 20, id * 30], &amp;(&amp;1))
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr">  7 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>%ComplexData&#123;id: id, name: name, values: values&#125;
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr">  8 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>end
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr">  9 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span>
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr"> 10 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>def calculate(%ComplexData&#123;values: values&#125;) do
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr"> 11 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>Enum.sum(values) / length(values)
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr"> 12 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>end
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr"> 13 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>end
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr"> 14 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span>
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr"> 15 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>def generate_data(count) do
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr"> 16 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>1..count
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr"> 17 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>|&gt; Enum.map(fn id -&gt; &#123;id, ComplexData.new(id, &quot;Item #&#123;id&#125;&quot;)&#125; end)
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr"> 18 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>|&gt; Enum.into(%&#123;&#125;)
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr"> 19 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>end
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr"> 20 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span>
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr"> 21 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>def save_to_file(filename, data) do
<span class="rose-pine-moon_elixir SignColumn">  </span><span class="rose-pine-moon_elixir LineNr"> 22 </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span><span class="rose-pine-moon_elixir -ibl-indent-char-1">│</span><span class="rose-pine-moon_elixir -ibl-whitespace-char-1"> </span>File.write!(filename, Enum.map(data, fn &#123;_, item&#125; -&gt;

</pre>
</section>