<script> import "$lib/vihtml/rosebones_c.css" </script>

<section class="rosebones_c boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr">  1 </span><span class="rosebones_c Statement">#include</span> <span class="rosebones_c Constant">&lt;stdio.h&gt;</span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr">  2 </span><span class="rosebones_c Statement">#include</span> <span class="rosebones_c Constant">&lt;stdlib.h&gt;</span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr">  3 </span><span class="rosebones_c Statement">#include</span> <span class="rosebones_c Constant">&lt;stdbool.h&gt;</span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr">  4 </span><span class="rosebones_c Statement">#include</span> <span class="rosebones_c Constant">&lt;math.h&gt;</span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr">  5 </span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr">  6 </span><span class="rosebones_c Statement">#define</span> <span class="rosebones_c Identifier"><span class="rosebones_c -constant"><span class="rosebones_c Constant">PI</span></span></span> <span class="rosebones_c Identifier"><span class="rosebones_c Number">3.14159</span></span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr">  7 </span><span class="rosebones_c Statement">#define</span> <span class="rosebones_c Identifier"><span class="rosebones_c -constant"><span class="rosebones_c Statement">SQUARE</span></span></span><span class="rosebones_c Delimiter">(</span><span class="rosebones_c Identifier"><span class="rosebones_c Identifier">x</span></span><span class="rosebones_c Delimiter">)</span> <span class="rosebones_c Delimiter">(</span><span class="rosebones_c Delimiter">(</span><span class="rosebones_c Identifier">x</span><span class="rosebones_c Delimiter">)</span> <span class="rosebones_c Statement">*</span> <span class="rosebones_c Delimiter">(</span><span class="rosebones_c Identifier">x</span><span class="rosebones_c Delimiter">)</span><span class="rosebones_c Delimiter">)</span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr">  8 </span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr">  9 </span><span class="rosebones_c Statement">typedef</span> <span class="rosebones_c Statement">struct</span> <span class="rosebones_c Delimiter">&#123;</span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr"> 10 </span><span class="rosebones_c -ibl-indent-char-1">│</span><span class="rosebones_c NonText"> </span><span class="rosebones_c NonText"> </span><span class="rosebones_c NonText"> </span><span class="rosebones_c Type">double</span> <span class="rosebones_c Identifier">x</span><span class="rosebones_c Delimiter">,</span> <span class="rosebones_c Identifier">y</span><span class="rosebones_c Delimiter">;</span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr"> 11 </span><span class="rosebones_c -ibl-indent-char-1">│</span><span class="rosebones_c NonText"> </span><span class="rosebones_c NonText"> </span><span class="rosebones_c NonText"> </span><span class="rosebones_c Type">double</span> <span class="rosebones_c Identifier">radius</span><span class="rosebones_c Delimiter">;</span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr"> 12 </span><span class="rosebones_c Delimiter">&#125;</span> <span class="rosebones_c Type"><span class="rosebones_c Type">Circle</span></span><span class="rosebones_c Delimiter">;</span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr"> 13 </span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr"> 14 </span><span class="rosebones_c Type">double</span> <span class="rosebones_c Identifier"><span class="rosebones_c Function">calculate_area</span></span><span class="rosebones_c Delimiter">(</span><span class="rosebones_c Statement">const</span> <span class="rosebones_c Type">Circle</span> <span class="rosebones_c Identifier"><span class="rosebones_c Statement">*</span><span class="rosebones_c Identifier">c</span></span><span class="rosebones_c Delimiter">)</span> <span class="rosebones_c Delimiter">&#123;</span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr"> 15 </span><span class="rosebones_c -ibl-indent-char-1">│</span><span class="rosebones_c NonText"> </span><span class="rosebones_c NonText"> </span><span class="rosebones_c NonText"> </span><span class="rosebones_c Statement">return</span> <span class="rosebones_c Identifier"><span class="rosebones_c -constant">PI</span></span> <span class="rosebones_c Statement">*</span> <span class="rosebones_c Identifier"><span class="rosebones_c -constant"><span class="rosebones_c Function">SQUARE</span></span></span><span class="rosebones_c Delimiter">(</span><span class="rosebones_c -_parent"><span class="rosebones_c Identifier">c</span><span class="rosebones_c Statement">-&gt;</span><span class="rosebones_c Identifier">radius</span></span><span class="rosebones_c Delimiter">)</span><span class="rosebones_c Delimiter">;</span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr"> 16 </span><span class="rosebones_c Delimiter">&#125;</span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr"> 17 </span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr"> 18 </span><span class="rosebones_c Type">void</span> <span class="rosebones_c Identifier"><span class="rosebones_c Function">print_array</span></span><span class="rosebones_c Delimiter">(</span><span class="rosebones_c Statement">const</span> <span class="rosebones_c Type">char</span> <span class="rosebones_c Identifier"><span class="rosebones_c Statement">*</span><span class="rosebones_c Identifier">msg</span></span><span class="rosebones_c Delimiter">,</span> <span class="rosebones_c Type">int</span> <span class="rosebones_c Identifier"><span class="rosebones_c Statement">*</span><span class="rosebones_c Identifier">arr</span></span><span class="rosebones_c Delimiter">,</span> <span class="rosebones_c Type">size_t</span> <span class="rosebones_c Identifier"><span class="rosebones_c Identifier">size</span></span><span class="rosebones_c Delimiter">)</span> <span class="rosebones_c Delimiter">&#123;</span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr"> 19 </span><span class="rosebones_c -ibl-indent-char-1">│</span><span class="rosebones_c NonText"> </span><span class="rosebones_c NonText"> </span><span class="rosebones_c NonText"> </span><span class="rosebones_c Identifier"><span class="rosebones_c Function">printf</span></span><span class="rosebones_c Delimiter">(</span><span class="rosebones_c Constant">&quot;%s: &quot;</span><span class="rosebones_c Delimiter">,</span> <span class="rosebones_c Identifier">msg</span><span class="rosebones_c Delimiter">)</span><span class="rosebones_c Delimiter">;</span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr"> 20 </span><span class="rosebones_c -ibl-indent-char-1">│</span><span class="rosebones_c NonText"> </span><span class="rosebones_c NonText"> </span><span class="rosebones_c NonText"> </span><span class="rosebones_c Statement">for</span> <span class="rosebones_c Delimiter">(</span><span class="rosebones_c Type">size_t</span> <span class="rosebones_c Identifier">i</span> <span class="rosebones_c Statement">=</span> <span class="rosebones_c Number">0</span><span class="rosebones_c Delimiter">;</span> <span class="rosebones_c Identifier">i</span> <span class="rosebones_c Statement">&lt;</span> <span class="rosebones_c Identifier">size</span><span class="rosebones_c Delimiter">;</span> <span class="rosebones_c Identifier">i</span><span class="rosebones_c Statement">++</span><span class="rosebones_c Delimiter">)</span> <span class="rosebones_c Identifier"><span class="rosebones_c Function">printf</span></span><span class="rosebones_c Delimiter">(</span><span class="rosebones_c Constant">&quot;%d &quot;</span><span class="rosebones_c Delimiter">,</span> <span class="rosebones_c Identifier">arr</span><span class="rosebones_c Delimiter">[</span><span class="rosebones_c Identifier">i</span><span class="rosebones_c Delimiter">]</span><span class="rosebones_c Delimiter">)</span><span class="rosebones_c Delimiter">;</span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr"> 21 </span><span class="rosebones_c -ibl-indent-char-1">│</span><span class="rosebones_c NonText"> </span><span class="rosebones_c NonText"> </span><span class="rosebones_c NonText"> </span><span class="rosebones_c Identifier"><span class="rosebones_c Function">printf</span></span><span class="rosebones_c Delimiter">(</span><span class="rosebones_c Constant">&quot;<span class="rosebones_c Special">\n</span>&quot;</span><span class="rosebones_c Delimiter">)</span><span class="rosebones_c Delimiter">;</span>
<span class="rosebones_c LineNr">  </span><span class="rosebones_c LineNr"> 22 </span><span class="rosebones_c Delimiter">&#125;</span>

</pre>
</section>