<script> import "$lib/vihtml/rxyhn_c.css" </script>

<section class="rxyhn_c boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr">  1 </span><span class="rxyhn_c Include">#include</span> <span class="rxyhn_c -string">&lt;stdio.h&gt;</span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr">  2 </span><span class="rxyhn_c Include">#include</span> <span class="rxyhn_c -string">&lt;stdlib.h&gt;</span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr">  3 </span><span class="rxyhn_c Include">#include</span> <span class="rxyhn_c -string">&lt;stdbool.h&gt;</span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr">  4 </span><span class="rxyhn_c Include">#include</span> <span class="rxyhn_c -string">&lt;math.h&gt;</span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr">  5 </span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr">  6 </span><span class="rxyhn_c -keyword-directive-define">#define</span> <span class="rxyhn_c -variable"><span class="rxyhn_c -constant"><span class="rxyhn_c -constant-macro">PI</span></span></span> <span class="rxyhn_c -variable"><span class="rxyhn_c -number">3.14159</span></span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr">  7 </span><span class="rxyhn_c -keyword-directive-define">#define</span> <span class="rxyhn_c -variable"><span class="rxyhn_c -constant"><span class="rxyhn_c -function-macro">SQUARE</span></span></span><span class="rxyhn_c -punctuation-bracket">(</span><span class="rxyhn_c -variable"><span class="rxyhn_c -variable-parameter">x</span></span><span class="rxyhn_c -punctuation-bracket">)</span> <span class="rxyhn_c -punctuation-bracket">(</span><span class="rxyhn_c -punctuation-bracket">(</span><span class="rxyhn_c -variable">x</span><span class="rxyhn_c -punctuation-bracket">)</span> <span class="rxyhn_c -operator">*</span> <span class="rxyhn_c -punctuation-bracket">(</span><span class="rxyhn_c -variable">x</span><span class="rxyhn_c -punctuation-bracket">)</span><span class="rxyhn_c -punctuation-bracket">)</span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr">  8 </span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr">  9 </span><span class="rxyhn_c -keyword">typedef</span> <span class="rxyhn_c -keyword">struct</span> <span class="rxyhn_c -punctuation-bracket">&#123;</span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr"> 10 </span><span class="rxyhn_c NonText">│</span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c -type-builtin">double</span> <span class="rxyhn_c -property">x</span><span class="rxyhn_c -punctuation-delimiter">,</span> <span class="rxyhn_c -property">y</span><span class="rxyhn_c -punctuation-delimiter">;</span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr"> 11 </span><span class="rxyhn_c NonText">│</span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c -type-builtin">double</span> <span class="rxyhn_c -property">radius</span><span class="rxyhn_c -punctuation-delimiter">;</span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr"> 12 </span><span class="rxyhn_c -punctuation-bracket">&#125;</span> <span class="rxyhn_c Type"><span class="rxyhn_c Type">Circle</span></span><span class="rxyhn_c -punctuation-delimiter">;</span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr"> 13 </span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr"> 14 </span><span class="rxyhn_c -type-builtin">double</span> <span class="rxyhn_c -variable"><span class="rxyhn_c -function">calculate_area</span></span><span class="rxyhn_c -punctuation-bracket">(</span><span class="rxyhn_c -keyword">const</span> <span class="rxyhn_c Type">Circle</span> <span class="rxyhn_c -variable-parameter"><span class="rxyhn_c -operator">*</span><span class="rxyhn_c -variable">c</span></span><span class="rxyhn_c -punctuation-bracket">)</span> <span class="rxyhn_c -punctuation-bracket">&#123;</span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr"> 15 </span><span class="rxyhn_c NonText">│</span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c -keyword-return">return</span> <span class="rxyhn_c -variable"><span class="rxyhn_c -constant">PI</span></span> <span class="rxyhn_c -operator">*</span> <span class="rxyhn_c -variable"><span class="rxyhn_c -constant"><span class="rxyhn_c -function-call">SQUARE</span></span></span><span class="rxyhn_c -punctuation-bracket">(</span><span class="rxyhn_c -_parent"><span class="rxyhn_c -variable">c</span><span class="rxyhn_c -operator">-&gt;</span><span class="rxyhn_c -property">radius</span></span><span class="rxyhn_c -punctuation-bracket">)</span><span class="rxyhn_c -punctuation-delimiter">;</span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr"> 16 </span><span class="rxyhn_c -punctuation-bracket">&#125;</span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr"> 17 </span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr"> 18 </span><span class="rxyhn_c -type-builtin">void</span> <span class="rxyhn_c -variable"><span class="rxyhn_c -function">print_array</span></span><span class="rxyhn_c -punctuation-bracket">(</span><span class="rxyhn_c -keyword">const</span> <span class="rxyhn_c -type-builtin">char</span> <span class="rxyhn_c -variable-parameter"><span class="rxyhn_c -operator">*</span><span class="rxyhn_c -variable">msg</span></span><span class="rxyhn_c -punctuation-delimiter">,</span> <span class="rxyhn_c -type-builtin">int</span> <span class="rxyhn_c -variable-parameter"><span class="rxyhn_c -operator">*</span><span class="rxyhn_c -variable">arr</span></span><span class="rxyhn_c -punctuation-delimiter">,</span> <span class="rxyhn_c -type-builtin">size_t</span> <span class="rxyhn_c -variable"><span class="rxyhn_c -variable-parameter">size</span></span><span class="rxyhn_c -punctuation-bracket">)</span> <span class="rxyhn_c -punctuation-bracket">&#123;</span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr"> 19 </span><span class="rxyhn_c NonText">│</span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c -variable"><span class="rxyhn_c -function-call">printf</span></span><span class="rxyhn_c -punctuation-bracket">(</span><span class="rxyhn_c -string">&quot;%s: &quot;</span><span class="rxyhn_c -punctuation-delimiter">,</span> <span class="rxyhn_c -variable">msg</span><span class="rxyhn_c -punctuation-bracket">)</span><span class="rxyhn_c -punctuation-delimiter">;</span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr"> 20 </span><span class="rxyhn_c NonText">│</span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c -keyword-repeat">for</span> <span class="rxyhn_c -punctuation-bracket">(</span><span class="rxyhn_c -type-builtin">size_t</span> <span class="rxyhn_c -variable">i</span> <span class="rxyhn_c -operator">=</span> <span class="rxyhn_c -number">0</span><span class="rxyhn_c -punctuation-delimiter">;</span> <span class="rxyhn_c -variable">i</span> <span class="rxyhn_c -operator">&lt;</span> <span class="rxyhn_c -variable">size</span><span class="rxyhn_c -punctuation-delimiter">;</span> <span class="rxyhn_c -variable">i</span><span class="rxyhn_c -operator">++</span><span class="rxyhn_c -punctuation-bracket">)</span> <span class="rxyhn_c -variable"><span class="rxyhn_c -function-call">printf</span></span><span class="rxyhn_c -punctuation-bracket">(</span><span class="rxyhn_c -string">&quot;%d &quot;</span><span class="rxyhn_c -punctuation-delimiter">,</span> <span class="rxyhn_c -variable">arr</span><span class="rxyhn_c -punctuation-bracket">[</span><span class="rxyhn_c -variable">i</span><span class="rxyhn_c -punctuation-bracket">]</span><span class="rxyhn_c -punctuation-bracket">)</span><span class="rxyhn_c -punctuation-delimiter">;</span>
<span class="rxyhn_c SignColumn">  </span><span class="rxyhn_c LineNr"> 21 </span><span class="rxyhn_c NonText">│</span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c NonText"> </span><span class="rxyhn_c -variable"><span class="rxyhn_c -function-call">printf</span></span><span class="rxyhn_c -punctuation-bracket">(</span><span class="rxyhn_c -string">&quot;<span class="rxyhn_c -string-escape">\n</span>&quot;</span><span class="rxyhn_c -punctuation-bracket">)</span><span class="rxyhn_c -punctuation-delimiter">;</span>

</pre>
</section>