<script> import "$lib/vihtml/tokyobones_haskell.css" </script>

<section class="tokyobones_haskell boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr">  1 </span><span class="tokyobones_haskell PreProc">&#123;-# LANGUAGE DeriveFunctor, DeriveFoldable, DeriveTraversable #-&#125;</span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr">  2 </span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr">  3 </span><span class="tokyobones_haskell PreProc">import</span> <span class="tokyobones_haskell Constant">Data</span><span class="tokyobones_haskell Statement">.</span><span class="tokyobones_haskell Constant">Map</span> <span class="tokyobones_haskell Delimiter">(</span><span class="tokyobones_haskell Type">Map</span><span class="tokyobones_haskell Delimiter">,</span> <span class="tokyobones_haskell Identifier">fromList</span><span class="tokyobones_haskell Delimiter">,</span> <span class="tokyobones_haskell Identifier">toList</span><span class="tokyobones_haskell Delimiter">)</span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr">  4 </span><span class="tokyobones_haskell PreProc">import</span> <span class="tokyobones_haskell Constant">Data</span><span class="tokyobones_haskell Statement">.</span><span class="tokyobones_haskell Constant">List</span> <span class="tokyobones_haskell Delimiter">(</span><span class="tokyobones_haskell Identifier">foldl'</span><span class="tokyobones_haskell Delimiter">)</span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr">  5 </span><span class="tokyobones_haskell PreProc">import</span> <span class="tokyobones_haskell Constant">Text</span><span class="tokyobones_haskell Statement">.</span><span class="tokyobones_haskell Constant">Printf</span> <span class="tokyobones_haskell Delimiter">(</span><span class="tokyobones_haskell Identifier">printf</span><span class="tokyobones_haskell Delimiter">)</span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr">  6 </span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr">  7 </span><span class="tokyobones_haskell Comment"><span class="tokyobones_haskell -spell">-- Define a data type to hold complex data</span></span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr">  8 </span><span class="tokyobones_haskell Statement">data</span> <span class="tokyobones_haskell Type">ComplexData</span> <span class="tokyobones_haskell Statement">=</span> <span class="tokyobones_haskell Special">ComplexData</span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr">  9 </span><span class="tokyobones_haskell -ibl-indent-char-1">│</span><span class="tokyobones_haskell NonText"> </span><span class="tokyobones_haskell Delimiter">&#123;</span> <span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Identifier">id</span></span> <span class="tokyobones_haskell Statement">::</span> <span class="tokyobones_haskell Type">Int</span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr"> 10 </span><span class="tokyobones_haskell -ibl-indent-char-1">│</span><span class="tokyobones_haskell NonText"> </span><span class="tokyobones_haskell Delimiter">,</span> <span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Identifier">name</span></span> <span class="tokyobones_haskell Statement">::</span> <span class="tokyobones_haskell Type">String</span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr"> 11 </span><span class="tokyobones_haskell -ibl-indent-char-1">│</span><span class="tokyobones_haskell NonText"> </span><span class="tokyobones_haskell Delimiter">,</span> <span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Identifier">values</span></span> <span class="tokyobones_haskell Statement">::</span> <span class="tokyobones_haskell Delimiter"><span class="tokyobones_haskell Type">[</span></span><span class="tokyobones_haskell Type">Int</span><span class="tokyobones_haskell Delimiter"><span class="tokyobones_haskell Type">]</span></span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr"> 12 </span><span class="tokyobones_haskell -ibl-indent-char-1">│</span><span class="tokyobones_haskell NonText"> </span><span class="tokyobones_haskell Delimiter">&#125;</span> <span class="tokyobones_haskell Statement">deriving</span> <span class="tokyobones_haskell Delimiter">(</span><span class="tokyobones_haskell Type">Show</span><span class="tokyobones_haskell Delimiter">)</span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr"> 13 </span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr"> 14 </span><span class="tokyobones_haskell Comment"><span class="tokyobones_haskell -spell">-- Create a new instance of ComplexData</span></span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr"> 15 </span><span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Function"><span class="tokyobones_haskell Function"><span class="tokyobones_haskell Function">newComplexData</span></span></span></span><span class="tokyobones_haskell Function"> <span class="tokyobones_haskell Statement">::</span> <span class="tokyobones_haskell Type">Int</span> <span class="tokyobones_haskell Statement">-&gt;</span> <span class="tokyobones_haskell Type">String</span> <span class="tokyobones_haskell Statement">-&gt;</span> <span class="tokyobones_haskell Type">ComplexData</span></span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr"> 16 </span><span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Function"><span class="tokyobones_haskell Function">newComplexData</span></span></span> <span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Identifier">id</span></span> <span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Identifier">name</span></span> <span class="tokyobones_haskell Statement">=</span> <span class="tokyobones_haskell Special">ComplexData</span> <span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Function"><span class="tokyobones_haskell Identifier">id</span></span></span> <span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Function"><span class="tokyobones_haskell Identifier">name</span></span></span> <span class="tokyobones_haskell Delimiter">[</span><span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Function"><span class="tokyobones_haskell Identifier">id</span></span></span> <span class="tokyobones_haskell Statement">*</span> <span class="tokyobones_haskell Number">10</span><span class="tokyobones_haskell Delimiter">,</span> <span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Function"><span class="tokyobones_haskell Identifier">id</span></span></span> <span class="tokyobones_haskell Statement">*</span> <span class="tokyobones_haskell Number">20</span><span class="tokyobones_haskell Delimiter">,</span> <span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Function"><span class="tokyobones_haskell Identifier">id</span></span></span> <span class="tokyobones_haskell Statement">*</span> <span class="tokyobones_haskell Number">30</span><span class="tokyobones_haskell Delimiter">]</span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr"> 17 </span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr"> 18 </span><span class="tokyobones_haskell Comment"><span class="tokyobones_haskell -spell">-- Calculate the average of values in ComplexData</span></span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr"> 19 </span><span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Function"><span class="tokyobones_haskell Function"><span class="tokyobones_haskell Function">calculate</span></span></span></span><span class="tokyobones_haskell Function"> <span class="tokyobones_haskell Statement">::</span> <span class="tokyobones_haskell Type">ComplexData</span> <span class="tokyobones_haskell Statement">-&gt;</span> <span class="tokyobones_haskell Type">Double</span></span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr"> 20 </span><span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Function"><span class="tokyobones_haskell Function">calculate</span></span></span> <span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Delimiter">(</span><span class="tokyobones_haskell Special">ComplexData</span> <span class="tokyobones_haskell Special">_</span> <span class="tokyobones_haskell Special">_</span> <span class="tokyobones_haskell Identifier">values</span><span class="tokyobones_haskell Delimiter">)</span></span> <span class="tokyobones_haskell Statement">=</span> 
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr"> 21 </span><span class="tokyobones_haskell -ibl-indent-char-1">│</span><span class="tokyobones_haskell NonText"> </span><span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Function">fromIntegral</span></span> <span class="tokyobones_haskell Delimiter">(</span><span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Function">sum</span></span> <span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Function"><span class="tokyobones_haskell Identifier">values</span></span></span><span class="tokyobones_haskell Delimiter">)</span> <span class="tokyobones_haskell Statement">/</span> <span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Function">fromIntegral</span></span> <span class="tokyobones_haskell Delimiter">(</span><span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Function">length</span></span> <span class="tokyobones_haskell Identifier"><span class="tokyobones_haskell Function"><span class="tokyobones_haskell Identifier">values</span></span></span><span class="tokyobones_haskell Delimiter">)</span>
<span class="tokyobones_haskell LineNr">  </span><span class="tokyobones_haskell LineNr"> 22 </span>

</pre>
</section>