<script> import "$lib/vicss/tokyonight-day.css" </script>

<section class="tokyonight-day boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr">  1 </span><span class="tokyonight-day -variable"><span class="tokyonight-day Function"><span class="tokyonight-day Special">require</span></span></span> <span class="tokyonight-day String">&quot;options&quot;</span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr">  2 </span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr">  3 </span><span class="tokyonight-day Comment"><span class="tokyonight-day -spell">-- bootstrap plugins &amp; lazy.nvim</span></span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr">  4 </span><span class="tokyonight-day -keyword">local</span> <span class="tokyonight-day -variable">lazypath</span> <span class="tokyonight-day -operator">=</span> <span class="tokyonight-day -variable">vim</span><span class="tokyonight-day -punctuation-delimiter">.</span><span class="tokyonight-day -variable"><span class="tokyonight-day -variable-member">fn</span></span><span class="tokyonight-day -punctuation-delimiter">.</span><span class="tokyonight-day -variable"><span class="tokyonight-day -variable-member"><span class="tokyonight-day Function">stdpath</span></span></span> <span class="tokyonight-day String">&quot;data&quot;</span> <span class="tokyonight-day -operator">..</span> <span class="tokyonight-day String">&quot;/lazy/lazy.nvim&quot;</span> <span class="tokyonight-day Comment"><span class="tokyonight-day -spell">-- path where its going to be installed</span></span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr">  5 </span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr">  6 </span><span class="tokyonight-day Statement">if</span> <span class="tokyonight-day -operator">not</span> <span class="tokyonight-day -variable">vim</span><span class="tokyonight-day -punctuation-delimiter">.</span><span class="tokyonight-day -variable"><span class="tokyonight-day -variable-member">loop</span></span><span class="tokyonight-day -punctuation-delimiter">.</span><span class="tokyonight-day -variable"><span class="tokyonight-day -variable-member"><span class="tokyonight-day Function">fs_stat</span></span></span><span class="tokyonight-day -punctuation-bracket">(</span><span class="tokyonight-day -variable">lazypath</span><span class="tokyonight-day -punctuation-bracket">)</span> <span class="tokyonight-day Statement">then</span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr">  7 </span><span class="tokyonight-day -ibl-indent-char-1">│</span><span class="tokyonight-day -ibl-whitespace-char-1"> </span><span class="tokyonight-day -variable">vim</span><span class="tokyonight-day -punctuation-delimiter">.</span><span class="tokyonight-day -variable"><span class="tokyonight-day -variable-member">fn</span></span><span class="tokyonight-day -punctuation-delimiter">.</span><span class="tokyonight-day -variable"><span class="tokyonight-day -variable-member"><span class="tokyonight-day Function">system</span></span></span> <span class="tokyonight-day -punctuation-bracket"><span class="tokyonight-day -constructor">&#123;</span></span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr">  8 </span><span class="tokyonight-day -ibl-indent-char-1">│</span><span class="tokyonight-day -ibl-whitespace-char-1"> </span><span class="tokyonight-day -ibl-indent-char-1">│</span><span class="tokyonight-day -ibl-whitespace-char-1"> </span><span class="tokyonight-day String">&quot;git&quot;</span><span class="tokyonight-day -punctuation-delimiter">,</span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr">  9 </span><span class="tokyonight-day -ibl-indent-char-1">│</span><span class="tokyonight-day -ibl-whitespace-char-1"> </span><span class="tokyonight-day -ibl-indent-char-1">│</span><span class="tokyonight-day -ibl-whitespace-char-1"> </span><span class="tokyonight-day String">&quot;clone&quot;</span><span class="tokyonight-day -punctuation-delimiter">,</span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr"> 10 </span><span class="tokyonight-day -ibl-indent-char-1">│</span><span class="tokyonight-day -ibl-whitespace-char-1"> </span><span class="tokyonight-day -ibl-indent-char-1">│</span><span class="tokyonight-day -ibl-whitespace-char-1"> </span><span class="tokyonight-day String">&quot;--filter=blob:none&quot;</span><span class="tokyonight-day -punctuation-delimiter">,</span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr"> 11 </span><span class="tokyonight-day -ibl-indent-char-1">│</span><span class="tokyonight-day -ibl-whitespace-char-1"> </span><span class="tokyonight-day -ibl-indent-char-1">│</span><span class="tokyonight-day -ibl-whitespace-char-1"> </span><span class="tokyonight-day String">&quot;https://github.com/folke/lazy.nvim.git&quot;</span><span class="tokyonight-day -punctuation-delimiter">,</span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr"> 12 </span><span class="tokyonight-day -ibl-indent-char-1">│</span><span class="tokyonight-day -ibl-whitespace-char-1"> </span><span class="tokyonight-day -ibl-indent-char-1">│</span><span class="tokyonight-day -ibl-whitespace-char-1"> </span><span class="tokyonight-day String">&quot;--branch=stable&quot;</span><span class="tokyonight-day -punctuation-delimiter">,</span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr"> 13 </span><span class="tokyonight-day -ibl-indent-char-1">│</span><span class="tokyonight-day -ibl-whitespace-char-1"> </span><span class="tokyonight-day -ibl-indent-char-1">│</span><span class="tokyonight-day -ibl-whitespace-char-1"> </span><span class="tokyonight-day -variable">lazypath</span><span class="tokyonight-day -punctuation-delimiter">,</span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr"> 14 </span><span class="tokyonight-day -ibl-indent-char-1">│</span><span class="tokyonight-day -ibl-whitespace-char-1"> </span><span class="tokyonight-day -punctuation-bracket"><span class="tokyonight-day -constructor">&#125;</span></span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr"> 15 </span><span class="tokyonight-day Statement">end</span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr"> 16 </span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr"> 17 </span><span class="tokyonight-day -variable">vim</span><span class="tokyonight-day -punctuation-delimiter">.</span><span class="tokyonight-day -variable"><span class="tokyonight-day -variable-member">opt</span></span><span class="tokyonight-day -punctuation-delimiter">.</span><span class="tokyonight-day -variable"><span class="tokyonight-day -variable-member">rtp</span></span><span class="tokyonight-day -punctuation-delimiter">:</span><span class="tokyonight-day -variable"><span class="tokyonight-day Function">prepend</span></span><span class="tokyonight-day -punctuation-bracket">(</span><span class="tokyonight-day -variable">lazypath</span><span class="tokyonight-day -punctuation-bracket">)</span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr"> 18 </span>
<span class="tokyonight-day SignColumn">  </span><span class="tokyonight-day LineNr"> 19 </span><span class="tokyonight-day -variable"><span class="tokyonight-day Function"><span class="tokyonight-day Special">require</span></span></span><span class="tokyonight-day -punctuation-bracket">(</span><span class="tokyonight-day String">&quot;lazy&quot;</span><span class="tokyonight-day -punctuation-bracket">)</span><span class="tokyonight-day -punctuation-delimiter">.</span><span class="tokyonight-day -variable"><span class="tokyonight-day -variable-member"><span class="tokyonight-day Function">setup</span></span></span><span class="tokyonight-day -punctuation-bracket">(</span><span class="tokyonight-day -variable"><span class="tokyonight-day Function"><span class="tokyonight-day Special">require</span></span></span> <span class="tokyonight-day String">&quot;plugins&quot;</span><span class="tokyonight-day -punctuation-bracket">)</span>

</pre>
</section>