<script> import "$lib/vicss/tokyonight-storm.css" </script>

<section class="tokyonight-storm boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr">  1 </span><span class="tokyonight-storm -keyword">local</span> <span class="tokyonight-storm -variable">utils</span> <span class="tokyonight-storm -operator">=</span> <span class="tokyonight-storm -variable"><span class="tokyonight-storm Function"><span class="tokyonight-storm Special">require</span></span></span> <span class="tokyonight-storm String">&quot;vihtml.utils&quot;</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr">  2 </span><span class="tokyonight-storm -keyword">local</span> <span class="tokyonight-storm -variable"><span class="tokyonight-storm Constant">M</span></span> <span class="tokyonight-storm -operator">=</span> <span class="tokyonight-storm -punctuation-bracket"><span class="tokyonight-storm -constructor">&#123;</span></span><span class="tokyonight-storm -punctuation-bracket"><span class="tokyonight-storm -constructor">&#125;</span></span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr">  3 </span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr">  4 </span><span class="tokyonight-storm -variable"><span class="tokyonight-storm Constant">M</span></span><span class="tokyonight-storm -punctuation-delimiter">.</span><span class="tokyonight-storm -variable"><span class="tokyonight-storm -variable-member"><span class="tokyonight-storm Function">write_file</span></span></span> <span class="tokyonight-storm -operator">=</span> <span class="tokyonight-storm -keyword-function">function</span><span class="tokyonight-storm -punctuation-bracket">(</span><span class="tokyonight-storm -variable"><span class="tokyonight-storm -variable-parameter">path</span></span><span class="tokyonight-storm -punctuation-delimiter">,</span> <span class="tokyonight-storm -variable"><span class="tokyonight-storm -variable-parameter">str</span></span><span class="tokyonight-storm -punctuation-bracket">)</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr">  5 </span><span class="tokyonight-storm -ibl-indent-char-1">│</span><span class="tokyonight-storm -ibl-whitespace-char-1"> </span><span class="tokyonight-storm -keyword">local</span> <span class="tokyonight-storm -variable">file</span> <span class="tokyonight-storm -operator">=</span> <span class="tokyonight-storm -variable"><span class="tokyonight-storm -module-builtin">io</span></span><span class="tokyonight-storm -punctuation-delimiter">.</span><span class="tokyonight-storm -variable"><span class="tokyonight-storm -variable-member"><span class="tokyonight-storm Function">open</span></span></span><span class="tokyonight-storm -punctuation-bracket">(</span><span class="tokyonight-storm -variable">path</span><span class="tokyonight-storm -punctuation-delimiter">,</span> <span class="tokyonight-storm String">&quot;wb&quot;</span><span class="tokyonight-storm -punctuation-bracket">)</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr">  6 </span><span class="tokyonight-storm -ibl-indent-char-1">│</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr">  7 </span><span class="tokyonight-storm -ibl-indent-char-1">│</span><span class="tokyonight-storm -ibl-whitespace-char-1"> </span><span class="tokyonight-storm Statement">if</span> <span class="tokyonight-storm -variable">file</span> <span class="tokyonight-storm Statement">then</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr">  8 </span><span class="tokyonight-storm -ibl-indent-char-1">│</span><span class="tokyonight-storm -ibl-whitespace-char-1"> </span><span class="tokyonight-storm -ibl-indent-char-1">│</span><span class="tokyonight-storm -ibl-whitespace-char-1"> </span><span class="tokyonight-storm -variable">file</span><span class="tokyonight-storm -punctuation-delimiter">:</span><span class="tokyonight-storm -variable"><span class="tokyonight-storm Function">write</span></span><span class="tokyonight-storm -punctuation-bracket">(</span><span class="tokyonight-storm -variable">str</span><span class="tokyonight-storm -punctuation-bracket">)</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr">  9 </span><span class="tokyonight-storm -ibl-indent-char-1">│</span><span class="tokyonight-storm -ibl-whitespace-char-1"> </span><span class="tokyonight-storm -ibl-indent-char-1">│</span><span class="tokyonight-storm -ibl-whitespace-char-1"> </span><span class="tokyonight-storm -variable">file</span><span class="tokyonight-storm -punctuation-delimiter">:</span><span class="tokyonight-storm -variable"><span class="tokyonight-storm Function">close</span></span><span class="tokyonight-storm -punctuation-bracket">(</span><span class="tokyonight-storm -punctuation-bracket">)</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr"> 10 </span><span class="tokyonight-storm -ibl-indent-char-1">│</span><span class="tokyonight-storm -ibl-whitespace-char-1"> </span><span class="tokyonight-storm Statement">end</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr"> 11 </span><span class="tokyonight-storm -keyword-function">end</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr"> 12 </span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr"> 13 </span><span class="tokyonight-storm -variable"><span class="tokyonight-storm Constant">M</span></span><span class="tokyonight-storm -punctuation-delimiter">.</span><span class="tokyonight-storm -variable"><span class="tokyonight-storm -variable-member"><span class="tokyonight-storm Function">get_theme_list</span></span></span> <span class="tokyonight-storm -operator">=</span> <span class="tokyonight-storm -keyword-function">function</span><span class="tokyonight-storm -punctuation-bracket">(</span><span class="tokyonight-storm -punctuation-bracket">)</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr"> 14 </span><span class="tokyonight-storm -ibl-indent-char-1">│</span><span class="tokyonight-storm -ibl-whitespace-char-1"> </span><span class="tokyonight-storm -keyword">local</span> <span class="tokyonight-storm -variable">list</span> <span class="tokyonight-storm -operator">=</span> <span class="tokyonight-storm -punctuation-bracket"><span class="tokyonight-storm -constructor">&#123;</span></span><span class="tokyonight-storm -punctuation-bracket"><span class="tokyonight-storm -constructor">&#125;</span></span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr"> 15 </span><span class="tokyonight-storm -ibl-indent-char-1">│</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr"> 16 </span><span class="tokyonight-storm -ibl-indent-char-1">│</span><span class="tokyonight-storm -ibl-whitespace-char-1"> </span><span class="tokyonight-storm Statement">for</span> <span class="tokyonight-storm -variable">_</span><span class="tokyonight-storm -punctuation-delimiter">,</span> <span class="tokyonight-storm -variable">v</span> <span class="tokyonight-storm -keyword">in</span> <span class="tokyonight-storm -variable"><span class="tokyonight-storm Function"><span class="tokyonight-storm Special">ipairs</span></span></span><span class="tokyonight-storm -punctuation-bracket">(</span><span class="tokyonight-storm -variable"><span class="tokyonight-storm Function"><span class="tokyonight-storm Special">require</span></span></span> <span class="tokyonight-storm String">&quot;themelist&quot;</span><span class="tokyonight-storm -punctuation-bracket">)</span> <span class="tokyonight-storm Statement">do</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr"> 17 </span><span class="tokyonight-storm -ibl-indent-char-1">│</span><span class="tokyonight-storm -ibl-whitespace-char-1"> </span><span class="tokyonight-storm -ibl-indent-char-1">│</span><span class="tokyonight-storm -ibl-whitespace-char-1"> </span><span class="tokyonight-storm -variable">list</span> <span class="tokyonight-storm -operator">=</span> <span class="tokyonight-storm -variable">vim</span><span class="tokyonight-storm -punctuation-delimiter">.</span><span class="tokyonight-storm -variable"><span class="tokyonight-storm -variable-member"><span class="tokyonight-storm Function">list_extend</span></span></span><span class="tokyonight-storm -punctuation-bracket">(</span><span class="tokyonight-storm -variable">list</span><span class="tokyonight-storm -punctuation-delimiter">,</span> <span class="tokyonight-storm -variable">v</span><span class="tokyonight-storm -punctuation-delimiter">.</span><span class="tokyonight-storm -variable"><span class="tokyonight-storm -variable-member">variants</span></span><span class="tokyonight-storm -punctuation-bracket">)</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr"> 18 </span><span class="tokyonight-storm -ibl-indent-char-1">│</span><span class="tokyonight-storm -ibl-whitespace-char-1"> </span><span class="tokyonight-storm Statement">end</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr"> 19 </span><span class="tokyonight-storm -ibl-indent-char-1">│</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr"> 20 </span><span class="tokyonight-storm -ibl-indent-char-1">│</span><span class="tokyonight-storm -ibl-whitespace-char-1"> </span><span class="tokyonight-storm -keyword">return</span> <span class="tokyonight-storm -variable">list</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr"> 21 </span><span class="tokyonight-storm -keyword-function">end</span>
<span class="tokyonight-storm SignColumn">  </span><span class="tokyonight-storm LineNr"> 22 </span>

</pre>
</section>