<script> import "$lib/vicss/tokyonight-moon.css" </script>

<section class="tokyonight-moon boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr">  1 </span><span class="tokyonight-moon -variable"><span class="tokyonight-moon Function"><span class="tokyonight-moon Special">require</span></span></span> <span class="tokyonight-moon String">&quot;options&quot;</span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr">  2 </span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr">  3 </span><span class="tokyonight-moon -keyword">local</span> <span class="tokyonight-moon -variable">lazypath</span> <span class="tokyonight-moon -operator">=</span> <span class="tokyonight-moon -variable">vim</span><span class="tokyonight-moon -punctuation-delimiter">.</span><span class="tokyonight-moon -variable"><span class="tokyonight-moon -variable-member">fn</span></span><span class="tokyonight-moon -punctuation-delimiter">.</span><span class="tokyonight-moon -variable"><span class="tokyonight-moon -variable-member"><span class="tokyonight-moon Function">stdpath</span></span></span> <span class="tokyonight-moon String">&quot;data&quot;</span> <span class="tokyonight-moon -operator">..</span> <span class="tokyonight-moon String">&quot;/lazy/lazy.nvim&quot;</span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr">  4 </span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr">  5 </span><span class="tokyonight-moon Statement">if</span> <span class="tokyonight-moon -operator">not</span> <span class="tokyonight-moon -variable">vim</span><span class="tokyonight-moon -punctuation-delimiter">.</span><span class="tokyonight-moon -variable"><span class="tokyonight-moon -variable-member">loop</span></span><span class="tokyonight-moon -punctuation-delimiter">.</span><span class="tokyonight-moon -variable"><span class="tokyonight-moon -variable-member"><span class="tokyonight-moon Function">fs_stat</span></span></span><span class="tokyonight-moon -punctuation-bracket">(</span><span class="tokyonight-moon -variable">lazypath</span><span class="tokyonight-moon -punctuation-bracket">)</span> <span class="tokyonight-moon Statement">then</span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr">  6 </span><span class="tokyonight-moon -ibl-indent-char-1">│</span><span class="tokyonight-moon -ibl-whitespace-char-1"> </span><span class="tokyonight-moon -variable">vim</span><span class="tokyonight-moon -punctuation-delimiter">.</span><span class="tokyonight-moon -variable"><span class="tokyonight-moon -variable-member">fn</span></span><span class="tokyonight-moon -punctuation-delimiter">.</span><span class="tokyonight-moon -variable"><span class="tokyonight-moon -variable-member"><span class="tokyonight-moon Function">system</span></span></span> <span class="tokyonight-moon -punctuation-bracket"><span class="tokyonight-moon -constructor">&#123;</span></span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr">  7 </span><span class="tokyonight-moon -ibl-indent-char-1">│</span><span class="tokyonight-moon -ibl-whitespace-char-1"> </span><span class="tokyonight-moon -ibl-indent-char-1">│</span><span class="tokyonight-moon -ibl-whitespace-char-1"> </span><span class="tokyonight-moon String">&quot;git&quot;</span><span class="tokyonight-moon -punctuation-delimiter">,</span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr">  8 </span><span class="tokyonight-moon -ibl-indent-char-1">│</span><span class="tokyonight-moon -ibl-whitespace-char-1"> </span><span class="tokyonight-moon -ibl-indent-char-1">│</span><span class="tokyonight-moon -ibl-whitespace-char-1"> </span><span class="tokyonight-moon String">&quot;clone&quot;</span><span class="tokyonight-moon -punctuation-delimiter">,</span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr">  9 </span><span class="tokyonight-moon -ibl-indent-char-1">│</span><span class="tokyonight-moon -ibl-whitespace-char-1"> </span><span class="tokyonight-moon -ibl-indent-char-1">│</span><span class="tokyonight-moon -ibl-whitespace-char-1"> </span><span class="tokyonight-moon String">&quot;--filter=blob:none&quot;</span><span class="tokyonight-moon -punctuation-delimiter">,</span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr"> 10 </span><span class="tokyonight-moon -ibl-indent-char-1">│</span><span class="tokyonight-moon -ibl-whitespace-char-1"> </span><span class="tokyonight-moon -ibl-indent-char-1">│</span><span class="tokyonight-moon -ibl-whitespace-char-1"> </span><span class="tokyonight-moon String">&quot;https://github.com/folke/lazy.nvim.git&quot;</span><span class="tokyonight-moon -punctuation-delimiter">,</span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr"> 11 </span><span class="tokyonight-moon -ibl-indent-char-1">│</span><span class="tokyonight-moon -ibl-whitespace-char-1"> </span><span class="tokyonight-moon -ibl-indent-char-1">│</span><span class="tokyonight-moon -ibl-whitespace-char-1"> </span><span class="tokyonight-moon String">&quot;--branch=stable&quot;</span><span class="tokyonight-moon -punctuation-delimiter">,</span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr"> 12 </span><span class="tokyonight-moon -ibl-indent-char-1">│</span><span class="tokyonight-moon -ibl-whitespace-char-1"> </span><span class="tokyonight-moon -ibl-indent-char-1">│</span><span class="tokyonight-moon -ibl-whitespace-char-1"> </span><span class="tokyonight-moon -variable">lazypath</span><span class="tokyonight-moon -punctuation-delimiter">,</span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr"> 13 </span><span class="tokyonight-moon -ibl-indent-char-1">│</span><span class="tokyonight-moon -ibl-whitespace-char-1"> </span><span class="tokyonight-moon -punctuation-bracket"><span class="tokyonight-moon -constructor">&#125;</span></span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr"> 14 </span><span class="tokyonight-moon Statement">end</span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr"> 15 </span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr"> 16 </span><span class="tokyonight-moon -variable">vim</span><span class="tokyonight-moon -punctuation-delimiter">.</span><span class="tokyonight-moon -variable"><span class="tokyonight-moon -variable-member">opt</span></span><span class="tokyonight-moon -punctuation-delimiter">.</span><span class="tokyonight-moon -variable"><span class="tokyonight-moon -variable-member">rtp</span></span><span class="tokyonight-moon -punctuation-delimiter">:</span><span class="tokyonight-moon -variable"><span class="tokyonight-moon Function">prepend</span></span><span class="tokyonight-moon -punctuation-bracket">(</span><span class="tokyonight-moon -variable">lazypath</span><span class="tokyonight-moon -punctuation-bracket">)</span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr"> 17 </span>
<span class="tokyonight-moon SignColumn">  </span><span class="tokyonight-moon LineNr"> 18 </span><span class="tokyonight-moon -variable"><span class="tokyonight-moon Function"><span class="tokyonight-moon Special">require</span></span></span><span class="tokyonight-moon -punctuation-bracket">(</span><span class="tokyonight-moon String">&quot;lazy&quot;</span><span class="tokyonight-moon -punctuation-bracket">)</span><span class="tokyonight-moon -punctuation-delimiter">.</span><span class="tokyonight-moon -variable"><span class="tokyonight-moon -variable-member"><span class="tokyonight-moon Function">setup</span></span></span><span class="tokyonight-moon -punctuation-bracket">(</span><span class="tokyonight-moon -variable"><span class="tokyonight-moon Function"><span class="tokyonight-moon Special">require</span></span></span> <span class="tokyonight-moon String">&quot;plugins&quot;</span><span class="tokyonight-moon -punctuation-bracket">)</span>

</pre>
</section>