<script> import "$lib/vicss/tokyodark.css" </script>

<section class="tokyodark boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr">  1 </span><span class="tokyodark Keyword">local</span> <span class="tokyodark -variable">utils</span> <span class="tokyodark Operator">=</span> <span class="tokyodark -variable"><span class="tokyodark Function"><span class="tokyodark Special">require</span></span></span> <span class="tokyodark String">&quot;vihtml.utils&quot;</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr">  2 </span><span class="tokyodark Keyword">local</span> <span class="tokyodark -variable"><span class="tokyodark Constant">M</span></span> <span class="tokyodark Operator">=</span> <span class="tokyodark Delimiter"><span class="tokyodark Special">&#123;</span></span><span class="tokyodark Delimiter"><span class="tokyodark Special">&#125;</span></span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr">  3 </span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr">  4 </span><span class="tokyodark -variable"><span class="tokyodark Constant">M</span></span><span class="tokyodark Delimiter">.</span><span class="tokyodark -variable"><span class="tokyodark -variable"><span class="tokyodark Function">write_file</span></span></span> <span class="tokyodark Operator">=</span> <span class="tokyodark Keyword">function</span><span class="tokyodark Delimiter">(</span><span class="tokyodark -variable"><span class="tokyodark -variable">path</span></span><span class="tokyodark Delimiter">,</span> <span class="tokyodark -variable"><span class="tokyodark -variable">str</span></span><span class="tokyodark Delimiter">)</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr">  5 </span><span class="tokyodark -ibl-indent-char-1">│</span><span class="tokyodark -ibl-whitespace-char-1"> </span><span class="tokyodark Keyword">local</span> <span class="tokyodark -variable">file</span> <span class="tokyodark Operator">=</span> <span class="tokyodark -variable"><span class="tokyodark Special">io</span></span><span class="tokyodark Delimiter">.</span><span class="tokyodark -variable"><span class="tokyodark -variable"><span class="tokyodark Function">open</span></span></span><span class="tokyodark Delimiter">(</span><span class="tokyodark -variable">path</span><span class="tokyodark Delimiter">,</span> <span class="tokyodark String">&quot;wb&quot;</span><span class="tokyodark Delimiter">)</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr">  6 </span><span class="tokyodark -ibl-indent-char-1">│</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr">  7 </span><span class="tokyodark -ibl-indent-char-1">│</span><span class="tokyodark -ibl-whitespace-char-1"> </span><span class="tokyodark Keyword">if</span> <span class="tokyodark -variable">file</span> <span class="tokyodark Keyword">then</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr">  8 </span><span class="tokyodark -ibl-indent-char-1">│</span><span class="tokyodark -ibl-whitespace-char-1"> </span><span class="tokyodark -ibl-indent-char-1">│</span><span class="tokyodark -ibl-whitespace-char-1"> </span><span class="tokyodark -variable">file</span><span class="tokyodark Delimiter">:</span><span class="tokyodark -variable"><span class="tokyodark Function">write</span></span><span class="tokyodark Delimiter">(</span><span class="tokyodark -variable">str</span><span class="tokyodark Delimiter">)</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr">  9 </span><span class="tokyodark -ibl-indent-char-1">│</span><span class="tokyodark -ibl-whitespace-char-1"> </span><span class="tokyodark -ibl-indent-char-1">│</span><span class="tokyodark -ibl-whitespace-char-1"> </span><span class="tokyodark -variable">file</span><span class="tokyodark Delimiter">:</span><span class="tokyodark -variable"><span class="tokyodark Function">close</span></span><span class="tokyodark Delimiter">(</span><span class="tokyodark Delimiter">)</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr"> 10 </span><span class="tokyodark -ibl-indent-char-1">│</span><span class="tokyodark -ibl-whitespace-char-1"> </span><span class="tokyodark Keyword">end</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr"> 11 </span><span class="tokyodark Keyword">end</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr"> 12 </span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr"> 13 </span><span class="tokyodark -variable"><span class="tokyodark Constant">M</span></span><span class="tokyodark Delimiter">.</span><span class="tokyodark -variable"><span class="tokyodark -variable"><span class="tokyodark Function">get_theme_list</span></span></span> <span class="tokyodark Operator">=</span> <span class="tokyodark Keyword">function</span><span class="tokyodark Delimiter">(</span><span class="tokyodark Delimiter">)</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr"> 14 </span><span class="tokyodark -ibl-indent-char-1">│</span><span class="tokyodark -ibl-whitespace-char-1"> </span><span class="tokyodark Keyword">local</span> <span class="tokyodark -variable">list</span> <span class="tokyodark Operator">=</span> <span class="tokyodark Delimiter"><span class="tokyodark Special">&#123;</span></span><span class="tokyodark Delimiter"><span class="tokyodark Special">&#125;</span></span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr"> 15 </span><span class="tokyodark -ibl-indent-char-1">│</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr"> 16 </span><span class="tokyodark -ibl-indent-char-1">│</span><span class="tokyodark -ibl-whitespace-char-1"> </span><span class="tokyodark Keyword">for</span> <span class="tokyodark -variable">_</span><span class="tokyodark Delimiter">,</span> <span class="tokyodark -variable">v</span> <span class="tokyodark Keyword">in</span> <span class="tokyodark -variable"><span class="tokyodark Function"><span class="tokyodark Special">ipairs</span></span></span><span class="tokyodark Delimiter">(</span><span class="tokyodark -variable"><span class="tokyodark Function"><span class="tokyodark Special">require</span></span></span> <span class="tokyodark String">&quot;themelist&quot;</span><span class="tokyodark Delimiter">)</span> <span class="tokyodark Keyword">do</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr"> 17 </span><span class="tokyodark -ibl-indent-char-1">│</span><span class="tokyodark -ibl-whitespace-char-1"> </span><span class="tokyodark -ibl-indent-char-1">│</span><span class="tokyodark -ibl-whitespace-char-1"> </span><span class="tokyodark -variable">list</span> <span class="tokyodark Operator">=</span> <span class="tokyodark -variable">vim</span><span class="tokyodark Delimiter">.</span><span class="tokyodark -variable"><span class="tokyodark -variable"><span class="tokyodark Function">list_extend</span></span></span><span class="tokyodark Delimiter">(</span><span class="tokyodark -variable">list</span><span class="tokyodark Delimiter">,</span> <span class="tokyodark -variable">v</span><span class="tokyodark Delimiter">.</span><span class="tokyodark -variable"><span class="tokyodark -variable">variants</span></span><span class="tokyodark Delimiter">)</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr"> 18 </span><span class="tokyodark -ibl-indent-char-1">│</span><span class="tokyodark -ibl-whitespace-char-1"> </span><span class="tokyodark Keyword">end</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr"> 19 </span><span class="tokyodark -ibl-indent-char-1">│</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr"> 20 </span><span class="tokyodark -ibl-indent-char-1">│</span><span class="tokyodark -ibl-whitespace-char-1"> </span><span class="tokyodark Keyword">return</span> <span class="tokyodark -variable">list</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr"> 21 </span><span class="tokyodark Keyword">end</span>
<span class="tokyodark SignColumn">  </span><span class="tokyodark LineNr"> 22 </span>

</pre>
</section>