<script> import "$lib/vihtml/tokyodark_c.css" </script>

<section class="tokyodark_c boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr">  1 </span><span class="tokyodark_c Keyword">#include</span> <span class="tokyodark_c String">&lt;stdio.h&gt;</span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr">  2 </span><span class="tokyodark_c Keyword">#include</span> <span class="tokyodark_c String">&lt;stdlib.h&gt;</span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr">  3 </span><span class="tokyodark_c Keyword">#include</span> <span class="tokyodark_c String">&lt;stdbool.h&gt;</span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr">  4 </span><span class="tokyodark_c Keyword">#include</span> <span class="tokyodark_c String">&lt;math.h&gt;</span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr">  5 </span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr">  6 </span><span class="tokyodark_c Keyword">#define</span> <span class="tokyodark_c -variable"><span class="tokyodark_c Constant"><span class="tokyodark_c Define">PI</span></span></span> <span class="tokyodark_c -variable"><span class="tokyodark_c Number">3.14159</span></span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr">  7 </span><span class="tokyodark_c Keyword">#define</span> <span class="tokyodark_c -variable"><span class="tokyodark_c Constant"><span class="tokyodark_c Macro">SQUARE</span></span></span><span class="tokyodark_c Delimiter">(</span><span class="tokyodark_c -variable"><span class="tokyodark_c -variable">x</span></span><span class="tokyodark_c Delimiter">)</span> <span class="tokyodark_c Delimiter">(</span><span class="tokyodark_c Delimiter">(</span><span class="tokyodark_c -variable">x</span><span class="tokyodark_c Delimiter">)</span> <span class="tokyodark_c Operator">*</span> <span class="tokyodark_c Delimiter">(</span><span class="tokyodark_c -variable">x</span><span class="tokyodark_c Delimiter">)</span><span class="tokyodark_c Delimiter">)</span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr">  8 </span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr">  9 </span><span class="tokyodark_c Keyword">typedef</span> <span class="tokyodark_c Keyword">struct</span> <span class="tokyodark_c Delimiter">&#123;</span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr"> 10 </span><span class="tokyodark_c -ibl-indent-char-1">│</span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c Type">double</span> <span class="tokyodark_c Identifier">x</span><span class="tokyodark_c Delimiter">,</span> <span class="tokyodark_c Identifier">y</span><span class="tokyodark_c Delimiter">;</span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr"> 11 </span><span class="tokyodark_c -ibl-indent-char-1">│</span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c Type">double</span> <span class="tokyodark_c Identifier">radius</span><span class="tokyodark_c Delimiter">;</span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr"> 12 </span><span class="tokyodark_c Delimiter">&#125;</span> <span class="tokyodark_c Type"><span class="tokyodark_c Typedef">Circle</span></span><span class="tokyodark_c Delimiter">;</span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr"> 13 </span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr"> 14 </span><span class="tokyodark_c Type">double</span> <span class="tokyodark_c -variable"><span class="tokyodark_c Function">calculate_area</span></span><span class="tokyodark_c Delimiter">(</span><span class="tokyodark_c Keyword">const</span> <span class="tokyodark_c Type">Circle</span> <span class="tokyodark_c -variable"><span class="tokyodark_c Operator">*</span><span class="tokyodark_c -variable">c</span></span><span class="tokyodark_c Delimiter">)</span> <span class="tokyodark_c Delimiter">&#123;</span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr"> 15 </span><span class="tokyodark_c -ibl-indent-char-1">│</span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c Keyword">return</span> <span class="tokyodark_c -variable"><span class="tokyodark_c Constant">PI</span></span> <span class="tokyodark_c Operator">*</span> <span class="tokyodark_c -variable"><span class="tokyodark_c Constant"><span class="tokyodark_c Function">SQUARE</span></span></span><span class="tokyodark_c Delimiter">(</span><span class="tokyodark_c -_parent"><span class="tokyodark_c -variable">c</span><span class="tokyodark_c Operator">-&gt;</span><span class="tokyodark_c Identifier">radius</span></span><span class="tokyodark_c Delimiter">)</span><span class="tokyodark_c Delimiter">;</span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr"> 16 </span><span class="tokyodark_c Delimiter">&#125;</span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr"> 17 </span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr"> 18 </span><span class="tokyodark_c Type">void</span> <span class="tokyodark_c -variable"><span class="tokyodark_c Function">print_array</span></span><span class="tokyodark_c Delimiter">(</span><span class="tokyodark_c Keyword">const</span> <span class="tokyodark_c Type">char</span> <span class="tokyodark_c -variable"><span class="tokyodark_c Operator">*</span><span class="tokyodark_c -variable">msg</span></span><span class="tokyodark_c Delimiter">,</span> <span class="tokyodark_c Type">int</span> <span class="tokyodark_c -variable"><span class="tokyodark_c Operator">*</span><span class="tokyodark_c -variable">arr</span></span><span class="tokyodark_c Delimiter">,</span> <span class="tokyodark_c Type">size_t</span> <span class="tokyodark_c -variable"><span class="tokyodark_c -variable">size</span></span><span class="tokyodark_c Delimiter">)</span> <span class="tokyodark_c Delimiter">&#123;</span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr"> 19 </span><span class="tokyodark_c -ibl-indent-char-1">│</span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c -variable"><span class="tokyodark_c Function">printf</span></span><span class="tokyodark_c Delimiter">(</span><span class="tokyodark_c String">&quot;%s: &quot;</span><span class="tokyodark_c Delimiter">,</span> <span class="tokyodark_c -variable">msg</span><span class="tokyodark_c Delimiter">)</span><span class="tokyodark_c Delimiter">;</span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr"> 20 </span><span class="tokyodark_c -ibl-indent-char-1">│</span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c Keyword">for</span> <span class="tokyodark_c Delimiter">(</span><span class="tokyodark_c Type">size_t</span> <span class="tokyodark_c -variable">i</span> <span class="tokyodark_c Operator">=</span> <span class="tokyodark_c Number">0</span><span class="tokyodark_c Delimiter">;</span> <span class="tokyodark_c -variable">i</span> <span class="tokyodark_c Operator">&lt;</span> <span class="tokyodark_c -variable">size</span><span class="tokyodark_c Delimiter">;</span> <span class="tokyodark_c -variable">i</span><span class="tokyodark_c Operator">++</span><span class="tokyodark_c Delimiter">)</span> <span class="tokyodark_c -variable"><span class="tokyodark_c Function">printf</span></span><span class="tokyodark_c Delimiter">(</span><span class="tokyodark_c String">&quot;%d &quot;</span><span class="tokyodark_c Delimiter">,</span> <span class="tokyodark_c -variable">arr</span><span class="tokyodark_c Delimiter">[</span><span class="tokyodark_c -variable">i</span><span class="tokyodark_c Delimiter">]</span><span class="tokyodark_c Delimiter">)</span><span class="tokyodark_c Delimiter">;</span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr"> 21 </span><span class="tokyodark_c -ibl-indent-char-1">│</span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c -ibl-whitespace-char-1"> </span><span class="tokyodark_c -variable"><span class="tokyodark_c Function">printf</span></span><span class="tokyodark_c Delimiter">(</span><span class="tokyodark_c String">&quot;<span class="tokyodark_c SpecialChar">\n</span>&quot;</span><span class="tokyodark_c Delimiter">)</span><span class="tokyodark_c Delimiter">;</span>
<span class="tokyodark_c SignColumn">  </span><span class="tokyodark_c LineNr"> 22 </span><span class="tokyodark_c Delimiter">&#125;</span>

</pre>
</section>