<script> import "$lib/vicss/tokyonight.css" </script>

<section class="tokyonight boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr">  1 </span><span class="tokyonight -variable"><span class="tokyonight Function"><span class="tokyonight Special">require</span></span></span> <span class="tokyonight String">&quot;options&quot;</span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr">  2 </span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr">  3 </span><span class="tokyonight Comment"><span class="tokyonight -spell">-- bootstrap plugins &amp; lazy.nvim</span></span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr">  4 </span><span class="tokyonight -keyword">local</span> <span class="tokyonight -variable">lazypath</span> <span class="tokyonight -operator">=</span> <span class="tokyonight -variable">vim</span><span class="tokyonight -punctuation-delimiter">.</span><span class="tokyonight -variable"><span class="tokyonight -variable-member">fn</span></span><span class="tokyonight -punctuation-delimiter">.</span><span class="tokyonight -variable"><span class="tokyonight -variable-member"><span class="tokyonight Function">stdpath</span></span></span> <span class="tokyonight String">&quot;data&quot;</span> <span class="tokyonight -operator">..</span> <span class="tokyonight String">&quot;/lazy/lazy.nvim&quot;</span> <span class="tokyonight Comment"><span class="tokyonight -spell">-- path where its going to be installed</span></span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr">  5 </span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr">  6 </span><span class="tokyonight Statement">if</span> <span class="tokyonight -operator">not</span> <span class="tokyonight -variable">vim</span><span class="tokyonight -punctuation-delimiter">.</span><span class="tokyonight -variable"><span class="tokyonight -variable-member">loop</span></span><span class="tokyonight -punctuation-delimiter">.</span><span class="tokyonight -variable"><span class="tokyonight -variable-member"><span class="tokyonight Function">fs_stat</span></span></span><span class="tokyonight -punctuation-bracket">(</span><span class="tokyonight -variable">lazypath</span><span class="tokyonight -punctuation-bracket">)</span> <span class="tokyonight Statement">then</span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr">  7 </span><span class="tokyonight -ibl-indent-char-1">│</span><span class="tokyonight NonText"> </span><span class="tokyonight -variable">vim</span><span class="tokyonight -punctuation-delimiter">.</span><span class="tokyonight -variable"><span class="tokyonight -variable-member">fn</span></span><span class="tokyonight -punctuation-delimiter">.</span><span class="tokyonight -variable"><span class="tokyonight -variable-member"><span class="tokyonight Function">system</span></span></span> <span class="tokyonight -punctuation-bracket"><span class="tokyonight -constructor">&#123;</span></span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr">  8 </span><span class="tokyonight -ibl-indent-char-1">│</span><span class="tokyonight NonText"> </span><span class="tokyonight -ibl-indent-char-1">│</span><span class="tokyonight NonText"> </span><span class="tokyonight String">&quot;git&quot;</span><span class="tokyonight -punctuation-delimiter">,</span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr">  9 </span><span class="tokyonight -ibl-indent-char-1">│</span><span class="tokyonight NonText"> </span><span class="tokyonight -ibl-indent-char-1">│</span><span class="tokyonight NonText"> </span><span class="tokyonight String">&quot;clone&quot;</span><span class="tokyonight -punctuation-delimiter">,</span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr"> 10 </span><span class="tokyonight -ibl-indent-char-1">│</span><span class="tokyonight NonText"> </span><span class="tokyonight -ibl-indent-char-1">│</span><span class="tokyonight NonText"> </span><span class="tokyonight String">&quot;--filter=blob:none&quot;</span><span class="tokyonight -punctuation-delimiter">,</span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr"> 11 </span><span class="tokyonight -ibl-indent-char-1">│</span><span class="tokyonight NonText"> </span><span class="tokyonight -ibl-indent-char-1">│</span><span class="tokyonight NonText"> </span><span class="tokyonight String">&quot;https://github.com/folke/lazy.nvim.git&quot;</span><span class="tokyonight -punctuation-delimiter">,</span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr"> 12 </span><span class="tokyonight -ibl-indent-char-1">│</span><span class="tokyonight NonText"> </span><span class="tokyonight -ibl-indent-char-1">│</span><span class="tokyonight NonText"> </span><span class="tokyonight String">&quot;--branch=stable&quot;</span><span class="tokyonight -punctuation-delimiter">,</span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr"> 13 </span><span class="tokyonight -ibl-indent-char-1">│</span><span class="tokyonight NonText"> </span><span class="tokyonight -ibl-indent-char-1">│</span><span class="tokyonight NonText"> </span><span class="tokyonight -variable">lazypath</span><span class="tokyonight -punctuation-delimiter">,</span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr"> 14 </span><span class="tokyonight -ibl-indent-char-1">│</span><span class="tokyonight NonText"> </span><span class="tokyonight -punctuation-bracket"><span class="tokyonight -constructor">&#125;</span></span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr"> 15 </span><span class="tokyonight Statement">end</span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr"> 16 </span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr"> 17 </span><span class="tokyonight -variable">vim</span><span class="tokyonight -punctuation-delimiter">.</span><span class="tokyonight -variable"><span class="tokyonight -variable-member">opt</span></span><span class="tokyonight -punctuation-delimiter">.</span><span class="tokyonight -variable"><span class="tokyonight -variable-member">rtp</span></span><span class="tokyonight -punctuation-delimiter">:</span><span class="tokyonight -variable"><span class="tokyonight Function">prepend</span></span><span class="tokyonight -punctuation-bracket">(</span><span class="tokyonight -variable">lazypath</span><span class="tokyonight -punctuation-bracket">)</span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr"> 18 </span>
<span class="tokyonight SignColumn">  </span><span class="tokyonight LineNr"> 19 </span><span class="tokyonight -variable"><span class="tokyonight Function"><span class="tokyonight Special">require</span></span></span><span class="tokyonight -punctuation-bracket">(</span><span class="tokyonight String">&quot;lazy&quot;</span><span class="tokyonight -punctuation-bracket">)</span><span class="tokyonight -punctuation-delimiter">.</span><span class="tokyonight -variable"><span class="tokyonight -variable-member"><span class="tokyonight Function">setup</span></span></span><span class="tokyonight -punctuation-bracket">(</span><span class="tokyonight -variable"><span class="tokyonight Function"><span class="tokyonight Special">require</span></span></span> <span class="tokyonight String">&quot;plugins&quot;</span><span class="tokyonight -punctuation-bracket">)</span>

</pre>
</section>