<script> import "$lib/vicss/tokyonight-night.css" </script>

<section class="tokyonight-night boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr">  1 </span><span class="tokyonight-night -keyword">local</span> <span class="tokyonight-night -variable">utils</span> <span class="tokyonight-night -operator">=</span> <span class="tokyonight-night -variable"><span class="tokyonight-night Function"><span class="tokyonight-night Special">require</span></span></span> <span class="tokyonight-night String">&quot;vihtml.utils&quot;</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr">  2 </span><span class="tokyonight-night -keyword">local</span> <span class="tokyonight-night -variable"><span class="tokyonight-night Constant">M</span></span> <span class="tokyonight-night -operator">=</span> <span class="tokyonight-night -punctuation-bracket"><span class="tokyonight-night -constructor">&#123;</span></span><span class="tokyonight-night -punctuation-bracket"><span class="tokyonight-night -constructor">&#125;</span></span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr">  3 </span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr">  4 </span><span class="tokyonight-night -variable"><span class="tokyonight-night Constant">M</span></span><span class="tokyonight-night -punctuation-delimiter">.</span><span class="tokyonight-night -variable"><span class="tokyonight-night -variable-member"><span class="tokyonight-night Function">write_file</span></span></span> <span class="tokyonight-night -operator">=</span> <span class="tokyonight-night -keyword-function">function</span><span class="tokyonight-night -punctuation-bracket">(</span><span class="tokyonight-night -variable"><span class="tokyonight-night -variable-parameter">path</span></span><span class="tokyonight-night -punctuation-delimiter">,</span> <span class="tokyonight-night -variable"><span class="tokyonight-night -variable-parameter">str</span></span><span class="tokyonight-night -punctuation-bracket">)</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr">  5 </span><span class="tokyonight-night -ibl-indent-char-1">│</span><span class="tokyonight-night -ibl-whitespace-char-1"> </span><span class="tokyonight-night -keyword">local</span> <span class="tokyonight-night -variable">file</span> <span class="tokyonight-night -operator">=</span> <span class="tokyonight-night -variable"><span class="tokyonight-night -module-builtin">io</span></span><span class="tokyonight-night -punctuation-delimiter">.</span><span class="tokyonight-night -variable"><span class="tokyonight-night -variable-member"><span class="tokyonight-night Function">open</span></span></span><span class="tokyonight-night -punctuation-bracket">(</span><span class="tokyonight-night -variable">path</span><span class="tokyonight-night -punctuation-delimiter">,</span> <span class="tokyonight-night String">&quot;wb&quot;</span><span class="tokyonight-night -punctuation-bracket">)</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr">  6 </span><span class="tokyonight-night -ibl-indent-char-1">│</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr">  7 </span><span class="tokyonight-night -ibl-indent-char-1">│</span><span class="tokyonight-night -ibl-whitespace-char-1"> </span><span class="tokyonight-night Statement">if</span> <span class="tokyonight-night -variable">file</span> <span class="tokyonight-night Statement">then</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr">  8 </span><span class="tokyonight-night -ibl-indent-char-1">│</span><span class="tokyonight-night -ibl-whitespace-char-1"> </span><span class="tokyonight-night -ibl-indent-char-1">│</span><span class="tokyonight-night -ibl-whitespace-char-1"> </span><span class="tokyonight-night -variable">file</span><span class="tokyonight-night -punctuation-delimiter">:</span><span class="tokyonight-night -variable"><span class="tokyonight-night Function">write</span></span><span class="tokyonight-night -punctuation-bracket">(</span><span class="tokyonight-night -variable">str</span><span class="tokyonight-night -punctuation-bracket">)</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr">  9 </span><span class="tokyonight-night -ibl-indent-char-1">│</span><span class="tokyonight-night -ibl-whitespace-char-1"> </span><span class="tokyonight-night -ibl-indent-char-1">│</span><span class="tokyonight-night -ibl-whitespace-char-1"> </span><span class="tokyonight-night -variable">file</span><span class="tokyonight-night -punctuation-delimiter">:</span><span class="tokyonight-night -variable"><span class="tokyonight-night Function">close</span></span><span class="tokyonight-night -punctuation-bracket">(</span><span class="tokyonight-night -punctuation-bracket">)</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr"> 10 </span><span class="tokyonight-night -ibl-indent-char-1">│</span><span class="tokyonight-night -ibl-whitespace-char-1"> </span><span class="tokyonight-night Statement">end</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr"> 11 </span><span class="tokyonight-night -keyword-function">end</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr"> 12 </span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr"> 13 </span><span class="tokyonight-night -variable"><span class="tokyonight-night Constant">M</span></span><span class="tokyonight-night -punctuation-delimiter">.</span><span class="tokyonight-night -variable"><span class="tokyonight-night -variable-member"><span class="tokyonight-night Function">get_theme_list</span></span></span> <span class="tokyonight-night -operator">=</span> <span class="tokyonight-night -keyword-function">function</span><span class="tokyonight-night -punctuation-bracket">(</span><span class="tokyonight-night -punctuation-bracket">)</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr"> 14 </span><span class="tokyonight-night -ibl-indent-char-1">│</span><span class="tokyonight-night -ibl-whitespace-char-1"> </span><span class="tokyonight-night -keyword">local</span> <span class="tokyonight-night -variable">list</span> <span class="tokyonight-night -operator">=</span> <span class="tokyonight-night -punctuation-bracket"><span class="tokyonight-night -constructor">&#123;</span></span><span class="tokyonight-night -punctuation-bracket"><span class="tokyonight-night -constructor">&#125;</span></span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr"> 15 </span><span class="tokyonight-night -ibl-indent-char-1">│</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr"> 16 </span><span class="tokyonight-night -ibl-indent-char-1">│</span><span class="tokyonight-night -ibl-whitespace-char-1"> </span><span class="tokyonight-night Statement">for</span> <span class="tokyonight-night -variable">_</span><span class="tokyonight-night -punctuation-delimiter">,</span> <span class="tokyonight-night -variable">v</span> <span class="tokyonight-night -keyword">in</span> <span class="tokyonight-night -variable"><span class="tokyonight-night Function"><span class="tokyonight-night Special">ipairs</span></span></span><span class="tokyonight-night -punctuation-bracket">(</span><span class="tokyonight-night -variable"><span class="tokyonight-night Function"><span class="tokyonight-night Special">require</span></span></span> <span class="tokyonight-night String">&quot;themelist&quot;</span><span class="tokyonight-night -punctuation-bracket">)</span> <span class="tokyonight-night Statement">do</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr"> 17 </span><span class="tokyonight-night -ibl-indent-char-1">│</span><span class="tokyonight-night -ibl-whitespace-char-1"> </span><span class="tokyonight-night -ibl-indent-char-1">│</span><span class="tokyonight-night -ibl-whitespace-char-1"> </span><span class="tokyonight-night -variable">list</span> <span class="tokyonight-night -operator">=</span> <span class="tokyonight-night -variable">vim</span><span class="tokyonight-night -punctuation-delimiter">.</span><span class="tokyonight-night -variable"><span class="tokyonight-night -variable-member"><span class="tokyonight-night Function">list_extend</span></span></span><span class="tokyonight-night -punctuation-bracket">(</span><span class="tokyonight-night -variable">list</span><span class="tokyonight-night -punctuation-delimiter">,</span> <span class="tokyonight-night -variable">v</span><span class="tokyonight-night -punctuation-delimiter">.</span><span class="tokyonight-night -variable"><span class="tokyonight-night -variable-member">variants</span></span><span class="tokyonight-night -punctuation-bracket">)</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr"> 18 </span><span class="tokyonight-night -ibl-indent-char-1">│</span><span class="tokyonight-night -ibl-whitespace-char-1"> </span><span class="tokyonight-night Statement">end</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr"> 19 </span><span class="tokyonight-night -ibl-indent-char-1">│</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr"> 20 </span><span class="tokyonight-night -ibl-indent-char-1">│</span><span class="tokyonight-night -ibl-whitespace-char-1"> </span><span class="tokyonight-night -keyword">return</span> <span class="tokyonight-night -variable">list</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr"> 21 </span><span class="tokyonight-night -keyword-function">end</span>
<span class="tokyonight-night SignColumn">  </span><span class="tokyonight-night LineNr"> 22 </span>

</pre>
</section>