<script> import "$lib/vihtml/tokyobones_go.css" </script>

<section class="tokyobones_go boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr">  1 </span><span class="tokyobones_go Statement">use</span> <span class="tokyobones_go Identifier">std</span><span class="tokyobones_go Delimiter">:</span><span class="tokyobones_go Delimiter">:</span><span class="tokyobones_go Delimiter">&#123;</span><span class="tokyobones_go Statement">collections</span><span class="tokyobones_go Delimiter">:</span><span class="tokyobones_go Delimiter">:</span><span class="tokyobones_go Delimiter">&#123;</span><span class="tokyobones_go Identifier">HashMap</span><span class="tokyobones_go Delimiter">,</span> <span class="tokyobones_go Identifier">HashSet</span><span class="tokyobones_go Delimiter">&#125;</span><span class="tokyobones_go Delimiter">,</span> <span class="tokyobones_go Identifier">fs</span><span class="tokyobones_go Delimiter">:</span><span class="tokyobones_go Delimiter">:</span><span class="tokyobones_go Identifier">File</span><span class="tokyobones_go Delimiter">,</span> <span class="tokyobones_go Identifier">io</span><span class="tokyobones_go Delimiter">:</span><span class="tokyobones_go Delimiter">:</span><span class="tokyobones_go Delimiter">&#123;</span><span class="tokyobones_go Identifier">self</span><span class="tokyobones_go Delimiter">,</span> <span class="tokyobones_go Identifier">Write</span><span class="tokyobones_go Delimiter">&#125;</span><span class="tokyobones_go Delimiter">,</span> <span class="tokyobones_go Identifier">thread</span><span class="tokyobones_go Delimiter">,</span> <span class="tokyobones_go Identifier">time</span><span class="tokyobones_go Delimiter">:</span><span class="tokyobones_go Delimiter">:</span><span class="tokyobones_go Identifier">Duration</span><span class="tokyobones_go Delimiter">&#125;</span><span class="tokyobones_go Delimiter">;</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr">  2 </span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr">  3 </span>#<span class="tokyobones_go Delimiter">[</span><span class="tokyobones_go Identifier"><span class="tokyobones_go Function">derive</span></span><span class="tokyobones_go Delimiter">(</span><span class="tokyobones_go Identifier">Debug</span><span class="tokyobones_go Delimiter">,</span> <span class="tokyobones_go Identifier">Clone</span><span class="tokyobones_go Delimiter">)</span><span class="tokyobones_go Delimiter">]</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr">  4 </span><span class="tokyobones_go Statement">struct</span> <span class="tokyobones_go Type">ComplexData</span> <span class="tokyobones_go Delimiter">&#123;</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr">  5 </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go Identifier"><span class="tokyobones_go Identifier">id</span></span><span class="tokyobones_go Delimiter">:</span> <span class="tokyobones_go Identifier">u32</span><span class="tokyobones_go Delimiter">,</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr">  6 </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go Identifier"><span class="tokyobones_go Identifier">name</span></span><span class="tokyobones_go Delimiter">:</span> <span class="tokyobones_go Identifier">String</span><span class="tokyobones_go Delimiter">,</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr">  7 </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go Identifier"><span class="tokyobones_go Identifier">values</span></span><span class="tokyobones_go Delimiter">:</span> <span class="tokyobones_go Identifier">HashSet</span><span class="tokyobones_go Statement">&lt;</span><span class="tokyobones_go Identifier">u32</span><span class="tokyobones_go Statement">&gt;</span><span class="tokyobones_go Delimiter">,</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr">  8 </span><span class="tokyobones_go Delimiter">&#125;</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr">  9 </span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr"> 10 </span><span class="tokyobones_go Identifier">impl</span> <span class="tokyobones_go Type">ComplexData</span> <span class="tokyobones_go Delimiter">&#123;</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr"> 11 </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go Identifier">fn</span> <span class="tokyobones_go Identifier"><span class="tokyobones_go Function"><span class="tokyobones_go Special">new</span></span></span><span class="tokyobones_go Delimiter">(</span><span class="tokyobones_go Type">id</span><span class="tokyobones_go Delimiter">:</span> <span class="tokyobones_go Identifier">u32</span><span class="tokyobones_go Delimiter">,</span> <span class="tokyobones_go Identifier"><span class="tokyobones_go Identifier">name</span></span><span class="tokyobones_go Delimiter">:</span> <span class="tokyobones_go Statement">&amp;</span><span class="tokyobones_go Identifier">str</span><span class="tokyobones_go Delimiter">)</span> <span class="tokyobones_go Statement">-</span><span class="tokyobones_go Statement">&gt;</span> <span class="tokyobones_go Type">Self</span> <span class="tokyobones_go Delimiter">&#123;</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr"> 12 </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go Identifier">let</span> <span class="tokyobones_go Identifier">mut</span> <span class="tokyobones_go Identifier">values</span> <span class="tokyobones_go Statement">=</span> <span class="tokyobones_go Identifier"><span class="tokyobones_go Identifier">HashSet</span></span><span class="tokyobones_go Delimiter">:</span><span class="tokyobones_go Delimiter">:</span><span class="tokyobones_go Identifier"><span class="tokyobones_go Function"><span class="tokyobones_go Special">new</span></span></span><span class="tokyobones_go Delimiter">(</span><span class="tokyobones_go Delimiter">)</span><span class="tokyobones_go Delimiter">;</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr"> 13 </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go Identifier">values</span><span class="tokyobones_go Delimiter">.</span><span class="tokyobones_go Identifier"><span class="tokyobones_go Function">insert</span></span><span class="tokyobones_go Delimiter">(</span><span class="tokyobones_go Identifier">id</span> <span class="tokyobones_go Statement">*</span> <span class="tokyobones_go Number">10</span><span class="tokyobones_go Delimiter">)</span><span class="tokyobones_go Delimiter">;</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr"> 14 </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go Identifier">values</span><span class="tokyobones_go Delimiter">.</span><span class="tokyobones_go Identifier"><span class="tokyobones_go Function">insert</span></span><span class="tokyobones_go Delimiter">(</span><span class="tokyobones_go Identifier">id</span> <span class="tokyobones_go Statement">*</span> <span class="tokyobones_go Number">20</span><span class="tokyobones_go Delimiter">)</span><span class="tokyobones_go Delimiter">;</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr"> 15 </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go Type">ComplexData</span> <span class="tokyobones_go Delimiter">&#123;</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr"> 16 </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go Identifier">id</span><span class="tokyobones_go Delimiter">,</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr"> 17 </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go Identifier"><span class="tokyobones_go Identifier">name</span></span><span class="tokyobones_go Delimiter">:</span> <span class="tokyobones_go Identifier">name</span><span class="tokyobones_go Delimiter">.</span><span class="tokyobones_go Identifier"><span class="tokyobones_go Function">to_string</span></span><span class="tokyobones_go Delimiter">(</span><span class="tokyobones_go Delimiter">)</span><span class="tokyobones_go Delimiter">,</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr"> 18 </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go Identifier">values</span><span class="tokyobones_go Delimiter">,</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr"> 19 </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go Delimiter">&#125;</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr"> 20 </span><span class="tokyobones_go -ibl-indent-char-1">│</span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go NonText"> </span><span class="tokyobones_go Delimiter">&#125;</span>
<span class="tokyobones_go LineNr">  </span><span class="tokyobones_go LineNr"> 21 </span><span class="tokyobones_go -ibl-indent-char-1">│</span>

</pre>
</section>