<script> import "$lib/vihtml/tundra_go.css" </script>

<section class="tundra_go boxbg pt7 pb3  rounded-2xl">
<pre>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr">  1 </span><span class="tundra_go Label">use</span> <span class="tundra_go -variable">std</span><span class="tundra_go -punctuation-delimiter">:</span><span class="tundra_go -punctuation-delimiter">:</span><span class="tundra_go -punctuation-bracket">&#123;</span><span class="tundra_go Label">collections</span><span class="tundra_go -punctuation-delimiter">:</span><span class="tundra_go -punctuation-delimiter">:</span><span class="tundra_go -punctuation-bracket">&#123;</span><span class="tundra_go -variable">HashMap</span><span class="tundra_go -punctuation-delimiter">,</span> <span class="tundra_go -variable">HashSet</span><span class="tundra_go -punctuation-bracket">&#125;</span><span class="tundra_go -punctuation-delimiter">,</span> <span class="tundra_go -variable">fs</span><span class="tundra_go -punctuation-delimiter">:</span><span class="tundra_go -punctuation-delimiter">:</span><span class="tundra_go -variable">File</span><span class="tundra_go -punctuation-delimiter">,</span> <span class="tundra_go -variable">io</span><span class="tundra_go -punctuation-delimiter">:</span><span class="tundra_go -punctuation-delimiter">:</span><span class="tundra_go -punctuation-bracket">&#123;</span><span class="tundra_go -variable">self</span><span class="tundra_go -punctuation-delimiter">,</span> <span class="tundra_go -variable">Write</span><span class="tundra_go -punctuation-bracket">&#125;</span><span class="tundra_go -punctuation-delimiter">,</span> <span class="tundra_go -variable">thread</span><span class="tundra_go -punctuation-delimiter">,</span> <span class="tundra_go -variable">time</span><span class="tundra_go -punctuation-delimiter">:</span><span class="tundra_go -punctuation-delimiter">:</span><span class="tundra_go -variable">Duration</span><span class="tundra_go -punctuation-bracket">&#125;</span><span class="tundra_go -punctuation-delimiter">;</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr">  2 </span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr">  3 </span>#<span class="tundra_go -punctuation-bracket">[</span><span class="tundra_go -variable"><span class="tundra_go -function-call">derive</span></span><span class="tundra_go -punctuation-bracket">(</span><span class="tundra_go -variable">Debug</span><span class="tundra_go -punctuation-delimiter">,</span> <span class="tundra_go -variable">Clone</span><span class="tundra_go -punctuation-bracket">)</span><span class="tundra_go -punctuation-bracket">]</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr">  4 </span><span class="tundra_go -keyword">struct</span> <span class="tundra_go Type">ComplexData</span> <span class="tundra_go -punctuation-bracket">&#123;</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr">  5 </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go -variable"><span class="tundra_go -variable-member">id</span></span><span class="tundra_go -punctuation-delimiter">:</span> <span class="tundra_go -variable">u32</span><span class="tundra_go -punctuation-delimiter">,</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr">  6 </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go -variable"><span class="tundra_go -variable-member">name</span></span><span class="tundra_go -punctuation-delimiter">:</span> <span class="tundra_go -variable">String</span><span class="tundra_go -punctuation-delimiter">,</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr">  7 </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go -variable"><span class="tundra_go -variable-member">values</span></span><span class="tundra_go -punctuation-delimiter">:</span> <span class="tundra_go -variable">HashSet</span><span class="tundra_go -operator">&lt;</span><span class="tundra_go -variable">u32</span><span class="tundra_go -operator">&gt;</span><span class="tundra_go -punctuation-delimiter">,</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr">  8 </span><span class="tundra_go -punctuation-bracket">&#125;</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr">  9 </span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr"> 10 </span><span class="tundra_go -variable">impl</span> <span class="tundra_go Type">ComplexData</span> <span class="tundra_go -punctuation-bracket">&#123;</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr"> 11 </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go -variable">fn</span> <span class="tundra_go -variable"><span class="tundra_go -function-call"><span class="tundra_go -function-builtin">new</span></span></span><span class="tundra_go -punctuation-bracket">(</span><span class="tundra_go Type">id</span><span class="tundra_go -punctuation-delimiter">:</span> <span class="tundra_go -variable">u32</span><span class="tundra_go -punctuation-delimiter">,</span> <span class="tundra_go -variable"><span class="tundra_go -variable-member">name</span></span><span class="tundra_go -punctuation-delimiter">:</span> <span class="tundra_go -operator">&amp;</span><span class="tundra_go -variable">str</span><span class="tundra_go -punctuation-bracket">)</span> <span class="tundra_go -operator">-</span><span class="tundra_go -operator">&gt;</span> <span class="tundra_go Type">Self</span> <span class="tundra_go -punctuation-bracket">&#123;</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr"> 12 </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go -variable">let</span> <span class="tundra_go -variable">mut</span> <span class="tundra_go -variable">values</span> <span class="tundra_go -operator">=</span> <span class="tundra_go -variable"><span class="tundra_go -variable-member">HashSet</span></span><span class="tundra_go -punctuation-delimiter">:</span><span class="tundra_go -punctuation-delimiter">:</span><span class="tundra_go -variable"><span class="tundra_go -function-call"><span class="tundra_go -function-builtin">new</span></span></span><span class="tundra_go -punctuation-bracket">(</span><span class="tundra_go -punctuation-bracket">)</span><span class="tundra_go -punctuation-delimiter">;</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr"> 13 </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go -variable">values</span><span class="tundra_go -punctuation-delimiter">.</span><span class="tundra_go -property"><span class="tundra_go -function-method-call">insert</span></span><span class="tundra_go -punctuation-bracket">(</span><span class="tundra_go -variable">id</span> <span class="tundra_go -operator">*</span> <span class="tundra_go -number">10</span><span class="tundra_go -punctuation-bracket">)</span><span class="tundra_go -punctuation-delimiter">;</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr"> 14 </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go -variable">values</span><span class="tundra_go -punctuation-delimiter">.</span><span class="tundra_go -property"><span class="tundra_go -function-method-call">insert</span></span><span class="tundra_go -punctuation-bracket">(</span><span class="tundra_go -variable">id</span> <span class="tundra_go -operator">*</span> <span class="tundra_go -number">20</span><span class="tundra_go -punctuation-bracket">)</span><span class="tundra_go -punctuation-delimiter">;</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr"> 15 </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go Type">ComplexData</span> <span class="tundra_go -punctuation-bracket">&#123;</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr"> 16 </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go -variable">id</span><span class="tundra_go -punctuation-delimiter">,</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr"> 17 </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go -variable"><span class="tundra_go -variable-member">name</span></span><span class="tundra_go -punctuation-delimiter">:</span> <span class="tundra_go -variable">name</span><span class="tundra_go -punctuation-delimiter">.</span><span class="tundra_go -property"><span class="tundra_go -function-method-call">to_string</span></span><span class="tundra_go -punctuation-bracket">(</span><span class="tundra_go -punctuation-bracket">)</span><span class="tundra_go -punctuation-delimiter">,</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr"> 18 </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go -variable">values</span><span class="tundra_go -punctuation-delimiter">,</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr"> 19 </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go -punctuation-bracket">&#125;</span>
<span class="tundra_go SignColumn">  </span><span class="tundra_go LineNr"> 20 </span><span class="tundra_go NonText">│</span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go NonText"> </span><span class="tundra_go -punctuation-bracket">&#125;</span>

</pre>
</section>