return {
  { "folke/tokyonight.nvim", name = "tokyonight" },
  { "edeneast/nightfox.nvim", name = "nightfox" },
  { "tiagovla/tokyodark.nvim", name = "tokyodark" },
  { "rose-pine/neovim", name = "rose-pine" },
  { "olimorris/onedarkpro.nvim", name = "onedark" },
  { "bluz71/vim-nightfly-colors", name = "nightfly" },
  { "projekt0n/github-nvim-theme", name = "github_dark" },
  { "marko-cerovac/material.nvim", name = "material" },
  { "shaunsingh/nord.nvim", name = "nord" },
  { "AlexvZyl/nordic.nvim", name = "nordic" },
  { "nyoom-engineering/oxocarbon.nvim", name = "oxocarbon" },
  { "ribru17/bamboo.nvim", name = "bamboo" },
  { "mcchrish/zenbones.nvim", name = "zenbones",    dependencies = "rktjmp/lush.nvim", },
  { "savq/melange-nvim", name = "melange" },
  { "olivercederborg/poimandres.nvim", name = "poimandres" },
  { "maxmx03/fluoromachine.nvim", name = "fluoromachine" },
  { "oxfist/night-owl.nvim", name = "night-owl" },
  { "uloco/bluloco.nvim", name = "bluloco" },
  { "xero/miasma.nvim", name = "miasma" },
}
