name: Gen html by nvim

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  bootstrap-nvim:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Prepare
      env:
        NVIM_TAG: stable
      run: |
        wget https://github.com/neovim/neovim/releases/download/${NVIM_TAG}/nvim-linux64.tar.gz
        tar -zxf nvim-linux64.tar.gz
        sudo ln -s "$PWD"/nvim-linux64/bin/nvim /usr/local/bin
        cp -r tiny ~/.config/nvim
        
    - name: use nvim tohtml
      run: |
        nvim --headless +"q"
        nvim --headless +":lua require 'vihtml'" +"q"

    - name: Push changes
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add src
        git commit -m "Auto-update generated HTML files"
        git push https://x-access-token:${PAT}@github.com/siduck/neovimthemes.git

